package ar.com.lamontana;

import static org.assertj.core.api.Assertions.*;
import ar.com.lamontana.configuracion.*;
import ar.com.lamontana.identidad.IdentidadController;
import ar.com.lamontana.identidad.IdentidadService;
import io.zonky.test.db.postgres.embedded.EmbeddedPostgres;
import java.net.*;
import java.io.*;
import jakarta.mail.Session;
import jakarta.mail.internet.MimeMessage;
import java.util.concurrent.*;
import java.util.regex.Pattern;
import java.net.http.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.time.Duration;
import java.time.Instant;
import java.util.*;
import java.util.concurrent.TimeUnit;
import org.junit.jupiter.api.*;
import org.springframework.boot.builder.SpringApplicationBuilder;
import org.springframework.context.ConfigurableApplicationContext;
import org.springframework.dao.DataAccessException;
import org.springframework.jdbc.core.JdbcTemplate;
import tools.jackson.databind.JsonNode;
import tools.jackson.databind.json.JsonMapper;

class ActivacionConfiguracionIntegrationTest {
    private static final JsonMapper JSON=JsonMapper.builder().build();
    private static final String EMAIL="entrega@example.test",CLAVE="ConfiguracionEntrega123!",TOKEN="token-local-entrega-configuracion-exclusivo-test";
    private EmbeddedPostgres pg;
    private CapturaSmtp smtp;
    private ConfigurableApplicationContext app;
    private JdbcTemplate jdbc;
    private Path archivos;
    private HttpClient admin;
    private int port;
    private String id,a,b,servicio,formato,papel,terminacion,comercial;
    private JsonNode borrador;
    @BeforeEach void iniciar()throws Exception {
        archivos=Files.createTempDirectory("lamontana-entrega-");smtp=new CapturaSmtp();pg=EmbeddedPostgres.builder().start();arrancar();
        app.getBean(IdentidadService.class).crearPropietario(new IdentidadController.AltaPropietario(TOKEN,"Admin","Entrega",EMAIL,CLAVE));admin=cliente();login(admin,EMAIL);
        var creado=post(admin,"/api/admin/configuracion/borradores",Map.of("operacion",UUID.randomUUID().toString()));status(creado,200);borrador=JSON.readTree(creado.body());id=borrador.get("codigoPublico").asString();
        a=sucursal("A");b=sucursal("B");status(post(admin,"/api/admin/catalogo/servicios",Map.of("codigo","IMP","nombre","Impresión","tipo","IMPRESION")),201);servicio=jdbc.queryForObject("SELECT codigo_publico::text FROM lamontana.servicio WHERE codigo='IMP'",String.class);
        var modelo=comando();modelo.put("modelo","MANUAL");aceptar(put(admin,base()+"/modelo",modelo));servicios(List.of(a));
    }
    @AfterEach void cerrar()throws Exception{if(app!=null)app.close();if(pg!=null)pg.close();if(smtp!=null)smtp.close();if(archivos!=null)Files.deleteIfExists(archivos);}
    private void arrancar(){arrancar(false);}
    private void arrancar(boolean automatico){app=new SpringApplicationBuilder(LaMontanaApplication.class).run("--server.port=0","--lamontana.configuracion.ejecucion-automatica="+automatico,"--spring.datasource.url="+pg.getJdbcUrl("postgres","postgres"),"--spring.datasource.username=postgres","--spring.datasource.password=","--lamontana.archivos.directorio="+archivos,"--lamontana.instalacion.token="+TOKEN,"--spring.mail.host=127.0.0.1","--spring.mail.port="+smtp.port());port=Integer.parseInt(app.getEnvironment().getProperty("local.server.port"));jdbc=app.getBean(JdbcTemplate.class);}


    private JsonNode revision()throws Exception{var r=get(admin,base()+"/revision");status(r,200);return JSON.readTree(r.body());}
    private Set<String> codigos(JsonNode r){var c=new HashSet<String>();for(var h:r.get("hallazgos"))c.add(h.get("codigo").asString());return c;}
    private void preparar()throws Exception{
        status(post(admin,"/api/admin/catalogo/formatos",Map.of("codigo","F","nombre","Formato","anchoMm","210","altoMm","297")),201);
        status(post(admin,"/api/admin/catalogo/papeles",Map.of("codigo","P","nombre","Papel","gramaje","80","terminacion","Mate")),201);
        status(post(admin,"/api/admin/catalogo/servicios",Map.of("codigo","TERM","nombre","Acabado","tipo","TERMINACION")),201);
        formato=jdbc.queryForObject("SELECT codigo_publico::text FROM lamontana.formato",String.class);
        papel=jdbc.queryForObject("SELECT codigo_publico::text FROM lamontana.papel",String.class);
        terminacion=jdbc.queryForObject("SELECT codigo_publico::text FROM lamontana.servicio WHERE codigo='TERM'",String.class);
        var m=comando();m.putAll(Map.of("modelo","CONDICIONAL","criterio","MONTO_TOTAL"));aceptar(put(admin,base()+"/modelo",m));
        var p=comando();p.put("pagos",Map.of("medios",List.of("TRANSFERENCIA","EFECTIVO"),"instruccionesTransferencia","Cuenta de prueba","vigenciaCotizacionMinutos",90,"exigirSena",true,"condicionSena","SUPERAR_UMBRAL_APROBACION","tipoSena","PORCENTAJE","valorSena","25","umbralAprobacion","30"));aceptar(put(admin,base()+"/pagos",p));
        var r=comando();r.put("metodoAsignacion","MANUAL");r.put("serviciosPorSucursal",List.of(Map.of("sucursal",a,"servicios",List.of(servicio,terminacion)),Map.of("sucursal",b,"servicios",List.of(servicio))));aceptar(put(admin,base()+"/recursos",r));
        for(String origen:List.of(a,b)){var i=comando();i.putAll(Map.of("sucursal",origen,"nombre","Impresora "+origen,"formatos",List.of(formato),"admiteColor",false,"admiteDobleFaz",true,"capacidadHojas",2,"estado","OPERATIVA"));aceptar(post(admin,base()+"/impresoras",i));}
        guardar("1","1",List.of("RETIRO_SUCURSAL","ENVIO_DOMICILIO"),List.of(horario(a,semana("09:00","18:00")),horario(b,semana("09:00","18:00"))));
        var z=comando();z.putAll(Map.of("codigo","CENTRO","nombre","Centro","zonaHoraria","America/Argentina/Buenos_Aires","costo","12.50","habilitada",true,"territorios",List.of(territorio()),"franjas",List.of(Map.of("dia",1,"apertura","09:00","cierre","18:00","capacidadPedidos",2,"habilitada",true))));aceptar(post(admin,ruta()+"/zonas",z));
        publicar(null,"2.00",true,false);
    }
    private Map<String,Object> territorio(){return Map.of("codigoPostal","5600","localidad","San Rafael","provincia","Mendoza");}
    private Map<String,Object> oferta(String id,String base,String precio,int minutos,boolean habilitada){return Map.of("servicio",id,"nombreVisible",id.equals(servicio)?"Impresión":"Acabado","basePrecio",base,"precio",precio,"preparacionMinutos",minutos,"habilitado",habilitada,"compatibilidades",id.equals(servicio)?List.of():List.of(Map.of("formato",formato,"papel",papel)));}
    private void publicar(Instant fecha,String precio,boolean term,boolean color)throws Exception{
        var c=new HashMap<String,Object>();c.put("operacion",UUID.randomUUID().toString());c.put("versionBase",comercial);c.put("motivo","Revisión de prueba");c.put("programadaPara",fecha==null?null:fecha.toString());
        var tarifas=new ArrayList<Map<String,Object>>();tarifas.add(Map.of("formato",formato,"papel",papel,"color","BLANCO_NEGRO","precio",precio,"recargoDobleFaz","0.50","habilitada",true));if(color)tarifas.add(Map.of("formato",formato,"papel",papel,"color","COLOR","precio","5","recargoDobleFaz","0","habilitada",true));c.put("tarifas",tarifas);c.put("servicios",List.of(oferta(servicio,"POR_CARILLA","0",30,true),oferta(terminacion,"POR_HOJA","1.25",120,term)));
        var r=post(admin,"/api/admin/catalogo/revisiones",c);status(r,200);if(fecha==null)comercial=JSON.readTree(r.body()).get("codigoPublico").asString();
    }
    private Map<String,Object> ejemplo(String modalidad){var c=new HashMap<String,Object>();c.putAll(Map.of("version",borrador.get("version").asLong(),"revisionComercial",comercial,"sucursal",a,"item",Map.of("servicio",servicio,"formato",formato,"papel",papel,"color","BLANCO_NEGRO","paginas",3,"copias",2,"dobleFaz",true,"terminaciones",List.of(terminacion)),"modalidad",modalidad,"recibidoEn","2026-09-28T12:00:00Z"));if(modalidad.equals("ENVIO_DOMICILIO"))c.put("territorio",territorio());return c;}
    private JsonNode simular(Map<String,Object> e)throws Exception{var r=post(admin,base()+"/revision/simular",e);status(r,200);return JSON.readTree(r.body());}
    private void configurarSegundo()throws Exception{
        var m=comando();m.putAll(Map.of("modelo","CONDICIONAL","criterio","MONTO_TOTAL"));aceptar(put(admin,base()+"/modelo",m));
        var p=comando();p.put("pagos",Map.of("medios",List.of("TRANSFERENCIA","EFECTIVO"),"instruccionesTransferencia","Cuenta de prueba","vigenciaCotizacionMinutos",90,"exigirSena",true,"condicionSena","SUPERAR_UMBRAL_APROBACION","tipoSena","PORCENTAJE","valorSena","25","umbralAprobacion","30"));aceptar(put(admin,base()+"/pagos",p));
        var r=comando();r.put("metodoAsignacion","MANUAL");r.put("serviciosPorSucursal",List.of(Map.of("sucursal",a,"servicios",List.of(servicio,terminacion)),Map.of("sucursal",b,"servicios",List.of(servicio))));aceptar(put(admin,base()+"/recursos",r));
        for(String origen:List.of(a,b)){var i=comando();i.putAll(Map.of("sucursal",origen,"nombre","Impresora "+origen,"formatos",List.of(formato),"admiteColor",false,"admiteDobleFaz",true,"capacidadHojas",2,"estado","OPERATIVA"));aceptar(post(admin,base()+"/impresoras",i));}
        guardar("1","1",List.of("RETIRO_SUCURSAL","ENVIO_DOMICILIO"),List.of(horario(a,semana("09:00","18:00")),horario(b,semana("09:00","18:00"))));
        var z=comando();z.putAll(Map.of("codigo","CENTRO2","nombre","Centro2","zonaHoraria","America/Argentina/Buenos_Aires","costo","12.50","habilitada",true,"territorios",List.of(territorio()),"franjas",List.of(Map.of("dia",1,"apertura","09:00","cierre","18:00","capacidadPedidos",2,"habilitada",true))));aceptar(post(admin,ruta()+"/zonas",z));
    }
    private Map<String,Object> decision()throws Exception{var r=revision();return new HashMap<>(Map.of("version",borrador.get("version").asLong(),"revisionComercial",comercial,"huellaRevision",r.get("huella").asString(),"advertenciasRevisadas",true,"motivo","Habilitar operación configurada"));}
    private Map<String,Object> solicitud()throws Exception{return new HashMap<>(Map.of("operacion",UUID.randomUUID().toString(),"decision",decision(),"contrasena",CLAVE));}
    private String rutaActivar(){return base()+"/activacion";}
    private String solicitar(Map<String,Object> s)throws Exception{status(post(admin,rutaActivar()+"/solicitar",s),200);return smtp.recibir().token();}
    private Map<String,Object> confirmacion(Map<String,Object> s,String token){var c=new HashMap<>(s);c.put("codigo",token);return c;}
    private JsonNode activar()throws Exception{var s=solicitud();var r=post(admin,rutaActivar()+"/confirmar",confirmacion(s,solicitar(s)));status(r,200);assertThat(JSON.readTree(r.body()).get("estado").asString()).isEqualTo("EXITOSO");return JSON.readTree(r.body()).get("version");}
    private void cooldown(){jdbc.update("UPDATE lamontana.autorizacion_configuracion SET fecha_emision=clock_timestamp()-interval '2 minutes'");}
    private JsonNode copiarBase(String origen,UUID operacion)throws Exception{var r=post(admin,"/api/admin/configuracion/historial/"+origen+"/base",Map.of("operacion",operacion));status(r,200);return JSON.readTree(r.body());}
    private void adoptarCopia(JsonNode copia){borrador=copia;id=copia.get("codigoPublico").asString();}
    private void guardarFaseCopia(int fase)throws Exception{var in=comando();String path="";switch(fase){case 2-> {path="/modelo";in.put("modelo",borrador.get("modelo"));in.put("criterio",borrador.get("criterio"));}case 3->{path="/pagos";in.put("pagos",borrador.get("pagos"));}case 4->{path="/recursos";in.put("metodoAsignacion",borrador.get("recursos").get("metodoAsignacion"));in.put("serviciosPorSucursal",borrador.get("recursos").get("serviciosPorSucursal"));}case 5->{path="/entrega";for(String key:List.of("preparacionHoras","trasladoHoras","modalidades","horariosPorSucursal"))in.put(key,borrador.get("entrega").get(key));}default->throw new IllegalArgumentException();}aceptar(put(admin,base()+path,in));}
    private Map<String,Object> confirmarCopiaSolicitud()throws Exception{var r=revision();return Map.of("operacion",UUID.randomUUID(),"version",borrador.get("version").asLong(),"revisionComercial",r.get("catalogo").get("actual").get("codigoPublico").asString(),"huellaRevision",r.get("huella").asString(),"advertenciasRevisadas",true);}
    private void confirmarCopia(Map<String,Object> in)throws Exception{var r=post(admin,base()+"/revision/confirmar",in);status(r,200);borrador=JSON.readTree(r.body()).get("borrador");}
    @Test void baseCopiaIntegraIdentidadesOrigenYBarridoSinDuplicarNiReactivar()throws Exception{
        preparar();var p=comando();p.putAll(Map.of("codigo","PUNTO","nombre","Punto central","calle","Prueba","numero","10","localidad","Localidad","provincia","Provincia","codigoPostal","1234","zonaHoraria","America/Argentina/Buenos_Aires","sucursales",List.of(Map.of("sucursal",a,"costo","2.50","habilitado",true,"franjas",List.of(Map.of("dia",2,"apertura","09:00","cierre","12:00","capacidadPedidos",3,"habilitada",true))),Map.of("sucursal",b,"costo","0.00","habilitado",true,"franjas",List.of(Map.of("dia",3,"apertura","15:00","cierre","18:00","capacidadPedidos",0,"habilitada",false))))));aceptar(post(admin,ruta()+"/puntos",p));
        var i=comando();i.putAll(Map.of("sucursal",a,"nombre","Retirada histórica","formatos",List.of(formato),"admiteColor",true,"admiteDobleFaz",false,"capacidadHojas",30,"estado","DESHABILITADA"));aceptar(post(admin,base()+"/impresoras",i));String retirada=null;for(var printer:borrador.get("recursos").get("impresoras"))if(printer.get("nombre").asString().equals("Retirada histórica"))retirada=printer.get("codigoPublico").asString();var retirar=comando();retirar.put("motivo","Retirada declarada");aceptar(post(admin,base()+"/impresoras/"+retirada+"/retirar",retirar));
        var activa=activar();String origen=id;int impresoras=contar("impresora"),puntos=contar("punto_entrega"),zonas=contar("zona_entrega"),catalogo=contar("catalogo_revision"),desafios=contar("autorizacion_configuracion");UUID op=UUID.randomUUID();var copia=copiarBase(origen,op);assertThat(copia.get("copia").get("origen").asString()).isEqualTo(origen);assertThat(copia.get("copia").get("fasesConfirmadas").size()).isZero();assertThat(copia.get("copia").get("barridoInicial").size()).isPositive();
        for(String field:List.of("modelo","criterio","pagos","recursos","entrega"))assertThat(copia.get(field)).as(field).isEqualTo(activa.get("configuracion").get(field));assertThat(copia.get("estado").asString()).isEqualTo("EN_PREPARACION");assertThat(estado().get("activa")).isEqualTo(activa);assertThat(contar("impresora")).isEqualTo(impresoras);assertThat(contar("punto_entrega")).isEqualTo(puntos);assertThat(contar("zona_entrega")).isEqualTo(zonas);assertThat(contar("catalogo_revision")).isEqualTo(catalogo);assertThat(contar("autorizacion_configuracion")).isEqualTo(desafios);assertThat(contar("activacion_configuracion")).isEqualTo(1);assertThat(contar("programacion_configuracion")).isZero();assertThat(copiarBase(origen,op)).isEqualTo(copia);
        status(post(admin,"/api/admin/configuracion/historial/"+origen+"/base",Map.of("operacion",UUID.randomUUID())),409);adoptarCopia(copia);status(post(admin,rutaActivar()+"/solicitar",solicitud()),409);assertThat(historial("/"+origen).get("base").get("permitida").asBoolean()).isFalse();app.close();arrancar();assertThat(estado().get("borrador")).isEqualTo(copia);
    }
    @Test void baseReconfirmacionObligatoriaInvalidacionYActivacionSegura()throws Exception{
        preparar();activar();String origen=id;UUID op=UUID.randomUUID();adoptarCopia(copiarBase(origen,op));status(post(admin,base()+"/revision/confirmar",confirmarCopiaSolicitud()),409);guardarFaseCopia(5);assertThat(borrador.get("copia").get("fasesConfirmadas").toString()).isEqualTo("[5]");guardarFaseCopia(2);assertThat(borrador.get("copia").get("fasesConfirmadas").toString()).isEqualTo("[2]");guardarFaseCopia(3);guardarFaseCopia(4);guardarFaseCopia(5);assertThat(revision().get("bloqueos").asLong()).isZero();cooldown();status(post(admin,rutaActivar()+"/solicitar",solicitud()),409);
        var confirmacion=confirmarCopiaSolicitud();confirmarCopia(confirmacion);long edicion=borrador.get("version").asLong();confirmarCopia(confirmacion);assertThat(borrador.get("version").asLong()).isEqualTo(edicion);assertThat(borrador.get("copia").get("fasesConfirmadas").toString()).isEqualTo("[2,3,4,5,6]");
        String impresora=borrador.get("recursos").get("impresoras").get(0).get("codigoPublico").asString();var cambiar=comando();cambiar.putAll(Map.of("estado","DESHABILITADA","motivo","Revisión de recurso"));aceptar(post(admin,base()+"/impresoras/"+impresora+"/estado",cambiar));assertThat(borrador.get("copia").get("fasesConfirmadas").toString()).isEqualTo("[2,3]");status(post(admin,base()+"/revision/confirmar",confirmacion),409);cambiar=comando();cambiar.putAll(Map.of("estado","OPERATIVA","motivo","Recurso revisado"));aceptar(post(admin,base()+"/impresoras/"+impresora+"/estado",cambiar));guardarFaseCopia(4);guardarFaseCopia(5);confirmarCopia(confirmarCopiaSolicitud());
        publicar(null,"9",true,true);status(post(admin,rutaActivar()+"/solicitar",solicitud()),409);confirmarCopia(confirmarCopiaSolicitud());var activa=activar();assertThat(activa.get("predecesora").asString()).isEqualTo(origen);assertThat(activa.get("configuracion").get("copia").get("origen").asString()).isEqualTo(origen);assertThat(copiarBase(origen,op).get("estado").asString()).isEqualTo("ACTIVA");assertThat(contar("origen_configuracion")).isEqualTo(1);assertThat(historial("/"+id).get("copia").get("origen").asString()).isEqualTo(origen);
    }
    @Test void baseRollbackDeCopiaConcurrenciaBarridoDinamicoYPermisos()throws Exception{
        preparar();activar();String origen=id;var real=app.getBean(CopiaParametrosConfiguracion.class);var fallida=org.mockito.Mockito.mock(CopiaParametrosConfiguracion.class);org.mockito.Mockito.doAnswer(call->{real.copiar(call.getArgument(0),call.getArgument(1));throw new IllegalStateException("Fallo de copia de prueba");}).when(fallida).copiar(org.mockito.ArgumentMatchers.anyLong(),org.mockito.ArgumentMatchers.anyLong());org.springframework.test.util.ReflectionTestUtils.setField(app.getBean(CopiaConfiguracionService.class),"parametros",fallida);var in=Map.of("operacion",UUID.randomUUID());int comprobantes=contar("comprobante_configuracion"),versiones=contar("configuracion_version");var errorCopia=post(admin,"/api/admin/configuracion/historial/"+origen+"/base",in);status(errorCopia,500);assertThat(errorCopia.body()).doesNotContain("Fallo de copia de prueba","stackTrace");status(get(admin,"/error"),403);status(get(cliente(),"/error"),401);assertThat(contar("origen_configuracion")).isZero();assertThat(contar("configuracion_version")).isEqualTo(versiones);assertThat(contar("comprobante_configuracion")).isEqualTo(comprobantes);org.springframework.test.util.ReflectionTestUtils.setField(app.getBean(CopiaConfiguracionService.class),"parametros",real);
        jdbc.update("UPDATE lamontana.sucursal SET estado='DESACTIVADA'");var r1=request(admin,"POST","/api/admin/configuracion/historial/"+origen+"/base",in);var r2=request(admin,"POST","/api/admin/configuracion/historial/"+origen+"/base",in);var a1=admin.sendAsync(r1,HttpResponse.BodyHandlers.ofString());var a2=admin.sendAsync(r2,HttpResponse.BodyHandlers.ofString());var c1=a1.get();var c2=a2.get();status(c1,200);status(c2,200);assertThat(c1.body()).isEqualTo(c2.body());var copia=JSON.readTree(c1.body());assertThat(copia.get("copia").get("barridoInicial").toString()).contains("SIN_IMPRESORA_OPERATIVA");assertThat(contar("origen_configuracion")).isEqualTo(1);status(post(admin,"/api/admin/configuracion/historial/"+copia.get("codigoPublico").asString()+"/base",Map.of("operacion",UUID.randomUUID())),409);status(post(cliente(),"/api/admin/configuracion/historial/"+origen+"/base",in),401);
        for(String rol:List.of("CLIENTE","EMPLEADO","ADMIN_ADMIN")){String correo=rol.toLowerCase()+"-base@example.test";jdbc.update("INSERT INTO lamontana.usuario(codigo_publico,id_rol,correo,hash_contrasena,nombre,apellido,estado) SELECT ?,r.id_rol,?,u.hash_contrasena,'Interno','Test','ACTIVO' FROM lamontana.usuario u CROSS JOIN lamontana.rol r WHERE u.correo=? AND r.codigo=?",UUID.randomUUID(),correo,EMAIL,rol);var actor=cliente();login(actor,correo);status(post(actor,"/api/admin/configuracion/historial/"+origen+"/base",in),403);}
        var sin=HttpRequest.newBuilder(uri("/api/admin/configuracion/historial/"+origen+"/base")).header("Content-Type","application/json").POST(HttpRequest.BodyPublishers.ofString(JSON.writeValueAsString(in))).build();status(admin.send(sin,HttpResponse.BodyHandlers.ofString()),403);
    }
    @Test void baseProgramadaConservaConfirmacionYHistoricaPuedeOriginarOtraCopia()throws Exception{
        preparar();var original=activar();String origen=id;adoptarCopia(copiarBase(origen,UUID.randomUUID()));
        for(int fase=2;fase<=5;fase++)guardarFaseCopia(fase);cooldown();
        status(post(admin,rutaProgramar()+"/solicitar",solicitudProgramacion()),409);
        confirmarCopia(confirmarCopiaSolicitud());programar();String programada=id;
        assertThat(historial("/"+origen).get("base").get("permitida").asBoolean()).isFalse();
        status(post(admin,"/api/admin/configuracion/historial/"+origen+"/base",Map.of("operacion",UUID.randomUUID())),409);
        status(post(admin,"/api/admin/configuracion/historial/"+programada+"/base",Map.of("operacion",UUID.randomUUID())),409);
        app.close();arrancar();vencerProgramacion();ejecutar(true);
        var vigente=estado().get("activa");assertThat(vigente.get("configuracion").get("codigoPublico").asString()).isEqualTo(programada);
        assertThat(vigente.get("configuracion").get("copia").get("fasesConfirmadas").toString()).isEqualTo("[2,3,4,5,6]");
        assertThat(vigente.get("predecesora").asString()).isEqualTo(origen);assertThat(historial("/"+origen).get("version").get("estado").asString()).isEqualTo("HISTORICA");
        assertThat(historial("/"+origen).get("base").get("permitida").asBoolean()).isTrue();
        var copia=copiarBase(origen,UUID.randomUUID());assertThat(copia.get("numero").asLong()).isEqualTo(3);assertThat(copia.get("copia").get("origen").asString()).isEqualTo(origen);
        for(String field:List.of("modelo","criterio","pagos","recursos","entrega"))assertThat(copia.get(field)).isEqualTo(original.get("configuracion").get(field));
        assertThat(copia.get("copia").get("fasesConfirmadas").size()).isZero();assertThat(estado().get("activa")).isEqualTo(vigente);
    }
    private JsonNode revisionRollback()throws Exception{var r=get(admin,"/api/admin/configuracion/rollback/revision");status(r,200);return JSON.readTree(r.body());}
    private void segundaActivaRollback()throws Exception{var n=post(admin,"/api/admin/configuracion/borradores",Map.of("operacion",UUID.randomUUID()));status(n,200);adoptarCopia(JSON.readTree(n.body()));configurarSegundo();cooldown();activar();cooldown();}
    private JsonNode dosActivasRollback()throws Exception{preparar();var original=activar();segundaActivaRollback();return original;}
    private Map<String,Object> solicitudRollback()throws Exception{
        var r=revisionRollback();var d=new HashMap<String,Object>();d.put("activa",r.get("activa").get("configuracion").get("codigoPublico"));d.put("objetivo",r.get("objetivo").get("configuracion").get("codigoPublico"));d.put("versionObjetivo",r.get("objetivo").get("configuracion").get("version"));d.put("programada",r.get("programada").isNull()?null:r.get("programada").get("configuracion").get("codigoPublico"));d.put("revisionComercial",r.get("condiciones").get("catalogo").get("actual").get("codigoPublico"));d.put("huellaRevision",r.get("huella"));d.put("advertenciasRevisadas",true);d.put("cancelarProgramacion",!r.get("programada").isNull());d.put("motivo","Recuperar condiciones anteriores verificadas");return new HashMap<>(Map.of("operacion",UUID.randomUUID(),"decision",d,"contrasena",CLAVE));
    }
    private Map<String,Object> autorizarRollback()throws Exception{cooldown();var c=solicitudRollback();status(post(admin,"/api/admin/configuracion/rollback/solicitar",c),200);c.put("codigo",smtp.recibir().token());return c;}
    private JsonNode confirmarRollback(Map<String,Object> c)throws Exception{var r=post(admin,"/api/admin/configuracion/rollback/confirmar",c);status(r,200);return JSON.readTree(r.body());}
    private JsonNode programadaRollback()throws Exception{var activa=estado().get("activa").get("configuracion");adoptarCopia(copiarBase(activa.get("codigoPublico").asString(),UUID.randomUUID()));for(int f=2;f<=5;f++)guardarFaseCopia(f);confirmarCopia(confirmarCopiaSolicitud());cooldown();programar();cooldown();return estado().get("programada");}
    @Test void rollbackSinPredecesoraBorradorPermisosCsrfYRevocacion()throws Exception{
        assertThat(revisionRollback().get("permitida").asBoolean()).isFalse();preparar();activar();assertThat(revisionRollback().get("objetivo").isNull()).isTrue();segundaActivaRollback();assertThat(revisionRollback().get("permitida").asBoolean()).isTrue();
        var s=solicitudRollback();s.put("contrasena","NoEsLaClave");status(post(admin,"/api/admin/configuracion/rollback/solicitar",s),400);s.put("contrasena",CLAVE);status(post(admin,"/api/admin/configuracion/rollback/solicitar",s),200);var c=confirmacion(s,smtp.recibir().token());var decision=(Map<String,Object>)s.get("decision");var op=Map.of("operacion",s.get("operacion"),"objetivo",decision.get("objetivo"));status(post(admin,"/api/admin/configuracion/rollback/revocar",op),200);status(post(admin,"/api/admin/configuracion/rollback/confirmar",c),409);
        status(get(cliente(),"/api/admin/configuracion/rollback/revision"),401);
        for(String rol:List.of("CLIENTE","EMPLEADO","ADMIN_ADMIN")){String mail=rol.toLowerCase()+"-rollback@example.test";jdbc.update("INSERT INTO lamontana.usuario(codigo_publico,id_rol,correo,hash_contrasena,nombre,apellido,estado) SELECT ?,r.id_rol,?,u.hash_contrasena,'Interno','Prueba','ACTIVO' FROM lamontana.usuario u CROSS JOIN lamontana.rol r WHERE u.correo=? AND r.codigo=?",UUID.randomUUID(),mail,EMAIL,rol);var actor=cliente();login(actor,mail);status(get(actor,"/api/admin/configuracion/rollback/revision"),403);status(post(actor,"/api/admin/configuracion/rollback/solicitar",s),403);status(post(actor,"/api/admin/configuracion/rollback/confirmar",c),403);}
        var sinCsrf=HttpRequest.newBuilder(uri("/api/admin/configuracion/rollback/solicitar")).header("Content-Type","application/json").POST(HttpRequest.BodyPublishers.ofString(JSON.writeValueAsString(s))).build();status(admin.send(sinCsrf,HttpResponse.BodyHandlers.ofString()),403);
        status(post(admin,"/api/admin/configuracion/borradores",Map.of("operacion",UUID.randomUUID())),200);assertThat(revisionRollback().get("permitida").asBoolean()).isFalse();cooldown();status(post(admin,"/api/admin/configuracion/rollback/solicitar",solicitudRollback()),409);assertThat(jdbc.queryForObject("SELECT count(*) FROM lamontana.intento_activacion_configuracion WHERE operacion='ROLLBACK'",Integer.class)).isZero();
    }
    @Test void rollbackNuevaVersionCancelaProgramacionConservaPredecesoraYReplay()throws Exception{
        var original=dosActivasRollback();String primera=original.get("configuracion").get("codigoPublico").asString(),segunda=id;var programada=programadaRollback();publicar(null,"4.00",true,false);var r=revisionRollback();assertThat(r.get("permitida").asBoolean()).isTrue();var s=solicitudRollback();var d=(Map<String,Object>)s.get("decision");d.put("cancelarProgramacion",false);status(post(admin,"/api/admin/configuracion/rollback/solicitar",s),409);
        var c=autorizarRollback();var result=confirmarRollback(c);assertThat(result.get("estado").asString()).isEqualTo("EXITOSO");var nueva=result.get("version");assertThat(nueva.get("configuracion").get("numero").asLong()).isEqualTo(4);assertThat(nueva.get("configuracion").get("copia").get("tipo").asString()).isEqualTo("ROLLBACK");assertThat(nueva.get("configuracion").get("copia").get("origen").asString()).isEqualTo(primera);assertThat(nueva.get("configuracion").get("copia").get("fasesConfirmadas").size()).isZero();assertThat(nueva.get("predecesora").asString()).isEqualTo(segunda);assertThat(nueva.get("revisionComercial").asString()).isEqualTo(comercial);
        for(String key:List.of("modelo","criterio","pagos","recursos","entrega"))assertThat(nueva.get("configuracion").get(key)).as(key).isEqualTo(original.get("configuracion").get(key));assertThat(result.get("programacionCancelada").get("codigoPublico")).isEqualTo(programada.get("configuracion").get("codigoPublico"));assertThat(result.get("programacionCancelada").get("estado").asString()).isEqualTo("CANCELADA");assertThat(result.get("intento").get("configuracion").asString()).isEqualTo(primera);assertThat(result.get("intento").get("resultante")).isEqualTo(nueva.get("configuracion").get("codigoPublico"));assertThat(result.get("intento").get("operacion").asString()).isEqualTo("ROLLBACK");assertThat(confirmarRollback(c)).isEqualTo(result);ejecutar(true);assertThat(contar("activacion_configuracion")).isEqualTo(3);
        assertThat(historial("/"+nueva.get("configuracion").get("codigoPublico").asString()+"/auditoria").toString()).contains("ROLLBACK_EXITOSO","ROLLBACK_PUBLICADO");assertThat(historial("/"+segunda+"/auditoria").toString()).contains("ROLLBACK_EXITOSO");assertThat(revisionRollback().get("objetivo").get("configuracion").get("codigoPublico").asString()).isEqualTo(segunda);
        var segundo=confirmarRollback(autorizarRollback());assertThat(segundo.get("version").get("configuracion").get("numero").asLong()).isEqualTo(5);assertThat(segundo.get("version").get("configuracion").get("copia").get("origen").asString()).isEqualTo(segunda);assertThat(confirmarRollback(c).get("version").get("configuracion").get("codigoPublico")).isEqualTo(nueva.get("configuracion").get("codigoPublico"));assertThat(contar("configuracion_version")).isEqualTo(5);assertThat(jdbc.queryForObject("SELECT count(*) FROM lamontana.configuracion_version WHERE estado='ACTIVA'",Integer.class)).isEqualTo(1);
        app.close();arrancar();assertThat(estado().get("activa")).isEqualTo(segundo.get("version"));assertThat(confirmarRollback(c).get("estado").asString()).isEqualTo("EXITOSO");
    }
    @Test void rollbackFalloDespuesDeCopiarYPublicarRevierteTodoMenosIntento()throws Exception{
        dosActivasRollback();var programada=programadaRollback();var activa=estado().get("activa");int versiones=contar("configuracion_version"),copias=contar("origen_configuracion");var c=autorizarRollback();var real=app.getBean(PublicacionRollback.class);var fallida=org.mockito.Mockito.mock(PublicacionRollback.class);org.mockito.Mockito.doAnswer(call->{real.publicar(call.getArgument(0),call.getArgument(1),call.getArgument(2),call.getArgument(3),call.getArgument(4),call.getArgument(5));throw new IllegalStateException("Detalle interno de prueba");}).when(fallida).publicar(org.mockito.ArgumentMatchers.anyLong(),org.mockito.ArgumentMatchers.anyLong(),org.mockito.ArgumentMatchers.any(),org.mockito.ArgumentMatchers.any(),org.mockito.ArgumentMatchers.any(),org.mockito.ArgumentMatchers.anyString());org.springframework.test.util.ReflectionTestUtils.setField(app.getBean(RollbackConfiguracionService.class),"publicacion",fallida);
        var result=confirmarRollback(c);assertThat(result.get("estado").asString()).isEqualTo("FALLIDO");assertThat(result.toString()).doesNotContain("Detalle interno");assertThat(result.get("programacionCancelada").isNull()).isTrue();assertThat(result.get("version").isNull()).isTrue();assertThat(contar("configuracion_version")).isEqualTo(versiones);assertThat(contar("origen_configuracion")).isEqualTo(copias);assertThat(estado().get("activa")).isEqualTo(activa);assertThat(estado().get("programada")).isEqualTo(programada);assertThat(confirmarRollback(c)).isEqualTo(result);ejecutar(false);assertThat(estado().get("programada")).isEqualTo(programada);
        org.springframework.test.util.ReflectionTestUtils.setField(app.getBean(RollbackConfiguracionService.class),"publicacion",real);assertThat(confirmarRollback(autorizarRollback()).get("estado").asString()).isEqualTo("EXITOSO");
    }
    @Test void rollbackRevalidaCondicionesActualesSinReintentoPropio()throws Exception{
        dosActivasRollback();var activa=estado().get("activa");var c=autorizarRollback();publicar(null,"7.00",false,false);var result=confirmarRollback(c);assertThat(result.get("estado").asString()).isEqualTo("FALLIDO");assertThat(result.get("intento").get("resultado").asString()).isEqualTo("VALIDACION_RECHAZADA");assertThat(estado().get("activa")).isEqualTo(activa);assertThat(estado().get("programada").isNull()).isTrue();int intentos=contar("intento_activacion_configuracion");ejecutar(true);ejecutar(false);assertThat(contar("intento_activacion_configuracion")).isEqualTo(intentos);assertThat(revisionRollback().get("permitida").asBoolean()).isFalse();assertThat(confirmarRollback(c)).isEqualTo(result);
    }
    @Test void rollbackInterrumpidoSeRecuperaSinRepetirCopiaNiCancelar()throws Exception{
        dosActivasRollback();var programada=programadaRollback();var activa=estado().get("activa");var c=autorizarRollback();var fallida=org.mockito.Mockito.mock(PublicacionRollback.class);org.mockito.Mockito.doThrow(new AssertionError("Interrupción después del inicio durable")).when(fallida).publicar(org.mockito.ArgumentMatchers.anyLong(),org.mockito.ArgumentMatchers.anyLong(),org.mockito.ArgumentMatchers.any(),org.mockito.ArgumentMatchers.any(),org.mockito.ArgumentMatchers.any(),org.mockito.ArgumentMatchers.anyString());org.springframework.test.util.ReflectionTestUtils.setField(app.getBean(RollbackConfiguracionService.class),"publicacion",fallida);status(post(admin,"/api/admin/configuracion/rollback/confirmar",c),500);assertThat(jdbc.queryForObject("SELECT estado FROM lamontana.intento_activacion_configuracion WHERE operacion='ROLLBACK'",String.class)).isEqualTo("INICIADO");app.close();arrancar();ejecutar(true);var recuperado=confirmarRollback(c);assertThat(recuperado.get("estado").asString()).isEqualTo("INTERRUMPIDO");assertThat(recuperado.get("version").isNull()).isTrue();assertThat(estado().get("activa")).isEqualTo(activa);assertThat(estado().get("programada")).isEqualTo(programada);assertThat(contar("configuracion_version")).isEqualTo(3);
    }
    @Test void rollbackConcurrenciaConWorkerYConfirmacionesUnicas()throws Exception{
        dosActivasRollback();programadaRollback();vencerProgramacion();var c=autorizarRollback();var real=app.getBean(PublicacionRollback.class);var demorada=org.mockito.Mockito.mock(PublicacionRollback.class);var dentro=new CountDownLatch(1);var continuar=new CountDownLatch(1);
        org.mockito.Mockito.doAnswer(call->{dentro.countDown();assertThat(continuar.await(15,TimeUnit.SECONDS)).isTrue();return real.publicar(call.getArgument(0),call.getArgument(1),call.getArgument(2),call.getArgument(3),call.getArgument(4),call.getArgument(5));}).when(demorada).publicar(org.mockito.ArgumentMatchers.anyLong(),org.mockito.ArgumentMatchers.anyLong(),org.mockito.ArgumentMatchers.any(),org.mockito.ArgumentMatchers.any(),org.mockito.ArgumentMatchers.any(),org.mockito.ArgumentMatchers.anyString());org.springframework.test.util.ReflectionTestUtils.setField(app.getBean(RollbackConfiguracionService.class),"publicacion",demorada);
        var one=admin.sendAsync(request(admin,"POST","/api/admin/configuracion/rollback/confirmar",c),HttpResponse.BodyHandlers.ofString());try{assertThat(dentro.await(15,TimeUnit.SECONDS)).isTrue();var two=admin.sendAsync(request(admin,"POST","/api/admin/configuracion/rollback/confirmar",c),HttpResponse.BodyHandlers.ofString());ejecutar(false);continuar.countDown();var r1=one.get(20,TimeUnit.SECONDS);var r2=two.get(20,TimeUnit.SECONDS);status(r1,200);status(r2,200);assertThat(r2.body()).isEqualTo(r1.body());assertThat(JSON.readTree(r1.body()).get("estado").asString()).isEqualTo("EXITOSO");assertThat(jdbc.queryForObject("SELECT count(*) FROM lamontana.intento_activacion_configuracion WHERE operacion='ROLLBACK'",Integer.class)).isEqualTo(1);}finally{continuar.countDown();org.springframework.test.util.ReflectionTestUtils.setField(app.getBean(RollbackConfiguracionService.class),"publicacion",real);}
        programadaRollback();vencerProgramacion();var otra=autorizarRollback();ejecutar(false);var vigente=estado().get("activa");status(post(admin,"/api/admin/configuracion/rollback/confirmar",otra),409);assertThat(estado().get("activa")).isEqualTo(vigente);assertThat(jdbc.queryForObject("SELECT count(*) FROM lamontana.intento_activacion_configuracion WHERE operacion='ROLLBACK'",Integer.class)).isEqualTo(1);
    }
    private JsonNode historial(String ruta)throws Exception{var r=get(admin,"/api/admin/configuracion/historial"+ruta);status(r,200);return JSON.readTree(r.body());}
    @Test void historialDetalleComparacionAuditoriaCompletaSinMutacionesYReinicio()throws Exception{
        assertThat(historial("").get("versiones").get("total").asLong()).isZero();status(get(admin,"/api/admin/configuracion/historial/"+id),404);
        preparar();activar();String primera=id;var primero=historial("/"+id);assertThat(primero.get("revisionComercial").get("codigo").asString()).isEqualTo(comercial);assertThat(primero.get("version").get("autor").get("capturado").asBoolean()).isTrue();assertThat(primero.get("modulos").size()).isEqualTo(5);
        cooldown();aceptar(post(admin,"/api/admin/configuracion/borradores",Map.of("operacion",UUID.randomUUID())));id=borrador.get("codigoPublico").asString();configurarSegundo();guardar("2","1",List.of("RETIRO_SUCURSAL","ENVIO_DOMICILIO"),List.of(horario(a,semana("09:00","18:00")),horario(b,semana("09:00","18:00"))));activar();
        var lista=historial("");assertThat(lista.get("cantidades").get("HISTORICA").asInt()).isEqualTo(1);assertThat(lista.get("cantidades").get("ACTIVA").asInt()).isEqualTo(1);assertThat(lista.get("versiones").get("elementos").get(0).get("codigo").asString()).isEqualTo(id);
        var anterior=historial("/"+primera);assertThat(anterior.get("version").get("estado").asString()).isEqualTo("HISTORICA");assertThat(anterior.get("reemplazadaPor").get("codigo").asString()).isEqualTo(id);assertThat(historial("/"+id).get("predecesora").get("codigo").asString()).isEqualTo(primera);assertThat(anterior.get("modulos")).isEqualTo(primero.get("modulos"));
        var comp=historial("/"+primera+"/comparacion/"+id);assertThat(comp.get("secciones").get(0).get("modificada").asBoolean()).isFalse();assertThat(comp.get("secciones").get(1).get("modificada").asBoolean()).isFalse();assertThat(comp.get("secciones").get(3).get("modificada").asBoolean()).isTrue();assertThat(historial("/"+primera+"/comparacion/"+primera).get("modificadas").asLong()).isZero();
        jdbc.update("UPDATE lamontana.usuario SET nombre='Nombre nuevo' WHERE correo=?",EMAIL);assertThat(historial("/"+primera).get("version").get("autor").get("nombre").asString()).isEqualTo("Admin Entrega");assertThat(historial("/"+primera).get("activador").get("nombre").asString()).isEqualTo("Admin Entrega");
        jdbc.update("INSERT INTO lamontana.evento_configuracion(id_configuracion_version,id_actor,tipo,version,motivo) SELECT c.id_configuracion_version,c.id_usuario_creador,'AUTORIZACION_RECHAZADA',c.version,'Evento de prueba '||n FROM lamontana.configuracion_version c CROSS JOIN generate_series(1,55) n WHERE c.codigo_publico=?",UUID.fromString(primera));
        jdbc.update("INSERT INTO lamontana.intento_activacion_configuracion(id_intento,id_version_objetivo,origen,estado,fecha_inicio,fecha_fin,codigo_resultado,detalle_sanitizado) SELECT gen_random_uuid(),c.id_configuracion_version,'REINTENTO','FALLIDO',clock_timestamp()-interval '1 minute',clock_timestamp(),'PRUEBA','Intento de prueba '||n FROM lamontana.configuracion_version c CROSS JOIN generate_series(1,55) n WHERE c.codigo_publico=?",UUID.fromString(primera));
        int eventos=contar("evento_configuracion"),intentos=contar("intento_activacion_configuracion");var keys=new HashSet<String>();int fallidos=0;long total=historial("/"+primera+"/auditoria").get("total").asLong();for(int pagina=0;pagina*25<total;pagina++){var pag=historial("/"+primera+"/auditoria?pagina="+pagina);for(var ev:pag.get("elementos")){assertThat(keys.add(ev.get("clave").asString())).isTrue();if(ev.get("tipo").asString().equals("INTENTO_FALLIDO"))fallidos++;}}assertThat(keys.size()).isEqualTo(total);assertThat(fallidos).isEqualTo(55);
        publicar(null,"8",true,true);assertThat(historial("/"+primera).get("modulos")).isEqualTo(primero.get("modulos"));assertThat(historial("/"+primera).get("revisionComercial")).isEqualTo(primero.get("revisionComercial"));assertThat(contar("evento_configuracion")).isEqualTo(eventos);assertThat(contar("intento_activacion_configuracion")).isEqualTo(intentos);
        app.close();arrancar();assertThat(historial("/"+primera).get("modulos")).isEqualTo(primero.get("modulos"));assertThat(historial("/"+primera+"/auditoria").get("total").asLong()).isEqualTo(total);
    }
    @Test void historialProgramaConReferenciaAutorYCancelacionSinFalsaVigencia()throws Exception{
        preparar();programar();var d=historial("/"+id);assertThat(d.get("version").get("estado").asString()).isEqualTo("PROGRAMADA");assertThat(d.get("version").get("activadaEn").isNull()).isTrue();assertThat(d.get("programador").get("rol").asString()).isEqualTo("ADMIN_ADMIN");assertThat(d.get("revisionComercial").get("codigo").asString()).isEqualTo(comercial);
        cooldown();var actual=estado().get("programada").get("configuracion");var s=new HashMap<String,Object>(Map.of("operacion",UUID.randomUUID(),"version",actual.get("version").asLong(),"motivo","Cancelar para revisar","contrasena",CLAVE));status(post(admin,rutaProgramar()+"/cancelacion/solicitar",s),200);s.put("codigo",smtp.recibir().token());status(post(admin,rutaProgramar()+"/cancelacion/confirmar",s),200);var cancel=historial("/"+id);assertThat(cancel.get("version").get("estado").asString()).isEqualTo("CANCELADA");assertThat(cancel.get("version").get("activadaEn").isNull()).isTrue();assertThat(cancel.get("version").get("previstaEn")).isEqualTo(d.get("version").get("previstaEn"));assertThat(cancel.get("motivoProgramacion")).isEqualTo(d.get("motivoProgramacion"));
        jdbc.update("UPDATE lamontana.configuracion_version SET nombre_actor=NULL,rol_actor=NULL WHERE codigo_publico=?",UUID.fromString(id));var vieja=historial("/"+id);assertThat(vieja.get("version").get("autor").get("capturado").asBoolean()).isFalse();assertThat(vieja.get("version").get("autor").get("rol").isNull()).isTrue();
    }
    @Test void historialFiltrosPaginacionPermisosYValidacion()throws Exception{
        jdbc.update("INSERT INTO lamontana.configuracion_version(codigo_publico,numero_version,id_usuario_creador,estado,id_usuario_cancelador,fecha_cancelacion,motivo_cancelacion) SELECT gen_random_uuid(),n,u.id_usuario,'CANCELADA',u.id_usuario,clock_timestamp(),'Cancelación de prueba' FROM lamontana.usuario u CROSS JOIN generate_series(2,57) n WHERE correo=?",EMAIL);
        assertThat(historial("").get("versiones").get("total").asLong()).isEqualTo(56);assertThat(historial("?pagina=2").get("versiones").get("elementos").size()).isEqualTo(6);assertThat(historial("?orden=ANTIGUAS").get("versiones").get("elementos").get(0).get("numero").asLong()).isEqualTo(2);assertThat(historial("?buscar=V57&estado=CANCELADA").get("versiones").get("total").asLong()).isEqualTo(1);assertThat(historial("?estado=ACTIVA").get("versiones").get("total").asLong()).isZero();
        String cerrada=historial("").get("versiones").get("elementos").get(0).get("codigo").asString();for(String q:List.of("?pagina=-1","?pagina=1000001","?estado=EN_PREPARACION","?orden=sql","?buscar=%25"))status(get(admin,"/api/admin/configuracion/historial"+q),400);status(get(admin,"/api/admin/configuracion/historial/"+UUID.randomUUID()),404);status(get(admin,"/api/admin/configuracion/historial/"+cerrada+"/auditoria?pagina=-1"),400);status(get(cliente(),"/api/admin/configuracion/historial"),401);
        for(String rol:List.of("CLIENTE","EMPLEADO","ADMIN_ADMIN")){String correo=rol.toLowerCase()+"-history@example.test";jdbc.update("INSERT INTO lamontana.usuario(codigo_publico,id_rol,correo,hash_contrasena,nombre,apellido,estado) SELECT ?,r.id_rol,?,u.hash_contrasena,'Interno','Test','ACTIVO' FROM lamontana.usuario u CROSS JOIN lamontana.rol r WHERE u.correo=? AND r.codigo=?",UUID.randomUUID(),correo,EMAIL,rol);var actor=cliente();login(actor,correo);for(String path:List.of("","/"+cerrada,"/"+cerrada+"/auditoria","/"+cerrada+"/comparacion/"+cerrada))status(get(actor,"/api/admin/configuracion/historial"+path),rol.equals("ADMIN_ADMIN")?200:403);status(post(actor,"/api/admin/configuracion/historial/"+cerrada,Map.of()),403);}
    }
    @Test void primeraActivacionConcurrenteRecuperacionInmutabilidadYReinicio()throws Exception{
        preparar();assertThat(estado().get("activa").isNull()).isTrue();assertThat(revision().get("huella")).isEqualTo(revision().get("huella"));String snapshot=borrador.toString();var s=solicitud();var token=solicitar(s);status(post(admin,rutaActivar()+"/solicitar",s),200);assertThat(smtp.pendientes()).isZero();assertThat(estado().get("activa").isNull()).isTrue();
        var c=confirmacion(s,token);var req1=request(admin,"POST",rutaActivar()+"/confirmar",c);var req2=request(admin,"POST",rutaActivar()+"/confirmar",c);var f1=admin.sendAsync(req1,HttpResponse.BodyHandlers.ofString());var f2=admin.sendAsync(req2,HttpResponse.BodyHandlers.ofString());var r1=f1.get();var r2=f2.get();status(r1,200);status(r2,200);assertThat(r1.body()).isEqualTo(r2.body());var activada=JSON.readTree(r1.body()).get("version");assertThat(JSON.readTree(r1.body()).get("intento").get("origen").asString()).isEqualTo("MANUAL");assertThat(contar("intento_activacion_configuracion")).isEqualTo(1);
        assertThat(activada.get("configuracion").get("estado").asString()).isEqualTo("ACTIVA");assertThat(activada.get("predecesora").isNull()).isTrue();assertThat(activada.get("revisionComercial").asString()).isEqualTo(comercial);assertThat(estado().get("borrador").isNull()).isTrue();assertThat(estado().get("activa")).isEqualTo(activada);assertThat(contar("activacion_configuracion")).isEqualTo(1);
        for(String field:List.of("modelo","criterio","pagos","recursos","entrega"))assertThat(activada.get("configuracion").get(field)).isEqualTo(JSON.readTree(snapshot).get(field));
        var edit=comando();edit.put("modelo","MANUAL");status(put(admin,base()+"/modelo",edit),409);status(put(admin,ruta(),entrega("2","0",List.of("RETIRO_SUCURSAL"),List.of())),409);
        assertThat(JSON.readTree(get(admin,"/api/admin/puntos-entrega/disponibilidad").body()).get("contexto").asString()).isEqualTo("CONFIGURACION_ACTIVA");
        app.close();arrancar();status(post(admin,rutaActivar()+"/confirmar",c),200);assertThat(estado().get("activa")).isEqualTo(activada);assertThat(contar("activacion_configuracion")).isEqualTo(1);
        c.put("codigo","incorrecto");status(post(admin,rutaActivar()+"/confirmar",c),400);
    }
    @Test void reemplazoAtomicoFalloDurableConservaActivaBorradorYResultado()throws Exception{
        preparar();var original=activar();String primera=id;cooldown();var nuevo=post(admin,"/api/admin/configuracion/borradores",Map.of("operacion",UUID.randomUUID().toString()));status(nuevo,200);borrador=JSON.readTree(nuevo.body());id=borrador.get("codigoPublico").asString();configurarSegundo();
        var s=solicitud();var c=confirmacion(s,solicitar(s));var input=JSON.readValue(JSON.writeValueAsString(c),ActivacionConfiguracionController.Confirmar.class);var antes=estado();
        jdbc.execute("CREATE FUNCTION lamontana.fallar_activacion_test() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'fallo de prueba'; END $$");jdbc.execute("CREATE TRIGGER fallo_activacion BEFORE INSERT ON lamontana.activacion_configuracion FOR EACH ROW EXECUTE FUNCTION lamontana.fallar_activacion_test()");
        var fallido=app.getBean(ActivacionConfiguracionService.class).confirmar(UUID.fromString(id),input,EMAIL);assertThat(fallido.estado()).isEqualTo("FALLIDO");assertThat(fallido.version()).isNull();assertThat(fallido.intento().resultado()).isEqualTo("ERROR_PUBLICACION");assertThat(estado().get("activa")).isEqualTo(antes.get("activa"));assertThat(estado().get("borrador")).isEqualTo(antes.get("borrador"));assertThat(jdbc.queryForObject("SELECT fecha_consumo IS NOT NULL FROM lamontana.autorizacion_configuracion WHERE id_operacion=?",Boolean.class,UUID.fromString((String)s.get("operacion")))).isTrue();jdbc.execute("DROP TRIGGER fallo_activacion ON lamontana.activacion_configuracion");
        assertThat(app.getBean(ActivacionConfiguracionService.class).confirmar(UUID.fromString(id),input,EMAIL)).isEqualTo(fallido);ejecutar(false);assertThat(contar("activacion_configuracion")).isEqualTo(1);assertThat(contar("programacion_configuracion")).isZero();cooldown();s=solicitud();c=confirmacion(s,solicitar(s));
        var r=post(admin,rutaActivar()+"/confirmar",c);status(r,200);var activa=JSON.readTree(r.body()).get("version");assertThat(activa.get("predecesora").asString()).isEqualTo(primera);assertThat(contar("activacion_configuracion")).isEqualTo(2);assertThat(jdbc.queryForObject("SELECT count(*) FROM lamontana.configuracion_version WHERE estado='ACTIVA'",Integer.class)).isEqualTo(1);assertThat(jdbc.queryForObject("SELECT estado FROM lamontana.configuracion_version WHERE codigo_publico=?",String.class,UUID.fromString(primera))).isEqualTo("HISTORICA");assertThat(jdbc.queryForObject("SELECT fin_vigencia= (SELECT fecha_activacion FROM lamontana.activacion_configuracion ORDER BY fecha_activacion DESC LIMIT 1) FROM lamontana.activacion_configuracion WHERE id_predecesora IS NULL",Boolean.class)).isTrue();
    }
    @Test void cambioComercialAdvertenciasRevocacionEdicionEIntentos()throws Exception{
        preparar();var falta=solicitud();var d=new HashMap<>((Map<String,Object>)falta.get("decision"));d.put("advertenciasRevisadas",false);falta.put("decision",d);status(post(admin,rutaActivar()+"/solicitar",falta),409);assertThat(contar("autorizacion_configuracion")).isZero();
        var s=solicitud();var token=solicitar(s);var c=confirmacion(s,token);for(int n=1;n<=5;n++){var malo=confirmacion(s,"invalido");status(post(admin,rutaActivar()+"/confirmar",malo),400);}status(post(admin,rutaActivar()+"/confirmar",c),400);assertThat(jdbc.queryForObject("SELECT intentos FROM lamontana.autorizacion_configuracion",Integer.class)).isEqualTo(5);assertThat(estado().get("activa").isNull()).isTrue();
        cooldown();s=solicitud();token=solicitar(s);c=confirmacion(s,token);status(post(admin,rutaActivar()+"/revocar",Map.of("operacion",s.get("operacion"))),200);status(post(admin,rutaActivar()+"/confirmar",c),409);
        cooldown();s=solicitud();token=solicitar(s);c=confirmacion(s,token);publicar(null,"3",true,false);var rechazado=post(admin,rutaActivar()+"/confirmar",c);status(rechazado,200);assertThat(JSON.readTree(rechazado.body()).get("estado").asString()).isEqualTo("FALLIDO");assertThat(contar("activacion_configuracion")).isZero();assertThat(estado().get("borrador").get("version")).isEqualTo(borrador.get("version"));
        cooldown();s=solicitud();token=solicitar(s);c=confirmacion(s,token);guardar("2","1",List.of("RETIRO_SUCURSAL"),List.of(horario(a,semana("09:00","18:00")),horario(b,semana("09:00","18:00"))));status(post(admin,rutaActivar()+"/confirmar",c),409);
    }
    @Test void smtpFallidoCodigoVencidoPermisosYCsrf()throws Exception{
        preparar();var s=solicitud();smtp.rechazar=true;var input=JSON.readValue(JSON.writeValueAsString(s),ActivacionConfiguracionController.Solicitar.class);assertThatThrownBy(()->app.getBean(ActivacionConfiguracionService.class).solicitar(UUID.fromString(id),input,EMAIL)).isInstanceOf(ar.com.lamontana.identidad.CorreoService.CorreoNoDisponible.class);assertThat(contar("autorizacion_configuracion")).isZero();smtp.rechazar=false;
        var token=solicitar(s);var c=confirmacion(s,token);status(post(admin,base()+"/cancelacion/confirmar",Map.of("operacion",s.get("operacion"),"version",borrador.get("version").asLong(),"motivo","Otro propósito","contrasena",CLAVE,"codigo",token)),409);assertThat(estado().get("borrador").get("estado").asString()).isEqualTo("EN_PREPARACION");jdbc.update("UPDATE lamontana.autorizacion_configuracion SET fecha_emision=clock_timestamp()-interval '20 minutes',fecha_vencimiento=clock_timestamp()-interval '1 minute'");status(post(admin,rutaActivar()+"/confirmar",c),400);
        var sin=HttpRequest.newBuilder(uri(rutaActivar()+"/confirmar")).header("Content-Type","application/json").POST(HttpRequest.BodyPublishers.ofString(JSON.writeValueAsString(c))).build();status(admin.send(sin,HttpResponse.BodyHandlers.ofString()),403);
        var anon=cliente();status(post(anon,rutaActivar()+"/solicitar",s),401);for(String rol:List.of("CLIENTE","EMPLEADO","ADMIN_ADMIN")){String correo=rol.toLowerCase()+"-activation@example.test";jdbc.update("INSERT INTO lamontana.usuario(codigo_publico,id_rol,correo,hash_contrasena,nombre,apellido,estado) SELECT ?,r.id_rol,?,u.hash_contrasena,'Interno','Test','ACTIVO' FROM lamontana.usuario u CROSS JOIN lamontana.rol r WHERE u.correo=? AND r.codigo=?",UUID.randomUUID(),correo,EMAIL,rol);var actor=cliente();login(actor,correo);for(String accion:List.of("solicitar","confirmar"))status(post(actor,rutaActivar()+"/"+accion,accion.equals("solicitar")?s:c),403);status(post(actor,rutaActivar()+"/revocar",Map.of("operacion",s.get("operacion"))),403);}
    }
    @Test void programacionExigePropietarioCsrfYCredenciales()throws Exception{
        preparar();var s=solicitudProgramacion();var incorrecta=new HashMap<>(s);incorrecta.put("contrasena","Incorrecta123!");status(post(admin,rutaProgramar()+"/solicitar",incorrecta),400);assertThat(contar("autorizacion_configuracion")).isZero();
        var sin=HttpRequest.newBuilder(uri(rutaProgramar()+"/solicitar")).header("Content-Type","application/json").POST(HttpRequest.BodyPublishers.ofString(JSON.writeValueAsString(s))).build();status(admin.send(sin,HttpResponse.BodyHandlers.ofString()),403);status(post(cliente(),rutaProgramar()+"/solicitar",s),401);
        for(String rol:List.of("CLIENTE","EMPLEADO","ADMIN_ADMIN")){String correo=rol.toLowerCase()+"-program@example.test";jdbc.update("INSERT INTO lamontana.usuario(codigo_publico,id_rol,correo,hash_contrasena,nombre,apellido,estado) SELECT ?,r.id_rol,?,u.hash_contrasena,'Interno','Test','ACTIVO' FROM lamontana.usuario u CROSS JOIN lamontana.rol r WHERE u.correo=? AND r.codigo=?",UUID.randomUUID(),correo,EMAIL,rol);var actor=cliente();login(actor,correo);status(post(actor,rutaProgramar()+"/solicitar",s),403);status(post(actor,rutaProgramar()+"/revocar",Map.of("operacion",s.get("operacion"))),403);status(get(actor,rutaProgramar()+"/revision"),403);status(post(actor,rutaProgramar()+"/activacion/solicitar",solicitud()),403);status(post(actor,rutaProgramar()+"/cancelacion/solicitar",Map.of("operacion",UUID.randomUUID(),"version",borrador.get("version").asLong(),"motivo","Sin permiso","contrasena",CLAVE)),403);}
    }
    private String rutaProgramar(){return base()+"/programacion";}
    private Map<String,Object> solicitudProgramacion()throws Exception{
        return new HashMap<>(Map.of("operacion",UUID.randomUUID().toString(),"contrasena",CLAVE,"decision",Map.of("revision",decision(),"fechaLocal",java.time.LocalDateTime.now(java.time.ZoneId.of("America/Argentina/Buenos_Aires")).plusDays(1).withNano(0).toString(),"zonaHoraria","America/Argentina/Buenos_Aires")));
    }
    private Map<String,Object> programar()throws Exception{
        var s=solicitudProgramacion();status(post(admin,rutaProgramar()+"/solicitar",s),200);var c=confirmacion(s,smtp.recibir().token());var r=post(admin,rutaProgramar()+"/confirmar",c);status(r,200);return c;
    }
    private int intentosObjetivo(){return jdbc.queryForObject("SELECT count(*) FROM lamontana.intento_activacion_configuracion WHERE id_version_objetivo=(SELECT id_configuracion_version FROM lamontana.configuracion_version WHERE codigo_publico=?)",Integer.class,UUID.fromString(id));}
    private void vencerProgramacion(){jdbc.update("UPDATE lamontana.programacion_configuracion SET fecha_confirmacion=clock_timestamp()-interval '2 days',fecha_programada=clock_timestamp()-interval '1 day'");}
    private void ejecutar(boolean recuperacion){app.getBean(EjecucionProgramadaService.class).reconciliar(recuperacion);}
    private void vencerReintento(){jdbc.update("UPDATE lamontana.programacion_configuracion SET fecha_confirmacion=least(fecha_confirmacion,clock_timestamp()-interval '1 day')");jdbc.update("UPDATE lamontana.intento_activacion_configuracion SET fecha_inicio=clock_timestamp()-interval '12 minutes',fecha_fin=clock_timestamp()-interval '11 minutes',fecha_atraso_detectado=CASE WHEN origen='RECUPERACION' THEN clock_timestamp()-interval '12 minutes' ELSE NULL END WHERE estado='FALLIDO'");}
    @Test void programacionSeguraInmutableCancelacionYReinicio()throws Exception{
        preparar();var s=solicitudProgramacion();var d=new HashMap<>((Map<String,Object>)s.get("decision"));d.put("zonaHoraria","UTC-03:00");s.put("decision",d);status(post(admin,rutaProgramar()+"/solicitar",s),409);
        d.put("zonaHoraria","America/New_York");d.put("fechaLocal","2030-11-03T01:30:00");status(post(admin,rutaProgramar()+"/solicitar",s),409);
        d.put("fechaLocal","2030-03-10T02:30:00");status(post(admin,rutaProgramar()+"/solicitar",s),409);d.put("fechaLocal","2020-01-01T12:00:00");status(post(admin,rutaProgramar()+"/solicitar",s),409);assertThat(contar("autorizacion_configuracion")).isZero();
        s=solicitudProgramacion();status(post(admin,rutaProgramar()+"/solicitar",s),200);String token=smtp.recibir().token();var c=confirmacion(s,token);var cambiado=new HashMap<>((Map<String,Object>)s.get("decision"));cambiado.put("fechaLocal","2031-01-01T10:00:00");var distinto=new HashMap<>(c);distinto.put("decision",cambiado);status(post(admin,rutaProgramar()+"/confirmar",distinto),409);
        status(post(admin,rutaActivar()+"/confirmar",Map.of("operacion",s.get("operacion"),"decision",decision(),"contrasena",CLAVE,"codigo",token)),409);
        var req1=request(admin,"POST",rutaProgramar()+"/confirmar",c);var req2=request(admin,"POST",rutaProgramar()+"/confirmar",c);var f1=admin.sendAsync(req1,HttpResponse.BodyHandlers.ofString());var f2=admin.sendAsync(req2,HttpResponse.BodyHandlers.ofString());var r1=f1.get();var r2=f2.get();status(r1,200);status(r2,200);assertThat(r1.body()).isEqualTo(r2.body());var programada=JSON.readTree(r1.body());assertThat(estado().get("programada")).isEqualTo(programada);assertThat(estado().get("borrador").isNull()).isTrue();assertThat(estado().get("activa").isNull()).isTrue();
        ejecutar(false);assertThat(contar("intento_activacion_configuracion")).isZero();status(post(admin,"/api/admin/configuracion/borradores",Map.of("operacion",UUID.randomUUID())),409);var cambio=comando();cambio.put("modelo","MANUAL");status(put(admin,base()+"/modelo",cambio),409);
        assertThatThrownBy(()->jdbc.update("INSERT INTO lamontana.configuracion_version(codigo_publico,numero_version,id_usuario_creador,estado) SELECT ?,100,id_usuario,'EN_PREPARACION' FROM lamontana.usuario WHERE correo=?",UUID.randomUUID(),EMAIL)).isInstanceOf(DataAccessException.class);
        app.close();arrancar();assertThat(estado().get("programada")).isEqualTo(programada);cooldown();var cancelar=new HashMap<String,Object>(Map.of("operacion",UUID.randomUUID(),"version",programada.get("configuracion").get("version").asLong(),"motivo","Cambio de fecha requerido","contrasena",CLAVE));status(post(admin,rutaProgramar()+"/cancelacion/solicitar",cancelar),200);cancelar.put("codigo",smtp.recibir().token());status(post(admin,rutaProgramar()+"/cancelacion/revocar",Map.of("operacion",cancelar.get("operacion"))),200);status(post(admin,rutaProgramar()+"/cancelacion/confirmar",cancelar),409);cooldown();cancelar.put("operacion",UUID.randomUUID());cancelar.remove("codigo");status(post(admin,rutaProgramar()+"/cancelacion/solicitar",cancelar),200);cancelar.put("codigo",smtp.recibir().token());status(post(admin,rutaProgramar()+"/cancelacion/confirmar",cancelar),200);status(post(admin,rutaProgramar()+"/cancelacion/confirmar",cancelar),200);assertThat(estado().get("programada").isNull()).isTrue();assertThat(contar("programacion_configuracion")).isEqualTo(1);vencerProgramacion();ejecutar(true);assertThat(contar("intento_activacion_configuracion")).isZero();status(post(admin,rutaProgramar()+"/confirmar",c),200);assertThat(estado().get("programada").isNull()).isTrue();status(post(admin,"/api/admin/configuracion/borradores",Map.of("operacion",UUID.randomUUID())),200);
    }
    @Test void programacionAutomaticaAtomicaFallosDiezMinutosYConcurrencia()throws Exception{
        preparar();String original=id;var previa=activar();cooldown();var nuevo=post(admin,"/api/admin/configuracion/borradores",Map.of("operacion",UUID.randomUUID()));status(nuevo,200);borrador=JSON.readTree(nuevo.body());id=borrador.get("codigoPublico").asString();configurarSegundo();var c=programar();vencerProgramacion();
        jdbc.execute("CREATE FUNCTION lamontana.fallar_programacion_test() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'secreto-no-debe-registrarse'; END $$");jdbc.execute("CREATE TRIGGER fallo_programacion BEFORE INSERT ON lamontana.activacion_configuracion FOR EACH ROW EXECUTE FUNCTION lamontana.fallar_programacion_test()");
        var engine=app.getBean(EjecucionProgramadaService.class);var pool=Executors.newFixedThreadPool(4);try{var tareas=new ArrayList<Future<?>>();for(int n=0;n<4;n++)tareas.add(pool.submit(()->engine.reconciliar(false)));for(var tarea:tareas)tarea.get(20,TimeUnit.SECONDS);}finally{pool.shutdownNow();}
        assertThat(intentosObjetivo()).isEqualTo(1);assertThat(estado().get("activa")).isEqualTo(previa);var programada=estado().get("programada");assertThat(programada.toString()).doesNotContain("secreto-no-debe-registrarse");assertThat(programada.get("intentos").get(0).get("resultado").asString()).isEqualTo("ERROR_PUBLICACION");assertThat(Duration.between(Instant.parse(programada.get("intentos").get(0).get("terminadoEn").asString()),Instant.parse(programada.get("proximoIntentoEn").asString()))).isEqualTo(Duration.ofMinutes(10));
        ejecutar(false);ejecutar(true);assertThat(intentosObjetivo()).isEqualTo(1);vencerReintento();ejecutar(false);assertThat(intentosObjetivo()).isEqualTo(2);assertThat(estado().get("activa")).isEqualTo(previa);
        jdbc.execute("DROP TRIGGER fallo_programacion ON lamontana.activacion_configuracion");vencerReintento();app.close();arrancar(true);assertThat(estado().get("programada").isNull()).isTrue();var actual=estado().get("activa");assertThat(actual.get("predecesora").asString()).isEqualTo(original);assertThat(actual.get("activador").asString()).isEqualTo("Sistema automático");assertThat(contar("activacion_configuracion")).isEqualTo(2);assertThat(intentosObjetivo()).isEqualTo(3);assertThat(jdbc.queryForObject("SELECT origen FROM lamontana.intento_activacion_configuracion WHERE estado='EXITOSO' AND id_version_objetivo=(SELECT id_configuracion_version FROM lamontana.configuracion_version WHERE codigo_publico=?)",String.class,UUID.fromString(id))).isEqualTo("RECUPERACION");ejecutar(false);assertThat(intentosObjetivo()).isEqualTo(3);status(post(admin,rutaProgramar()+"/confirmar",c),200);assertThat(estado().get("programada").isNull()).isTrue();
    }
    @Test void primeraProgramacionRevalidaCondicionesActualesYSinRespaldo()throws Exception{
        preparar();programar();vencerProgramacion();jdbc.update("UPDATE lamontana.sucursal SET estado='DESACTIVADA'");ejecutar(false);assertThat(estado().get("activa").isNull()).isTrue();assertThat(estado().get("programada").get("intentos").get(0).get("resultado").asString()).isEqualTo("CONDICIONES_NO_VALIDAS");jdbc.update("UPDATE lamontana.sucursal SET estado='ACTIVA'");vencerReintento();ejecutar(false);assertThat(estado().get("activa").get("predecesora").isNull()).isTrue();assertThat(jdbc.queryForObject("SELECT id_actor IS NULL FROM lamontana.activacion_configuracion",Boolean.class)).isTrue();assertThat(contar("intento_activacion_configuracion")).isEqualTo(2);
    }
    @Test void recuperaInicioDurableSinPublicacionYNoDuplicaExito()throws Exception{
        preparar();programar();vencerProgramacion();jdbc.update("INSERT INTO lamontana.intento_activacion_configuracion(id_intento,id_version_objetivo,origen,estado,fecha_inicio) SELECT ?,id_configuracion_version,'PROGRAMACION','INICIADO',clock_timestamp()-interval '2 hours' FROM lamontana.configuracion_version WHERE codigo_publico=?",UUID.randomUUID(),UUID.fromString(id));
        assertThatThrownBy(()->jdbc.update("INSERT INTO lamontana.intento_activacion_configuracion(id_intento,id_version_objetivo,origen,estado,fecha_inicio) SELECT ?,id_configuracion_version,'PROGRAMACION','INICIADO',clock_timestamp() FROM lamontana.configuracion_version WHERE codigo_publico=?",UUID.randomUUID(),UUID.fromString(id))).isInstanceOf(DataAccessException.class);
        app.close();arrancar(true);assertThat(jdbc.queryForObject("SELECT count(*) FROM lamontana.intento_activacion_configuracion WHERE estado='INTERRUMPIDO'",Integer.class)).isEqualTo(1);assertThat(jdbc.queryForObject("SELECT count(*) FROM lamontana.intento_activacion_configuracion WHERE estado='EXITOSO' AND origen='RECUPERACION' AND fecha_atraso_detectado>= (SELECT fecha_programada FROM lamontana.programacion_configuracion)",Integer.class)).isEqualTo(1);assertThat(contar("activacion_configuracion")).isEqualTo(1);app.close();arrancar(true);assertThat(contar("intento_activacion_configuracion")).isEqualTo(2);assertThat(contar("activacion_configuracion")).isEqualTo(1);
    }
    @Test void programacionNoReutilizaAutorizacionDeAccesoRevocada()throws Exception{
        preparar();programar();vencerProgramacion();jdbc.update("UPDATE lamontana.usuario SET version_acceso=version_acceso+1 WHERE correo=?",EMAIL);ejecutar(false);assertThat(contar("activacion_configuracion")).isZero();assertThat(jdbc.queryForObject("SELECT codigo_resultado FROM lamontana.intento_activacion_configuracion",String.class)).isEqualTo("AUTORIZACION_NO_VIGENTE");
    }
    private Map<String,Object> solicitudAdelanto()throws Exception{
        var respuesta=get(admin,rutaProgramar()+"/revision");status(respuesta,200);var r=JSON.readTree(respuesta.body());
        return new HashMap<>(Map.of("operacion",UUID.randomUUID().toString(),"contrasena",CLAVE,"decision",Map.of("version",r.get("borrador").get("version").asLong(),"revisionComercial",r.get("catalogo").get("actual").get("codigoPublico").asString(),"huellaRevision",r.get("huella").asString(),"advertenciasRevisadas",true,"motivo","Activar ahora la programación revisada")));
    }
    private Map<String,Object> autorizarAdelanto()throws Exception{cooldown();var s=solicitudAdelanto();status(post(admin,rutaProgramar()+"/activacion/solicitar",s),200);return confirmacion(s,smtp.recibir().token());}
    @Test void adelantoManualAntesDeFechaConcurrenteConservaProgramacionYActor()throws Exception{
        preparar();programar();var prevista=estado().get("programada").get("previstaEn").asString();var c=autorizarAdelanto();status(post(admin,rutaActivar()+"/confirmar",c),409);
        var req1=request(admin,"POST",rutaProgramar()+"/activacion/confirmar",c);var req2=request(admin,"POST",rutaProgramar()+"/activacion/confirmar",c);var f1=admin.sendAsync(req1,HttpResponse.BodyHandlers.ofString());var f2=admin.sendAsync(req2,HttpResponse.BodyHandlers.ofString());var r1=f1.get();var r2=f2.get();status(r1,200);status(r2,200);assertThat(r1.body()).isEqualTo(r2.body());var resultado=JSON.readTree(r1.body());assertThat(resultado.get("estado").asString()).isEqualTo("EXITOSO");assertThat(resultado.get("intento").get("origen").asString()).isEqualTo("MANUAL");assertThat(Instant.parse(resultado.get("version").get("activadaEn").asString())).isBefore(Instant.parse(prevista));assertThat(resultado.get("version").get("activador").asString()).isEqualTo("Admin Entrega");assertThat(contar("programacion_configuracion")).isEqualTo(1);assertThat(contar("intento_activacion_configuracion")).isEqualTo(1);assertThat(estado().get("programada").isNull()).isTrue();ejecutar(true);assertThat(contar("activacion_configuracion")).isEqualTo(1);app.close();arrancar(true);status(post(admin,rutaProgramar()+"/activacion/confirmar",c),200);assertThat(contar("intento_activacion_configuracion")).isEqualTo(1);
    }
    @Test void falloManualProgramadoConservaResultadoYReintentaADiezMinutos()throws Exception{
        preparar();programar();vencerProgramacion();var c=autorizarAdelanto();publicar(null,"4",true,false);var r=post(admin,rutaProgramar()+"/activacion/confirmar",c);status(r,200);var resultado=JSON.readTree(r.body());assertThat(resultado.get("estado").asString()).isEqualTo("FALLIDO");assertThat(resultado.get("intento").get("origen").asString()).isEqualTo("MANUAL");assertThat(resultado.get("intento").get("resultado").asString()).isEqualTo("VALIDACION_RECHAZADA");assertThat(estado().get("activa").isNull()).isTrue();var programada=estado().get("programada");assertThat(Duration.between(Instant.parse(resultado.get("intento").get("terminadoEn").asString()),Instant.parse(programada.get("proximoIntentoEn").asString()))).isEqualTo(Duration.ofMinutes(10));assertThat(post(admin,rutaProgramar()+"/activacion/confirmar",c).body()).isEqualTo(r.body());ejecutar(false);ejecutar(true);assertThat(contar("intento_activacion_configuracion")).isEqualTo(1);vencerReintento();ejecutar(false);assertThat(contar("intento_activacion_configuracion")).isEqualTo(2);assertThat(estado().get("activa").isNull()).isFalse();assertThat(jdbc.queryForObject("SELECT id_usuario_actor IS NULL FROM lamontana.intento_activacion_configuracion WHERE estado='EXITOSO'",Boolean.class)).isTrue();
    }
    @Test void interrupcionDespuesDeInicioEsDurableBloqueaEdicionYSeRecuperaSinReejecutar()throws Exception{
        preparar();var s=solicitud();var c=confirmacion(s,solicitar(s));var input=JSON.readValue(JSON.writeValueAsString(c),ActivacionConfiguracionController.Confirmar.class);
        var interrumpida=org.mockito.Mockito.mock(PublicacionConfiguracion.class);org.mockito.Mockito.doThrow(new AssertionError("Caída simulada después del inicio durable")).when(interrumpida).publicar(org.mockito.ArgumentMatchers.anyLong(),org.mockito.ArgumentMatchers.any(),org.mockito.ArgumentMatchers.any(),org.mockito.ArgumentMatchers.any(),org.mockito.ArgumentMatchers.any());
        org.springframework.test.util.ReflectionTestUtils.setField(app.getBean(ActivacionConfiguracionService.class),"publicacion",interrumpida);
        assertThatThrownBy(()->app.getBean(ActivacionConfiguracionService.class).confirmar(UUID.fromString(id),input,EMAIL)).isInstanceOf(AssertionError.class);assertThat(contar("activacion_configuracion")).isZero();assertThat(jdbc.queryForObject("SELECT estado FROM lamontana.intento_activacion_configuracion",String.class)).isEqualTo("INICIADO");
        var cambio=comando();cambio.put("modelo","MANUAL");status(put(admin,base()+"/modelo",cambio),409);status(post(admin,base()+"/cancelacion/solicitar",Map.of("operacion",UUID.randomUUID(),"version",borrador.get("version").asLong(),"contrasena",CLAVE,"motivo","Esperar recuperación")),409);status(post(admin,rutaProgramar()+"/solicitar",solicitudProgramacion()),409);
        app.close();arrancar(true);var r=post(admin,rutaActivar()+"/confirmar",c);status(r,200);assertThat(JSON.readTree(r.body()).get("estado").asString()).isEqualTo("INTERRUMPIDO");assertThat(contar("intento_activacion_configuracion")).isEqualTo(1);assertThat(contar("activacion_configuracion")).isZero();assertThat(estado().get("borrador").get("version")).isEqualTo(borrador.get("version"));cooldown();activar();assertThat(contar("activacion_configuracion")).isEqualTo(1);assertThat(contar("intento_activacion_configuracion")).isEqualTo(2);
    }
    @Test void reintentoDeAdelantoPuedeVencerAntesDeLaFechaOriginal()throws Exception{
        preparar();programar();var prevista=Instant.parse(estado().get("programada").get("previstaEn").asString());var c=autorizarAdelanto();publicar(null,"4",true,false);var r=post(admin,rutaProgramar()+"/activacion/confirmar",c);status(r,200);assertThat(JSON.readTree(r.body()).get("estado").asString()).isEqualTo("FALLIDO");vencerReintento();ejecutar(true);assertThat(Instant.parse(estado().get("activa").get("activadaEn").asString())).isBefore(prevista);assertThat(jdbc.queryForObject("SELECT origen FROM lamontana.intento_activacion_configuracion WHERE estado='EXITOSO'",String.class)).isEqualTo("REINTENTO");assertThat(jdbc.queryForObject("SELECT fecha_atraso_detectado IS NULL FROM lamontana.intento_activacion_configuracion WHERE estado='EXITOSO'",Boolean.class)).isTrue();
    }
    @Test void reciboDeActivacionAnteriorNoInventaIntentoHistorico()throws Exception{
        preparar();var s=solicitud();var c=confirmacion(s,solicitar(s));var r=post(admin,rutaActivar()+"/confirmar",c);status(r,200);var version=JSON.readTree(r.body()).get("version");
        // Fixture de una activación previa a V19: su recibo y fecha real existían sin instrumentación de intentos.
        jdbc.update("DELETE FROM lamontana.intento_activacion_configuracion");var replay=post(admin,rutaActivar()+"/confirmar",c);status(replay,200);var resultado=JSON.readTree(replay.body());assertThat(resultado.get("estado").asString()).isEqualTo("EXITOSO");assertThat(resultado.get("intento").isNull()).isTrue();assertThat(resultado.get("version")).isEqualTo(version);assertThat(contar("activacion_configuracion")).isEqualTo(1);assertThat(contar("intento_activacion_configuracion")).isZero();
    }
    @Test void falloInmediatoNoAdelantaProgramacionCreadaDespues()throws Exception{
        preparar();var s=solicitud();var c=confirmacion(s,solicitar(s));publicar(null,"4",true,false);var r=post(admin,rutaActivar()+"/confirmar",c);status(r,200);assertThat(JSON.readTree(r.body()).get("estado").asString()).isEqualTo("FALLIDO");cooldown();programar();jdbc.update("UPDATE lamontana.intento_activacion_configuracion SET fecha_inicio=clock_timestamp()-interval '12 minutes',fecha_fin=clock_timestamp()-interval '11 minutes' WHERE estado='FALLIDO'");var prevista=estado().get("programada");assertThat(prevista.get("proximoIntentoEn")).isEqualTo(prevista.get("previstaEn"));ejecutar(false);assertThat(contar("intento_activacion_configuracion")).isEqualTo(1);assertThat(estado().get("activa").isNull()).isTrue();
    }
    @Test void automaticoQueGanaLaExclusionImpidePublicacionManualDuplicada()throws Exception{
        preparar();programar();vencerProgramacion();var c=autorizarAdelanto();var engine=app.getBean(EjecucionProgramadaService.class);
        try(var guard=pg.getPostgresDatabase().getConnection()){
            guard.setAutoCommit(false);try(var stmt=guard.createStatement()){stmt.execute("SELECT pg_advisory_xact_lock(764003)");}
            var automatico=CompletableFuture.runAsync(()->engine.reconciliar(false));boolean coordinando=false;
            for(int n=0;n<100;n++){coordinando=Boolean.TRUE.equals(jdbc.queryForObject("SELECT EXISTS(SELECT 1 FROM pg_locks WHERE locktype='advisory' AND objid=764004 AND granted)",Boolean.class));if(coordinando)break;Thread.sleep(10);}
            assertThat(coordinando).isTrue();var manual=admin.sendAsync(request(admin,"POST",rutaProgramar()+"/activacion/confirmar",c),HttpResponse.BodyHandlers.ofString());guard.commit();automatico.get(15,TimeUnit.SECONDS);status(manual.get(15,TimeUnit.SECONDS),409);
        }
        assertThat(contar("activacion_configuracion")).isEqualTo(1);assertThat(contar("intento_activacion_configuracion")).isEqualTo(1);assertThat(estado().get("intentos").get(0).get("origen").asString()).isEqualTo("PROGRAMACION");
    }
    @Test void manualQueGanaLaExclusionNoEsInterrumpidoPorElWorker()throws Exception{
        preparar();programar();vencerProgramacion();var c=autorizarAdelanto();var real=app.getBean(PublicacionConfiguracion.class);var demorada=org.mockito.Mockito.mock(PublicacionConfiguracion.class);var dentro=new CountDownLatch(1);var continuar=new CountDownLatch(1);
        org.mockito.Mockito.doAnswer(inv->{dentro.countDown();assertThat(continuar.await(10,TimeUnit.SECONDS)).isTrue();real.publicar(inv.getArgument(0),inv.getArgument(1),inv.getArgument(2),inv.getArgument(3),inv.getArgument(4));return null;}).when(demorada).publicar(org.mockito.ArgumentMatchers.anyLong(),org.mockito.ArgumentMatchers.any(),org.mockito.ArgumentMatchers.any(),org.mockito.ArgumentMatchers.any(),org.mockito.ArgumentMatchers.any());
        org.springframework.test.util.ReflectionTestUtils.setField(app.getBean(ActivacionConfiguracionService.class),"publicacion",demorada);
        var manual=admin.sendAsync(request(admin,"POST",rutaProgramar()+"/activacion/confirmar",c),HttpResponse.BodyHandlers.ofString());try{assertThat(dentro.await(10,TimeUnit.SECONDS)).isTrue();ejecutar(true);assertThat(contar("intento_activacion_configuracion")).isEqualTo(1);assertThat(jdbc.queryForObject("SELECT estado FROM lamontana.intento_activacion_configuracion",String.class)).isEqualTo("INICIADO");}finally{continuar.countDown();}
        var r=manual.get(15,TimeUnit.SECONDS);status(r,200);assertThat(JSON.readTree(r.body()).get("estado").asString()).isEqualTo("EXITOSO");assertThat(contar("activacion_configuracion")).isEqualTo(1);assertThat(contar("intento_activacion_configuracion")).isEqualTo(1);
    }
    private void servicios(List<String> sucursales)throws Exception{var c=comando();c.put("metodoAsignacion","MANUAL");c.put("serviciosPorSucursal",sucursales.stream().map(s->Map.of("sucursal",s,"servicios",List.of(servicio))).toList());aceptar(put(admin,base()+"/recursos",c));}
    private Map<String,Object> dia(int dia,Boolean habilitado,String apertura,String cierre){var d=new HashMap<String,Object>();d.put("dia",dia);d.put("habilitado",habilitado);d.put("apertura",apertura);d.put("cierre",cierre);return d;}
    private List<Map<String,Object>> semana(String apertura,String cierre){var dias=new ArrayList<Map<String,Object>>();for(int d=1;d<=7;d++)dias.add(dia(d,d<=5,d<=5?apertura:null,d<=5?cierre:null));return dias;}
    private List<Map<String,Object>> soloDomingo(String apertura,String cierre){var dias=new ArrayList<Map<String,Object>>();for(int d=1;d<=7;d++)dias.add(dia(d,d==7,d==7?apertura:null,d==7?cierre:null));return dias;}
    private Map<String,Object> horario(String sucursal,List<? extends Map<String,Object>> dias){return Map.of("sucursal",sucursal,"dias",dias);}
    private Map<String,Object> entrega(String preparacion,String traslado,List<String> modalidades,List<? extends Map<String,Object>> horarios){var c=comando();c.put("preparacionHoras",preparacion);c.put("trasladoHoras",traslado);c.put("modalidades",modalidades);c.put("horariosPorSucursal",horarios);return c;}
    private void guardar(String preparacion,String traslado,List<String> modalidades,List<? extends Map<String,Object>> horarios)throws Exception{aceptar(put(admin,ruta(),entrega(preparacion,traslado,modalidades,horarios)));}
    private Map<String,Object> simulacion(String sucursal,String modalidad,String recibido){return new HashMap<>(Map.of("version",borrador.get("version").asLong(),"sucursal",sucursal,"modalidad",modalidad,"recibidoEn",recibido));}
    private JsonNode simular(String sucursal,String modalidad,String recibido)throws Exception{var r=post(admin,ruta()+"/simular",simulacion(sucursal,modalidad,recibido));status(r,200);return JSON.readTree(r.body());}
    private JsonNode validacion()throws Exception{var r=get(admin,ruta()+"/validacion");status(r,200);return JSON.readTree(r.body());}
    private void assertProblemas(String... esperados)throws Exception{var v=validacion();assertThat(v.get("valida").asBoolean()).isFalse();var codigos=new ArrayList<String>();for(var p:v.get("problemas"))codigos.add(p.get("codigo").asString());assertThat(codigos).contains(esperados);}
    private void assertInstante(JsonNode respuesta,String campo,String esperado){assertThat(Instant.parse(respuesta.get(campo).asString())).isEqualTo(Instant.parse(esperado));}
    private String sucursal(String codigo)throws Exception{var r=post(admin,"/api/admin/sucursales",Map.of("codigo",codigo,"nombre","Sucursal "+codigo,"calle","Calle","numero","123","localidad","Ciudad","provincia","Provincia","codigoPostal","1234","zonaHoraria","America/Argentina/Buenos_Aires"));status(r,201);return JSON.readTree(r.body()).get("codigoPublico").asString();}
    private Map<String,Object> comando(){return new HashMap<>(Map.of("operacion",UUID.randomUUID().toString(),"version",borrador.get("version").asLong()));}
    private String base(){return "/api/admin/configuracion/borradores/"+id;}
    private String ruta(){return base()+"/entrega";}
    private int contar(String tabla){return jdbc.queryForObject("SELECT count(*) FROM lamontana."+tabla,Integer.class);}
    private JsonNode estado()throws Exception{var r=get(admin,"/api/admin/configuracion");status(r,200);return JSON.readTree(r.body());}
    private void aceptar(HttpResponse<String> r){status(r,200);borrador=JSON.readTree(r.body());}
    private HttpClient cliente(){return HttpClient.newBuilder().cookieHandler(new CookieManager(null,CookiePolicy.ACCEPT_ALL)).connectTimeout(Duration.ofSeconds(5)).build();}
    private URI uri(String path){return URI.create("http://127.0.0.1:"+port+path);}
    private HttpResponse<String> get(HttpClient c,String path)throws Exception{return c.send(HttpRequest.newBuilder(uri(path)).timeout(Duration.ofSeconds(15)).GET().build(),HttpResponse.BodyHandlers.ofString());}
    private String csrf(HttpClient c)throws Exception{var r=get(c,"/api/auth/csrf");status(r,200);return JSON.readTree(r.body()).get("token").asString();}
    private HttpRequest request(HttpClient c,String metodo,String path,Object data)throws Exception{return HttpRequest.newBuilder(uri(path)).timeout(Duration.ofSeconds(15)).header("Content-Type","application/json").header("X-CSRF-TOKEN",csrf(c)).method(metodo,HttpRequest.BodyPublishers.ofString(JSON.writeValueAsString(data))).build();}
    private HttpResponse<String> put(HttpClient c,String path,Object data)throws Exception{return c.send(request(c,"PUT",path,data),HttpResponse.BodyHandlers.ofString());}
    private HttpResponse<String> post(HttpClient c,String path,Object data)throws Exception{return c.send(request(c,"POST",path,data),HttpResponse.BodyHandlers.ofString());}
    private void login(HttpClient c,String correo)throws Exception{var r=HttpRequest.newBuilder(uri("/api/auth/login")).header("Content-Type","application/x-www-form-urlencoded").header("X-CSRF-TOKEN",csrf(c)).POST(HttpRequest.BodyPublishers.ofString("username="+URLEncoder.encode(correo,StandardCharsets.UTF_8)+"&password="+URLEncoder.encode(CLAVE,StandardCharsets.UTF_8))).build();status(c.send(r,HttpResponse.BodyHandlers.ofString()),200);}
    private void status(HttpResponse<String> r,int codigo){assertThat(r.statusCode()).withFailMessage("Esperado %s, recibido %s: %s",codigo,r.statusCode(),r.body()).isEqualTo(codigo);}
    private static final class CapturaSmtp implements AutoCloseable {
        private final ServerSocket servidor = new ServerSocket(0, 16, InetAddress.getByName("127.0.0.1"));
        private final BlockingQueue<Mensaje> mensajes = new LinkedBlockingQueue<>();
        private final ExecutorService hilo = Executors.newSingleThreadExecutor(r -> { var t = new Thread(r, "smtp-correo-test"); t.setDaemon(true); return t; });
        private volatile boolean rechazar;
        private volatile Exception fallo;
        CapturaSmtp() throws IOException { hilo.submit(this::aceptar); }
        int port() { return servidor.getLocalPort(); }
        int pendientes() { return mensajes.size(); }
        Mensaje recibir() throws Exception {
            var mensaje = mensajes.poll(5, TimeUnit.SECONDS);
            if (fallo != null) throw new AssertionError("Falló el servidor SMTP de prueba", fallo);
            assertThat(mensaje).as("El correo debe recibirse realmente por SMTP").isNotNull();
            return mensaje;
        }
        private void aceptar() {
            while (!servidor.isClosed()) {
                try (var socket = servidor.accept()) {
                    socket.setSoTimeout(5000);
                    var lector = new BufferedReader(new InputStreamReader(socket.getInputStream(), StandardCharsets.UTF_8));
                    var escritor = new BufferedWriter(new OutputStreamWriter(socket.getOutputStream(), StandardCharsets.UTF_8));
                    responder(escritor, "220 localhost ESMTP test");
                    for (String linea; (linea = lector.readLine()) != null;) {
                        String comando = linea.toUpperCase(Locale.ROOT);
                        if (comando.startsWith("EHLO") || comando.startsWith("HELO")) responder(escritor, "250 localhost");
                        else if (comando.startsWith("MAIL FROM:")) responder(escritor, "250 Sender OK");
                        else if (comando.startsWith("RCPT TO:")) responder(escritor, rechazar ? "451 Temporary SMTP failure" : "250 Recipient OK");
                        else if (comando.equals("DATA")) {
                            responder(escritor, "354 End data with <CRLF>.<CRLF>");
                            var datos = new StringBuilder();
                            while ((linea = lector.readLine()) != null && !linea.equals(".")) datos.append(linea.startsWith("..") ? linea.substring(1) : linea).append("\r\n");
                            var mime = new MimeMessage(Session.getInstance(new Properties()), new ByteArrayInputStream(datos.toString().getBytes(StandardCharsets.UTF_8)));
                            mensajes.add(new Mensaje(mime.getAllRecipients()[0].toString(), mime.getFrom()[0].toString(), mime.getSubject(), mime.getContent().toString()));
                            responder(escritor, "250 Queued");
                        } else if (comando.equals("QUIT")) { responder(escritor, "221 Bye"); break; }
                        else if (comando.equals("RSET") || comando.equals("NOOP")) responder(escritor, "250 OK");
                        else responder(escritor, "502 Command not implemented");
                    }
                } catch (Exception ex) { if (!servidor.isClosed()) fallo = ex; }
            }
        }
        private void responder(BufferedWriter escritor, String respuesta) throws IOException { escritor.write(respuesta + "\r\n"); escritor.flush(); }
        @Override public void close() throws Exception { servidor.close(); hilo.shutdownNow(); assertThat(hilo.awaitTermination(5, TimeUnit.SECONDS)).isTrue(); }
    }
    private record Mensaje(String destino, String remitente, String asunto, String cuerpo) {
        String token() {
            var encontrado = Pattern.compile("(?m)^[A-Za-z0-9_-]{43}\\r?$").matcher(cuerpo);
            assertThat(encontrado.find()).as("Código opaco presente en el correo MIME").isTrue();
            return encontrado.group().strip();
        }
        @Override public String toString() { return "Mensaje SMTP [contenido privado de prueba]"; }
    }
}
