import { catalogDate, colorLabels, priceLabels, type CatalogState, type CatalogRevision } from "@/lib/catalog-types";
import {ars} from "@/lib/catalog-pricing";
import {paperLabel} from "@/components/catalog-paper-select";
export function RevisionView({ revision, catalog }: { revision:CatalogRevision; catalog:CatalogState }) {
  return <div className="catalog-revision-view"><p><strong>Revisión {revision.numero}</strong> · {catalogDate(revision.creadaEn)} · {revision.actor}</p><p>{revision.motivo}</p><p>Estado: {revision.estado.toLowerCase()}{revision.programadaPara&&<> · Programada para {catalogDate(revision.programadaPara)}</>}{revision.activadaEn&&<> · Activada el {catalogDate(revision.activadaEn)}</>}</p><p>Moneda: ARS · pesos argentinos. Importes fijos.</p>
    <h3>Tarifas de impresión</h3><div className="pricing-read-list">{revision.tarifas.map((rate,index)=><article className="pricing-read-card" key={index}><strong>{paperLabel(catalog,rate)}</strong><dl><div><dt>Color</dt><dd>{colorLabels[rate.color]}</dd></div><div><dt>Por carilla</dt><dd>{ars(rate.precio)}</dd></div><div><dt>Recargo doble faz por carilla</dt><dd>{ars(rate.recargoDobleFaz)}</dd></div><div><dt>Estado</dt><dd>{rate.habilitada?"Habilitada":"Deshabilitada"}</dd></div></dl></article>)}</div>
    <h3>Servicios</h3><div className="pricing-read-list">{revision.servicios.map(offer=>{const printing=catalog.servicios.find(s=>s.codigoPublico===offer.servicio)?.tipo==="IMPRESION";return <article className="pricing-read-card" key={offer.servicio}><strong>{offer.nombreVisible}</strong><dl><div><dt>Forma de cobro</dt><dd>{priceLabels[offer.basePrecio]}</dd></div><div><dt>Precio</dt><dd>{printing?"Según tarifas de impresión":ars(offer.precio)}</dd></div><div><dt>Preparación</dt><dd>{offer.preparacionMinutos} min</dd></div><div><dt>Estado</dt><dd>{offer.habilitado?"Habilitado":"Deshabilitado"}</dd></div></dl>{offer.compatibilidades.length>0&&<div><strong>Papeles compatibles</strong><ul>{offer.compatibilidades.map((pair,i)=><li key={i}>{paperLabel(catalog,pair)}</li>)}</ul></div>}</article>;})}</div>
  </div>;
}
