"use client";
import {useEffect,useRef,useState,type FormEvent} from "react";
import {MutationError,secureMutation} from "@/lib/secure-mutation";
import {isConfigurationDraft,isConfigurationState,type ConfigurationDraft,type DeliveryZone,type DeliveryTerritory} from "@/lib/configuration-types";
const days=["Lunes","Martes","Miércoles","Jueves","Viernes","Sábado","Domingo"];
type Slot={dia:string;apertura:string;cierre:string;capacidad:string;habilitada:string};
type Form={codigo:string;nombre:string;descripcion:string;zonaHoraria:string;costo:string;habilitada:string;territorios:DeliveryTerritory[];franjas:Slot[]};
type Command={path:string;method:"POST"|"PUT";body:string};
const empty:Form={codigo:"",nombre:"",descripcion:"",zonaHoraria:"",costo:"",habilitada:"",territorios:[],franjas:[]};
function fromZone(z:DeliveryZone):Form{return{...z,descripcion:z.descripcion??"",habilitada:z.habilitada?"SI":"NO",franjas:z.franjas.map(f=>({dia:String(f.dia),apertura:f.apertura,cierre:f.cierre,capacidad:String(f.capacidadPedidos),habilitada:f.habilitada?"SI":"NO"}))};}

export function ConfigurationZones({draft,onSaved,onBack,onLockChange}:{draft:ConfigurationDraft;onSaved:(d:ConfigurationDraft)=>void;onBack:()=>void;onLockChange:(v:boolean)=>void}){
 const[current,setCurrent]=useState(draft),[editor,setEditor]=useState<"NEW"|DeliveryZone|null>(null),[form,setForm]=useState<Form>(empty),[query,setQuery]=useState("");
 const[busy,setBusy]=useState(false),[uncertain,setUncertain]=useState(false),[error,setError]=useState(""),[conflict,setConflict]=useState(false),[latest,setLatest]=useState<ConfigurationDraft|null>(null);
 const command=useRef<Command|null>(null),locked=busy||uncertain,base=`/api/admin/configuracion/borradores/${draft.codigoPublico}/entrega/zonas`;
 useEffect(()=>{onLockChange(locked);return()=>onLockChange(false);},[locked,onLockChange]);
 function change<K extends keyof Form>(k:K,v:Form[K]){setForm(f=>({...f,[k]:v}));}
 function open(z?:DeliveryZone){setEditor(z??"NEW");setForm(z?fromZone(z):{...empty,territorios:[],franjas:[]});setError("");setConflict(false);setLatest(null);}
 async function state(){const r=await fetch("/api/admin/configuracion",{cache:"no-store"});const data:unknown=await r.json();if(!r.ok||!isConfigurationState(data))throw new Error("No pudimos consultar el borrador.");return data;}
 async function send(event?:FormEvent){event?.preventDefault();if(busy)return;setBusy(true);setError("");try{
  if(!command.current){if(!editor)throw new Error("No hay una zona seleccionada.");const body={operacion:crypto.randomUUID(),version:current.version,...(editor==="NEW"?{codigo:form.codigo}:{}),nombre:form.nombre,descripcion:form.descripcion.trim()||null,zonaHoraria:form.zonaHoraria,costo:form.costo||null,habilitada:form.habilitada===""?null:form.habilitada==="SI",territorios:form.territorios,franjas:form.franjas.map(f=>({dia:f.dia?Number(f.dia):null,apertura:f.apertura,cierre:f.cierre,capacidadPedidos:f.capacidad===""?null:Number(f.capacidad),habilitada:f.habilitada===""?null:f.habilitada==="SI"}))};command.current={path:base+(editor==="NEW"?"":`/${editor.codigoPublico}`),method:editor==="NEW"?"POST":"PUT",body:JSON.stringify(body)};}
  const c=command.current,r=await secureMutation(c.path,c.body,"application/json",c.method),data:unknown=await r.json();if(!isConfigurationDraft(data))throw new Error("No pudimos confirmar la zona guardada.");command.current=null;setUncertain(false);onSaved(data);
 }catch(cause){setError(cause instanceof Error?cause.message:"No pudimos guardar la zona.");if(cause instanceof MutationError&&!cause.uncertain){command.current=null;setUncertain(false);if(cause.status===409){try{const data=await state();setConflict(!data.borrador||data.borrador.codigoPublico!==current.codigoPublico||data.borrador.version!==current.version);}catch{setConflict(true);}}}else if(command.current)setUncertain(true);}finally{setBusy(false);}}
 async function consult(){setBusy(true);setError("");try{const data=await state();if(!data.borrador)throw new Error("El borrador ya no está en preparación. Recargá para consultar su historial.");setLatest(data.borrador);}catch(cause){setError(cause instanceof Error?cause.message:"No pudimos consultar el borrador.");}finally{setBusy(false);}}
 function adopt(){if(!latest)return;if(latest.codigoPublico!==draft.codigoPublico){onSaved(latest);return;}if(editor&&editor!=="NEW"&&!latest.entrega.zonas.some(z=>z.codigoPublico===editor.codigoPublico)){setError("La zona ya no pertenece al borrador. Cargá el estado guardado.");return;}setCurrent(latest);setLatest(null);setConflict(false);setError("");}
 const visible=current.entrega.zonas.filter(z=>`${z.codigo} ${z.nombre} ${z.territorios.map(t=>`${t.codigoPostal} ${t.localidad} ${t.provincia}`).join(" ")}`.toLocaleLowerCase().includes(query.toLocaleLowerCase()));
 return <><h2>Administrar zonas de envío</h2><p className="admin-note">Fase 5 · Borrador {draft.numero} · Editando versión {current.version}. Cobertura, costo y cupo globales para todas las sucursales; se aplicarán al activar esta configuración.</p>
 {!editor?<div className="point-list-layout"><section><div className="resource-toolbar"><h3>Zonas de envío a domicilio</h3><button className="admin-button" disabled={locked} onClick={()=>open()}>Agregar zona</button></div><div className="catalog-field point-search zone-search"><label htmlFor="zone-search">Buscar zona o cobertura</label><input id="zone-search" value={query} onChange={e=>setQuery(e.target.value)}/></div>{visible.length===0&&<p className="admin-empty">No hay zonas para mostrar. La instalación comienza sin cobertura precargada.</p>}{visible.map(z=><article className="admin-card zone-card" key={z.codigoPublico}><div className="resource-toolbar"><h3>{z.nombre}</h3><span className="configuration-badge">{z.habilitada?"Habilitada en borrador":"Deshabilitada en borrador"}</span></div><p>{z.codigo} · {z.zonaHoraria} · ARS {z.costo}</p>{z.descripcion&&<p>{z.descripcion}</p>}<ul>{z.territorios.map((t,i)=><li key={i}>{t.codigoPostal} · {t.localidad} · {t.provincia}</li>)}</ul><p className="admin-note">{z.territorios.length} combinaciones territoriales · {z.franjas.length} franjas. Cupos configurados, sin reservas.</p><button className="admin-button secondary" disabled={locked} onClick={()=>open(z)}>Editar {z.nombre}</button></article>)}</section><aside className="admin-card point-summary"><h3>Cobertura sin mapas</h3><p>Se compara la combinación completa de código postal, localidad y provincia. No se aceptan rangos ni comodines.</p><p>Una combinación no puede pertenecer a dos zonas habilitadas. Primero deshabilitá la zona anterior o quitá esa combinación.</p><p className="admin-note">Los cambios son estructurales. No modifican pedidos pactados. Oferta al cliente y reservas: <strong>En construcción</strong>.</p></aside></div>:<form className="admin-form admin-card point-editor" onSubmit={send}><h3>{editor==="NEW"?"Agregar zona de envío":`Editar zona · ${editor.nombre}`}</h3><fieldset className="admin-fieldset" disabled={locked}><div className="admin-form-grid">
 <label>Código de la zona<input required pattern="[A-Za-z0-9_-]{1,40}" maxLength={40} readOnly={editor!=="NEW"} value={form.codigo} onChange={e=>change("codigo",e.target.value)}/></label><label>Nombre de la zona<input required maxLength={140} value={form.nombre} onChange={e=>change("nombre",e.target.value)}/></label><label>Zona horaria de envío<input required maxLength={64} value={form.zonaHoraria} onChange={e=>change("zonaHoraria",e.target.value)}/><small>Nombre IANA para interpretar las franjas del destino.</small></label><label>Costo de envío (ARS)<input required type="number" min="0" max="999999999999.99" step="0.01" value={form.costo} onChange={e=>change("costo",e.target.value)}/><small>Cero debe ingresarse expresamente.</small></label><div className="catalog-field"><label htmlFor="zone-enabled">Estado de la zona</label><select id="zone-enabled" required value={form.habilitada} onChange={e=>change("habilitada",e.target.value)}><option value="">Elegir estado</option><option value="SI">Habilitada en el borrador</option><option value="NO">Deshabilitada en el borrador</option></select></div></div><label className="point-references">Descripción de cobertura<textarea maxLength={2000} value={form.descripcion} onChange={e=>change("descripcion",e.target.value)}/></label>
 <section className="point-origins"><h3>Cobertura territorial</h3><p className="admin-note">Se normalizan mayúsculas y espacios; los acentos se conservan. El código postal no distingue espacios. Podés guardar sin cobertura y completarla después.</p>{form.territorios.map((t,i)=><section className="point-origin zone-territory" key={i}><h4>Combinación {i+1}</h4><div className="admin-form-grid">{([['codigoPostal','Código postal'],['localidad','Localidad'],['provincia','Provincia']] as const).map(([key,label])=><label key={key}>{label} de cobertura {i+1}<input required maxLength={key==='codigoPostal'?24:120} value={t[key]} onChange={e=>change("territorios",form.territorios.map((v,j)=>j===i?{...v,[key]:e.target.value}:v))}/></label>)}</div><button type="button" className="admin-button secondary" onClick={()=>change("territorios",form.territorios.filter((_,j)=>i!==j))}>Quitar cobertura {i+1}</button></section>)}<button type="button" className="admin-button secondary" disabled={form.territorios.length>=100} onClick={()=>change("territorios",[...form.territorios,{codigoPostal:"",localidad:"",provincia:""}])}>Agregar cobertura</button></section>
 <section className="point-origins"><h3>Franjas y cupos globales</h3><p className="admin-note">El cupo se comparte entre todas las sucursales para una misma fecha y franja. No representa plazas libres. Cero no permite reservas.</p><div className="admin-table-wrap" tabIndex={0} aria-label="Franjas de la zona"><table className="admin-table point-slots"><thead><tr><th>Día</th><th>Desde</th><th>Hasta</th><th>Cupo de pedidos</th><th>Estado</th><th>Acción</th></tr></thead><tbody>{form.franjas.map((f,i)=>{const slot=(key:keyof Slot,value:string)=>change("franjas",form.franjas.map((v,j)=>j===i?{...v,[key]:value}:v));return <tr key={i}><td><select required aria-label={`Día franja de zona ${i+1}`} value={f.dia} onChange={e=>slot("dia",e.target.value)}><option value="">Elegir día</option>{days.map((d,j)=><option key={d} value={j+1}>{d}</option>)}</select></td><td><input required aria-label={`Apertura franja de zona ${i+1}`} type="time" step="60" value={f.apertura} onChange={e=>slot("apertura",e.target.value)}/></td><td><input required aria-label={`Cierre franja de zona ${i+1}`} type="time" step="60" value={f.cierre} onChange={e=>slot("cierre",e.target.value)}/></td><td><input required aria-label={`Cupo franja de zona ${i+1}`} type="number" min="0" max="2147483647" step="1" value={f.capacidad} onChange={e=>slot("capacidad",e.target.value)}/></td><td><select required aria-label={`Estado franja de zona ${i+1}`} value={f.habilitada} onChange={e=>slot("habilitada",e.target.value)}><option value="">Elegir estado</option><option value="SI">Habilitada</option><option value="NO">Deshabilitada</option></select></td><td><button type="button" className="admin-button secondary" onClick={()=>change("franjas",form.franjas.filter((_,j)=>i!==j))}>Quitar franja de zona {i+1}</button></td></tr>})}</tbody></table></div>{form.franjas.length===0&&<p className="admin-empty">Todavía no hay franjas para esta zona.</p>}<button type="button" className="admin-button secondary" disabled={form.franjas.length>=100} onClick={()=>change("franjas",[...form.franjas,{dia:"",apertura:"",cierre:"",capacidad:"",habilitada:""}])}>Agregar franja de zona</button></section>
 </fieldset><div className="configuration-actions"><button type="button" className="admin-button secondary" disabled={locked} onClick={()=>{setEditor(null);setConflict(false);setLatest(null);setError("");}}>Volver a la lista de zonas</button><button className="admin-button" disabled={locked||conflict}>Guardar zona</button></div></form>}
 {error&&<p className="admin-warning" role="alert">{error}</p>}{uncertain&&<div className="admin-warning"><p>No pudimos confirmar la respuesta. Conservamos la misma operación para recuperar el guardado sin duplicarlo.</p><button className="admin-button" disabled={busy} onClick={()=>send()}>Reintentar la misma operación</button></div>}{conflict&&<div className="admin-warning"><p>El borrador cambió. Tus datos permanecen en el formulario.</p><button className="admin-button secondary" disabled={locked} onClick={consult}>Consultar zonas guardadas</button></div>}{latest&&<section className="admin-card"><h3>Edición actual {latest.version}</h3><p>{latest.entrega.zonas.length} zonas guardadas. Revisá antes de volver a guardar.</p><div className="configuration-actions"><button className="admin-button secondary" disabled={locked} onClick={adopt}>Usar edición actual conservando mis datos</button><button className="admin-button secondary" disabled={locked} onClick={()=>onSaved(latest)}>Cargar el estado guardado</button></div></section>}<div className="configuration-actions"><button className="admin-button secondary" disabled={locked} onClick={onBack}>Volver a horarios y entrega</button></div></>;
}
