"use client";
import {useState,useCallback} from "react";
import {DraftCancellation} from "@/components/draft-cancellation";
import type {ConfigurationSchedule,ConfigurationVersion,ConfigurationDraft} from "@/lib/configuration-types";
export function ConfigurationSchedulePanel({value,active,onRefresh,onCancelled,onAdvance,onLockChange}:{value:ConfigurationSchedule;active:ConfigurationVersion|null;onRefresh:()=>Promise<void>;onAdvance:()=>Promise<void>;onCancelled:(d:ConfigurationDraft)=>Promise<void>;onLockChange:(b:boolean)=>void}){
 const[busy,setBusy]=useState(false),[locked,setLocked]=useState(false),[error,setError]=useState("");
 const lock=useCallback((b:boolean)=>{setLocked(b);onLockChange(b);},[onLockChange]);
 async function refresh(){setBusy(true);onLockChange(true);setError("");try{await onRefresh();}catch{setError("No pudimos consultar el estado. Intentá nuevamente.");}finally{setBusy(false);onLockChange(false);}}
 const date=new Intl.DateTimeFormat("es-AR",{dateStyle:"short",timeStyle:"short",timeZone:value.zonaHoraria});
 return <section className="admin-card"><h3>Programación V{value.configuracion.numero}</h3><div className="activation-facts"><p><small>Fecha prevista</small><strong>{date.format(new Date(value.previstaEn))}</strong></p><p><small>Zona horaria</small><strong>{value.zonaHoraria}</strong></p><p><small>Autorizada por</small><strong>{value.programador}</strong></p><p><small>Próximo intento</small><strong>{value.proximoIntentoEn?date.format(new Date(value.proximoIntentoEn)):"En ejecución"}</strong></p></div><p>Motivo: {value.motivo}</p><p className="admin-info">{active?`V${active.configuracion.numero} sigue vigente.`:"Todavía no hay configuración activa."} El vencimiento de la fecha no garantiza la activación: se revalidan permisos, catálogo y condiciones actuales. Cada fallo se reintenta diez minutos después.</p><p className="admin-warning">Esta versión no se puede editar. Cancelala para preparar otra; cancelar conserva todo el contenido.</p><button className="admin-button secondary" disabled={busy||locked} onClick={refresh}>{busy?"Consultando…":"Actualizar programación"}</button>{error&&<p className="admin-warning" role="alert">{error}</p>}<h4>Últimos intentos</h4>{value.intentos.length===0?<p className="admin-empty">Todavía no comenzó ningún intento.</p>:<ul>{value.intentos.map(i=><li key={i.codigo}><strong>{i.estado}</strong> · {date.format(new Date(i.iniciadoEn))} · {i.origen}<p>{i.detalle}</p>{i.terminadoEn&&<small>Finalizado: {date.format(new Date(i.terminadoEn))}</small>}</li>)}</ul>}<button className="admin-button" disabled={busy||locked||value.intentos[0]?.estado==="INICIADO"} onClick={onAdvance}>Revisar para activar ahora</button><p className="admin-note">Activar ahora requiere una nueva revisión, contraseña y código de correo. Si falla, la programación sigue pendiente.</p><DraftCancellation key={`${value.configuracion.codigoPublico}:${value.configuracion.version}`} draft={value.configuracion} onRefresh={onRefresh} onCancelled={onCancelled} onLockChange={lock}/></section>;
}
