"use client";
import {useNavigationGuard,useConfirmNavigation} from "@/components/navigation-boundary";
import {useEffect,useRef,useState,type FormEvent} from "react";
import {MutationError,secureMutation} from "@/lib/secure-mutation";
import {isConfigurationDraft,isConfigurationState,type ConfigurationDraft,type DeliveryPoint} from "@/lib/configuration-types";
import {isBranch,type Branch} from "@/lib/organization-types";
const days=["Lunes","Martes","Miércoles","Jueves","Viernes","Sábado","Domingo"];
type SlotForm={dia:string;apertura:string;cierre:string;capacidad:string;habilitada:string};
type OriginForm={sucursal:string;habilitado:string;costo:string;franjas:SlotForm[]};
type PointForm={codigo:string;nombre:string;calle:string;numero:string;localidad:string;provincia:string;codigoPostal:string;referencias:string;zonaHoraria:string;sucursales:OriginForm[]};
type Command={path:string;method:"POST"|"PUT";body:string};
const empty:PointForm={codigo:"",nombre:"",calle:"",numero:"",localidad:"",provincia:"",codigoPostal:"",referencias:"",zonaHoraria:"",sucursales:[]};
function fromPoint(p:DeliveryPoint):PointForm{return{codigo:p.codigo,nombre:p.nombre,calle:p.calle,numero:p.numero,localidad:p.localidad,provincia:p.provincia,codigoPostal:p.codigoPostal,referencias:p.referencias??"",zonaHoraria:p.zonaHoraria,sucursales:p.sucursales.map(s=>({sucursal:s.sucursal,habilitado:s.habilitado?"SI":"NO",costo:s.costo,franjas:s.franjas.map(f=>({dia:String(f.dia),apertura:f.apertura,cierre:f.cierre,capacidad:String(f.capacidadPedidos),habilitada:f.habilitada?"SI":"NO"}))}))};}

export function ConfigurationPoints({draft,onSaved,onBack,onLockChange}:{draft:ConfigurationDraft;onSaved:(value:ConfigurationDraft)=>void;onBack:()=>void;onLockChange:(value:boolean)=>void}){
  const [current,setCurrent]=useState(draft),[branches,setBranches]=useState<Branch[]>([]),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState("");
  const [editor,setEditor]=useState<"NEW"|DeliveryPoint|null>(null),[form,setForm]=useState<PointForm>(empty),[branchToAdd,setBranchToAdd]=useState(""),[query,setQuery]=useState("");
  const [busy,setBusy]=useState(false),[uncertain,setUncertain]=useState(false),[error,setError]=useState(""),[conflict,setConflict]=useState(false),[latest,setLatest]=useState<ConfigurationDraft|null>(null);
  const command=useRef<Command|null>(null),locked=busy||uncertain,base=`/api/admin/configuracion/borradores/${draft.codigoPublico}/entrega/puntos`;
  const confirmNavigation=useConfirmNavigation();
 useNavigationGuard({dirty:!!editor&&JSON.stringify(form)!==JSON.stringify(editor==="NEW"?empty:fromPoint(editor)),blocked:locked});
 useEffect(()=>{onLockChange(locked);return()=>onLockChange(false);},[locked,onLockChange]);
  async function load(){setLoading(true);setLoadError("");try{const r=await fetch("/api/admin/sucursales",{cache:"no-store"});const b:unknown=await r.json();if(!r.ok||!Array.isArray(b)||!b.every(isBranch))throw new Error("No pudimos consultar las sucursales.");setBranches(b);}catch(cause){setLoadError(cause instanceof Error?cause.message:"No pudimos consultar las sucursales.");}finally{setLoading(false);}}
  useEffect(()=>{void load();},[]);
  function branchName(id:string){return branches.find(b=>b.codigoPublico===id)?.nombre??id;}
  function change<K extends keyof PointForm>(key:K,value:PointForm[K]){setForm(f=>({...f,[key]:value}));}
  function originChange(id:string,field:"habilitado"|"costo",value:string){setForm(f=>({...f,sucursales:f.sucursales.map(s=>s.sucursal===id?{...s,[field]:value}:s)}));}
  function slotChange(id:string,index:number,field:keyof SlotForm,value:string){setForm(f=>({...f,sucursales:f.sucursales.map(s=>s.sucursal===id?{...s,franjas:s.franjas.map((slot,i)=>i===index?{...slot,[field]:value}:slot)}:s)}));}
  function addOrigin(){if(!branchToAdd||form.sucursales.some(s=>s.sucursal===branchToAdd))return;change("sucursales",[...form.sucursales,{sucursal:branchToAdd,habilitado:"",costo:"",franjas:[]}]);setBranchToAdd("");}
  function open(p?:DeliveryPoint){setEditor(p??"NEW");setForm(p?fromPoint(p):{...empty,sucursales:[]});setError("");setBranchToAdd("");setConflict(false);setLatest(null);}
  async function state(){const r=await fetch("/api/admin/configuracion",{cache:"no-store"});const data:unknown=await r.json();if(!r.ok||!isConfigurationState(data))throw new Error("No pudimos consultar el borrador.");return data;}
  async function send(event?:FormEvent){event?.preventDefault();if(busy)return;setBusy(true);setError("");try{
    if(!command.current){if(!editor)throw new Error("No hay un punto seleccionado.");const {codigo,...fields}=form;const body={operacion:crypto.randomUUID(),version:current.version,...(editor==="NEW"?{codigo}:{}),...fields,referencias:form.referencias.trim()||null,sucursales:form.sucursales.map(s=>({sucursal:s.sucursal,habilitado:s.habilitado===""?null:s.habilitado==="SI",costo:s.costo||null,franjas:s.franjas.map(f=>({dia:f.dia?Number(f.dia):null,apertura:f.apertura,cierre:f.cierre,capacidadPedidos:f.capacidad===""?null:Number(f.capacidad),habilitada:f.habilitada===""?null:f.habilitada==="SI"}))}))};command.current={path:base+(editor==="NEW"?"":`/${editor.codigoPublico}`),method:editor==="NEW"?"POST":"PUT",body:JSON.stringify(body)};}
    const c=command.current,r=await secureMutation(c.path,c.body,"application/json",c.method),data:unknown=await r.json();if(!isConfigurationDraft(data))throw new Error("No pudimos confirmar el punto guardado.");command.current=null;setUncertain(false);onSaved(data);
  }catch(cause){setError(cause instanceof Error?cause.message:"No pudimos guardar el punto.");if(cause instanceof MutationError&&!cause.uncertain){command.current=null;setUncertain(false);if(cause.status===409){try{const data=await state();setConflict(!data.borrador||data.borrador.codigoPublico!==current.codigoPublico||data.borrador.version!==current.version);}catch{setConflict(true);}}}else if(command.current)setUncertain(true);}finally{setBusy(false);}}
  async function consult(){setBusy(true);setError("");try{const data=await state();if(!data.borrador)throw new Error("El borrador ya no está en preparación. Recargá para consultar su historial.");setLatest(data.borrador);}catch(cause){setError(cause instanceof Error?cause.message:"No pudimos consultar el borrador.");}finally{setBusy(false);}}
  function adopt(){if(!latest)return;if(latest.codigoPublico!==draft.codigoPublico){onSaved(latest);return;}if(editor&&editor!=="NEW"&&!latest.entrega.puntos.some(p=>p.codigoPublico===editor.codigoPublico)){setError("El punto ya no pertenece al borrador actual. Cargá el estado guardado.");return;}setCurrent(latest);setLatest(null);setConflict(false);setError("");}
  const visible=current.entrega.puntos.filter(p=>`${p.codigo} ${p.nombre} ${p.calle} ${p.numero} ${p.localidad} ${p.referencias??""}`.toLocaleLowerCase().includes(query.toLocaleLowerCase()));
  return <>
    <h2>Administrar puntos de entrega</h2><p className="admin-note">Fase 5 · Borrador {draft.numero} · Editando versión {current.version}. Nombre, dirección, orígenes y franjas son cambios estructurales de esta configuración.</p>
    <p className="admin-info">La disponibilidad temporal se gestiona por separado desde <a href={locked?undefined:"/administracion/puntos-entrega"} aria-disabled={locked}>Disponibilidad de puntos</a>. Guardar una definición todavía no habilita pedidos ni reservas.</p>
    {loading&&<p role="status">Consultando sucursales…</p>}{loadError&&<p className="admin-warning" role="alert">{loadError}</p>}
    {!editor?<div className="point-list-layout"><section><div className="resource-toolbar"><div className="catalog-field point-search"><label htmlFor="point-search">Buscar punto, dirección o referencia</label><input id="point-search" value={query} disabled={locked} onChange={e=>setQuery(e.target.value)}/></div><button type="button" className="admin-button" disabled={locked||loading||!!loadError} onClick={()=>open()}>Agregar punto</button></div>
      {visible.length===0?<p className="admin-empty">{current.entrega.puntos.length?"No hay coincidencias.":"Todavía no hay puntos en este borrador."}</p>:visible.map(p=><article className="admin-card point-row" key={p.codigoPublico}><div className="point-location"><span className="point-location-icon" aria-hidden="true">⌖</span><div><h3>{p.nombre}</h3><p>{p.calle} {p.numero} · {p.localidad}, {p.provincia}</p><small>{p.codigo} · {p.zonaHoraria}</small></div></div><div className="point-origins-summary">{p.sucursales.length===0?<p>Sin sucursales de origen</p>:p.sucursales.map(s=><p key={s.sucursal}><strong>{branchName(s.sucursal)}</strong><span>{s.habilitado?"Relación habilitada":"Relación deshabilitada"} · Costo ARS {s.costo}</span><small>{s.franjas.length} franjas declaradas · {s.franjas.filter(f=>f.habilitada&&f.capacidadPedidos>0).length} con cupo configurado</small></p>)}</div><div><span className="configuration-badge">Definición en borrador</span><button type="button" className="admin-button secondary" disabled={locked||loading||!!loadError} onClick={()=>open(p)}>Editar {p.nombre}</button></div></article>)}
    </section><aside className="admin-card point-summary"><h3>Resumen de puntos</h3><dl><dt>Definiciones en el borrador</dt><dd>{current.entrega.puntos.length}</dd><dt>Con sucursales de origen</dt><dd>{current.entrega.puntos.filter(p=>p.sucursales.length>0).length}</dd></dl><p className="admin-note">Son definiciones para revisar y activar. La disponibilidad temporal y su recordatorio se consultan en el dashboard.</p></aside></div>:<form className="admin-form admin-card point-editor" onSubmit={send}>
      <h3>{editor==="NEW"?"Agregar punto de entrega":`Editar punto · ${editor.nombre}`}</h3><fieldset className="admin-fieldset" disabled={locked||loading||!!loadError}><div className="admin-form-grid">
        <div className="catalog-field"><label htmlFor="point-code">Código del punto</label><input id="point-code" aria-describedby="point-code-help" required pattern="[A-Za-z0-9_-]{1,40}" maxLength={40} readOnly={editor!=="NEW"} value={form.codigo} onChange={e=>change("codigo",e.target.value)}/><small id="point-code-help">Identifica al punto y se conserva al editar.</small></div>
        <label>Nombre del punto<input required maxLength={160} value={form.nombre} onChange={e=>change("nombre",e.target.value)}/></label>
        <label>Calle del punto<input required maxLength={160} value={form.calle} onChange={e=>change("calle",e.target.value)}/></label><label>Número del punto<input required maxLength={20} value={form.numero} onChange={e=>change("numero",e.target.value)}/></label>
        <label>Localidad del punto<input required maxLength={120} value={form.localidad} onChange={e=>change("localidad",e.target.value)}/></label><label>Provincia del punto<input required maxLength={120} value={form.provincia} onChange={e=>change("provincia",e.target.value)}/></label><label>Código postal del punto<input required maxLength={12} value={form.codigoPostal} onChange={e=>change("codigoPostal",e.target.value)}/></label>
        <div className="catalog-field"><label htmlFor="point-zone">Zona horaria del punto</label><input id="point-zone" aria-describedby="point-zone-help" required maxLength={64} list="point-zones" value={form.zonaHoraria} onChange={e=>change("zonaHoraria",e.target.value)}/><datalist id="point-zones">{[...new Set(branches.map(b=>b.zonaHoraria))].map(zone=><option key={zone} value={zone}/>)}</datalist><small id="point-zone-help">Nombre IANA, utilizado para interpretar las franjas locales.</small></div>
      </div><label className="point-references">Referencias para llegar<textarea maxLength={2000} value={form.referencias} onChange={e=>change("referencias",e.target.value)}/></label>
      <section className="point-origins"><h3>Sucursales de origen y franjas</h3><p className="admin-note">Cada relación tiene costo y cupo propios. Podés guardar la dirección sin relaciones y completarlas después. El punto aún no ofrecerá entregas.</p><div className="point-add-origin"><div className="catalog-field"><label htmlFor="point-origin">Sucursal de origen para agregar</label><select id="point-origin" value={branchToAdd} onChange={e=>setBranchToAdd(e.target.value)}><option value="">Elegir sucursal</option>{branches.filter(b=>b.estado==="ACTIVA"&&!form.sucursales.some(s=>s.sucursal===b.codigoPublico)).map(b=><option key={b.codigoPublico} value={b.codigoPublico}>{b.nombre}</option>)}</select></div><button type="button" className="admin-button secondary" disabled={!branchToAdd} onClick={addOrigin}>Agregar sucursal de origen</button></div>
      {form.sucursales.map(s=><section className="point-origin" key={s.sucursal}><div className="resource-toolbar"><h4>{branchName(s.sucursal)}{branches.find(b=>b.codigoPublico===s.sucursal)?.estado==="DESACTIVADA"&&" · Desactivada"}</h4><button type="button" className="admin-button secondary" onClick={()=>change("sucursales",form.sucursales.filter(v=>v.sucursal!==s.sucursal))}>Quitar origen {branchName(s.sucursal)}</button></div><div className="admin-form-grid"><div className="catalog-field"><label htmlFor={`point-enabled-${s.sucursal}`}>Estado de la relación con {branchName(s.sucursal)}</label><select id={`point-enabled-${s.sucursal}`} required value={s.habilitado} onChange={e=>originChange(s.sucursal,"habilitado",e.target.value)}><option value="">Elegir estado</option><option value="SI">Habilitada en el borrador</option><option value="NO">Deshabilitada en el borrador</option></select></div><div className="catalog-field"><label htmlFor={`point-cost-${s.sucursal}`}>Costo desde {branchName(s.sucursal)} (ARS)</label><input id={`point-cost-${s.sucursal}`} aria-describedby={`point-cost-help-${s.sucursal}`} required type="number" min="0" max="999999999999.99" step="0.01" value={s.costo} onChange={e=>originChange(s.sucursal,"costo",e.target.value)}/><small id={`point-cost-help-${s.sucursal}`}>Ingresá cero expresamente si no tiene costo.</small></div></div>
      <div className="admin-table-wrap" tabIndex={0} aria-label={`Franjas desde ${branchName(s.sucursal)}`}><table className="admin-table point-slots"><thead><tr><th>Día</th><th>Desde</th><th>Hasta</th><th>Cupo de pedidos</th><th>Estado</th><th>Acción</th></tr></thead><tbody>{s.franjas.map((f,i)=><tr key={i}><td><select required aria-label={`Día franja ${i+1} de ${branchName(s.sucursal)}`} value={f.dia} onChange={e=>slotChange(s.sucursal,i,"dia",e.target.value)}><option value="">Elegir día</option>{days.map((day,j)=><option key={day} value={j+1}>{day}</option>)}</select></td><td><input required aria-label={`Apertura franja ${i+1} de ${branchName(s.sucursal)}`} type="time" step="60" value={f.apertura} onChange={e=>slotChange(s.sucursal,i,"apertura",e.target.value)}/></td><td><input required aria-label={`Cierre franja ${i+1} de ${branchName(s.sucursal)}`} type="time" step="60" value={f.cierre} onChange={e=>slotChange(s.sucursal,i,"cierre",e.target.value)}/></td><td><input required aria-label={`Cupo franja ${i+1} de ${branchName(s.sucursal)}`} type="number" min="0" max="2147483647" step="1" value={f.capacidad} onChange={e=>slotChange(s.sucursal,i,"capacidad",e.target.value)}/></td><td><select required aria-label={`Estado franja ${i+1} de ${branchName(s.sucursal)}`} value={f.habilitada} onChange={e=>slotChange(s.sucursal,i,"habilitada",e.target.value)}><option value="">Elegir estado</option><option value="SI">Habilitada</option><option value="NO">Deshabilitada</option></select></td><td><button type="button" className="admin-button secondary" onClick={()=>change("sucursales",form.sucursales.map(row=>row.sucursal===s.sucursal?{...row,franjas:row.franjas.filter((_,j)=>j!==i)}:row))}>Quitar franja {i+1}</button></td></tr>)}</tbody></table></div>
      {s.franjas.length===0&&<p className="admin-empty">Todavía no hay franjas para esta sucursal.</p>}<button type="button" className="admin-button secondary" onClick={()=>change("sucursales",form.sucursales.map(row=>row.sucursal===s.sucursal?{...row,franjas:[...row.franjas,{dia:"",apertura:"",cierre:"",capacidad:"",habilitada:""}]}:row))}>Agregar franja de {branchName(s.sucursal)}</button><p className="admin-note">Las franjas no pueden superponerse para el mismo día y origen. Cupo cero no permite reservas; no representa cupo ilimitado.</p></section>)}
      </section></fieldset><div className="configuration-actions"><button type="button" className="admin-button secondary" disabled={locked} onClick={()=>{if(!confirmNavigation())return;setEditor(null);setConflict(false);setLatest(null);setError("");}}>Volver a la lista de puntos</button><button className="admin-button" disabled={locked||loading||!!loadError||conflict}>Guardar punto</button></div>
    </form>}
    {error&&<p className="admin-warning" role="alert">{error}</p>}{uncertain&&<div className="admin-warning"><p>La respuesta no se pudo confirmar. Conservamos el comando para recuperar el guardado sin duplicarlo.</p><button type="button" className="admin-button" disabled={busy} onClick={()=>send()}>Reintentar la misma operación</button></div>}
    {conflict&&<div className="admin-warning"><p>El borrador cambió. Tus datos permanecen en el formulario.</p><button type="button" className="admin-button secondary" disabled={locked} onClick={consult}>Consultar puntos guardados</button></div>}
    {latest&&<section className="admin-card"><h3>Edición actual {latest.version}</h3><p>{latest.entrega.puntos.length} puntos guardados. Revisá antes de volver a guardar tus cambios.</p><div className="configuration-actions"><button type="button" className="admin-button secondary" disabled={locked} onClick={adopt}>Usar edición actual conservando mis datos</button><button type="button" className="admin-button secondary" disabled={locked} onClick={()=>{if(confirmNavigation())onSaved(latest);}}>Cargar el estado guardado</button></div></section>}
    <div className="configuration-actions"><button type="button" className="admin-button secondary" disabled={locked} onClick={onBack}>Volver a horarios y entrega</button><button type="button" className="admin-button secondary" disabled={locked||loading} onClick={load}>Actualizar sucursales</button></div>
  </>;
}
