"use client";
import {useEffect,useRef,useState,type FormEvent} from "react";
import {secureMutation,MutationError} from "@/lib/secure-mutation";
import {catalogDate} from "@/lib/catalog-types";
import {modelLabels,criterionLabels} from "@/lib/configuration-types";
import {HistoryValues,historySummary} from "@/components/configuration-history-values";
import {type Value} from "@/lib/configuration-history-types";
import {isRollbackReview,isRollbackResult,type RollbackReview,type RollbackResult} from "@/lib/configuration-rollback-types";
const root="/api/admin/configuracion/rollback";
const phases=["Configuración actual","Modelo operativo y aprobación","Pagos y reglas de seña","Recursos y asignación","Horarios y entrega","Resumen y simulación","Aplicación y seguridad","Historial de versiones"];
type Receipt={operacion:string;vencimiento:string};
type Decision={activa:string;objetivo:string;versionObjetivo:number;programada:string|null;revisionComercial:string;huellaRevision:string;advertenciasRevisadas:boolean;cancelarProgramacion:boolean;motivo:string};
export function ConfigurationRollback(){
 const[review,setReview]=useState<RollbackReview|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[uncertain,setUncertain]=useState(false),[error,setError]=useState(""),[conflict,setConflict]=useState(false);
 const[step,setStep]=useState<"review"|"security">("review"),[ack,setAck]=useState(false),[cancelAck,setCancelAck]=useState(false),[reason,setReason]=useState(""),[password,setPassword]=useState(""),[code,setCode]=useState(""),[receipt,setReceipt]=useState<Receipt|null>(null),[decision,setDecision]=useState<Decision|null>(null),[result,setResult]=useState<RollbackResult|null>(null);
 const operation=useRef<string|null>(null),command=useRef<{path:string;body:string;action:"solicitar"|"confirmar"|"revocar";next?:"review"|"home"}|null>(null);
 const locked=loading||busy||uncertain,navigationLocked=locked||step==="security"&&!result;
 async function refresh(){setLoading(true);setError("");setAck(false);setCancelAck(false);try{const r=await fetch(root+"/revision",{cache:"no-store"}),data:unknown=await r.json();if(!r.ok||!isRollbackReview(data))throw new Error(r.status===403?"La reversión requiere al propietario activo de la imprenta.":"No pudimos consultar las condiciones de reversión. Volvé a intentarlo.");setReview(data);setConflict(false);}catch(e){setError(e instanceof Error?e.message:"No pudimos consultar.");setConflict(true);}finally{setLoading(false);}}
 useEffect(()=>{void refresh();},[]);
 function continueReview(e:FormEvent){e.preventDefault();if(!review?.permitida||!review.activa||!review.objetivo||!review.condiciones?.catalogo.actual||!ack||review.programada&&!cancelAck||!reason.trim()||locked||conflict)return;setDecision({activa:review.activa.configuracion.codigoPublico,objetivo:review.objetivo.configuracion.codigoPublico,versionObjetivo:review.objetivo.configuracion.version,programada:review.programada?.configuracion.codigoPublico??null,revisionComercial:review.condiciones.catalogo.actual.codigoPublico,huellaRevision:review.huella,advertenciasRevisadas:ack,cancelarProgramacion:!!review.programada&&cancelAck,motivo:reason.trim()});setStep("security");setError("");}
 async function send(action?:"solicitar"|"confirmar",e?:FormEvent){
  e?.preventDefault();if(busy||action&&(!decision||uncertain))return;
  if(action){operation.current??=crypto.randomUUID();command.current={path:root+"/"+action,action,body:JSON.stringify({operacion:operation.current,decision,contrasena:password,...(action==="confirmar"?{codigo:code}:{})})};}
  const c=command.current;if(!c)return;setBusy(true);setError("");
  try{const response=await secureMutation(c.path,c.body,"application/json","POST"),data:unknown=await response.json();
   if(c.action==="solicitar"){const d=data as Partial<Receipt>|null;if(!d||d.operacion!==operation.current||typeof d.vencimiento!=="string")throw new Error("No pudimos verificar el envío del código.");setReceipt({operacion:d.operacion,vencimiento:d.vencimiento});}
   else if(c.action==="confirmar"){if(!isRollbackResult(data)||data.intento.configuracion!==decision?.objetivo)throw new Error("No pudimos verificar el resultado de la reversión.");setResult(data);setPassword("");setCode("");setReceipt(null);operation.current=null;}
   else{if(typeof data!=="object"||data===null||!("mensaje" in data))throw new Error("No pudimos confirmar la revocación.");operation.current=null;setReceipt(null);setPassword("");setCode("");setDecision(null);setStep("review");setConflict(false);if(c.next==="home")location.assign("/administracion/configuracion");else await refresh();}
   command.current=null;setUncertain(false);
  }catch(e){setError(e instanceof Error?e.message:"No pudimos completar la operación.");if(e instanceof MutationError&&!e.uncertain){command.current=null;setUncertain(false);if(e.status===409)setConflict(true);}else setUncertain(true);}finally{setBusy(false);}
 }
 async function leave(next:"review"|"home"){if(locked)return;if(operation.current&&decision){command.current={path:root+"/revocar",action:"revocar",next,body:JSON.stringify({operacion:operation.current,objetivo:decision.objetivo})};await send();}else if(next==="home")location.assign("/administracion/configuracion");else{setStep("review");setDecision(null);setPassword("");setCode("");await refresh();}}
 const b=review?.objetivo?.configuracion,refs:Record<string,string>={};review?.condiciones?.sucursales.forEach(s=>refs[s.codigoPublico]=s.nombre);review?.condiciones?.catalogo.servicios.forEach(s=>refs[s.codigoPublico]=s.nombre);review?.condiciones?.catalogo.formatos.forEach(f=>refs[f.codigoPublico]=f.nombre);
 const modules:{code:string;title:string;value:Value}[]=b?[{code:"modelo",title:"Modelo operativo y aprobación",value:{modelo:b.modelo,criterio:b.criterio}},{code:"pagos",title:"Pagos y reglas de seña",value:b.pagos as Value},{code:"recursos",title:"Recursos y asignación",value:b.recursos as Value},{code:"horarios",title:"Horarios y tiempos",value:{preparacionHoras:b.entrega.preparacionHoras,trasladoHoras:b.entrega.trasladoHoras,horariosPorSucursal:b.entrega.horariosPorSucursal} as Value},{code:"entrega",title:"Modalidades, puntos y zonas",value:{modalidades:b.entrega.modalidades,puntos:b.entrega.puntos,zonas:b.entrega.zonas} as Value}]:[];
 return <div className="configuration-layout"><aside className="configuration-steps"><h2>Flujo de configuración</h2><p>Reversión · Aplicación y seguridad</p><nav aria-label="Fases del configurador">{phases.map((label,i)=><button key={i} disabled={navigationLocked||i>0&&i<7} aria-current={i===6?"step":undefined} onClick={()=>location.assign(i===7?"/administracion/configuracion/historial":"/administracion/configuracion")}><span>{String(i+1).padStart(2,"0")}</span><span>{label}</span></button>)}</nav></aside><div className="configuration-body rollback-review">
 {result?<><h2>Reversión manual · Resultado</h2><section className={`admin-card ${result.estado==="EXITOSO"?"activation-success":""}`}>{result.version?<><div className="activation-check" aria-hidden="true">✓</div><h3>V{result.version.configuracion.numero} se publicó mediante reversión</h3><p>Se recuperaron los parámetros de V{result.version.configuracion.copia!.numeroOrigen} como una nueva versión.</p><p>{result.version.configuracion.estado==="ACTIVA"?"Esta configuración está activa.":"Esta configuración ya fue reemplazada y permanece en el historial."}</p><p>Vigencia desde {catalogDate(result.version.activadaEn)} · {result.version.activador}</p>{result.programacionCancelada&&<p className="admin-info">La programación V{result.programacionCancelada.numero} quedó cancelada en la misma operación.</p>}</>:<><h3>{result.estado==="INICIADO"?"La reversión sigue en curso":result.estado==="INTERRUMPIDO"?"La reversión fue interrumpida":"No se pudo publicar la reversión"}</h3><p className="admin-warning">{result.intento.detalle}</p><p>La misma operación recupera este resultado. Para otro intento, consultá el estado y autorizá nuevamente.</p></>}<p className="admin-note">La reversión sólo recupera configuración operativa y conserva los precios comerciales actuales. El recorrido de pedidos y pagos está En construcción.</p><div className="configuration-actions"><a className="admin-button" href="/administracion/configuracion">Ver configuración actual</a><a className="admin-button secondary" href="/administracion/configuracion/historial">Ver historial de versiones</a></div></section></>:step==="review"?<>
 <h2>Reversión manual · Revisar configuración anterior</h2><p className="admin-note">Se recupera la predecesora que realmente estuvo activa. Se publicará con un nuevo número de versión; las versiones anteriores conservarán su historia.</p><button className="admin-button secondary" disabled={locked} onClick={refresh}>Actualizar revisión de reversión</button>{loading&&<p role="status">Consultando condiciones actuales…</p>}
 {review?.impedimentos.map(text=><p className="admin-warning" key={text}>{text}</p>)}
 {b&&review?.activa&&<><div className="rollback-summary"><section className="admin-card"><small>CONFIGURACIÓN VIGENTE</small><h3>V{review.activa.configuracion.numero} · Activa</h3><p>{review.activa.configuracion.modelo&&modelLabels[review.activa.configuracion.modelo]}</p><p>Quedará histórica si la reversión tiene éxito.</p></section><section className="admin-card"><small>CONTENIDO A RECUPERAR</small><h3>V{b.numero} · Predecesora efectiva</h3><p>{b.modelo&&modelLabels[b.modelo]}{b.criterio&&` · ${criterionLabels[b.criterio]}`}</p><p>Se copiará a una nueva versión con vigencia desde su publicación.</p></section></div><section className="admin-card"><h3>Parámetros que se recuperarán</h3>{modules.map(m=><details key={m.code}><summary>{m.title} · {historySummary(m.code,m.value)}</summary><HistoryValues value={m.value} refs={refs}/></details>)}</section></>}
 {review?.programada&&<section className="admin-card"><h3>Programación que se cancelaría</h3><p>V{review.programada.configuracion.numero} · {catalogDate(review.programada.previstaEn)}</p><p>La programación y sus reintentos se cancelarán únicamente si la nueva versión se publica completamente. Si la reversión falla, conservarán su estado.</p></section>}
 {review?.condiciones&&<section className="admin-card"><h3>Comprobación de condiciones actuales</h3><p>{review.condiciones.bloqueos} bloqueos · {review.condiciones.advertencias} advertencias</p>{review.condiciones.hallazgos.filter(h=>h.nivel!=="INFORMACION").map((h,i)=><p className={h.nivel==="BLOQUEO"?"admin-warning":"admin-info"} key={i}>{h.mensaje}</p>)}<p>Se usará el catálogo comercial vigente, revisión {review.condiciones.catalogo.actual?.numero??"no disponible"}. Los precios históricos y la disponibilidad física anterior no se restauran.</p>{review.condiciones.bloqueos>0&&<p className="admin-note">Corregí las condiciones externas o usá la histórica como base de un borrador para modificar sus parámetros.</p>}</section>}
 <form className="admin-form" onSubmit={continueReview}><fieldset className="admin-fieldset" disabled={locked||conflict||!review?.permitida}><label>Motivo de reversión<textarea required maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></label><label className="admin-check rollback-confirm"><input type="checkbox" required checked={ack} onChange={e=>setAck(e.target.checked)}/><span>Revisé las condiciones y advertencias. Confirmo recuperar los parámetros indicados como una nueva versión.</span></label>{review?.programada&&<label className="admin-check rollback-confirm"><input type="checkbox" required checked={cancelAck} onChange={e=>setCancelAck(e.target.checked)}/><span>Confirmo cancelar la programación V{review.programada.configuracion.numero} si la reversión tiene éxito.</span></label>}<button className="admin-button" disabled={!ack||!!review?.programada&&!cancelAck}>Continuar con reversión</button></fieldset><div className="configuration-actions"><a className="admin-button secondary" href={locked?undefined:"/administracion/configuracion"}>Volver a configuración actual</a></div></form>
 </>:<><h2>Reversión manual · Verificación de seguridad</h2><section className="admin-card"><h3>Confirmar la recuperación</h3><p>Recuperar V{b?.numero} como nueva versión y reemplazar V{review?.activa?.configuracion.numero}.</p>{review?.programada&&<p className="admin-warning">También se cancelará V{review.programada.configuracion.numero}, programada para {catalogDate(review.programada.previstaEn)}.</p>}<p>Motivo: {decision?.motivo}</p><form className="admin-form" onSubmit={e=>void send(receipt?"confirmar":"solicitar",e)}><fieldset className="admin-fieldset" disabled={locked}><label>Tu contraseña actual<input type="password" required autoComplete="current-password" maxLength={128} value={password} onChange={e=>setPassword(e.target.value)}/></label>{receipt&&<><p className="admin-info">Código enviado por correo. Abrí Mailpit para copiarlo; vence el {catalogDate(receipt.vencimiento)}.</p><label>Código de reversión recibido<input required autoComplete="one-time-code" maxLength={200} value={code} onChange={e=>setCode(e.target.value)}/></label></>}</fieldset>{!uncertain&&<div className="configuration-actions"><button type="button" className="admin-button secondary" disabled={busy} onClick={()=>void leave("review")}>Cancelar autorización y revisar</button><button className="admin-button" disabled={busy||conflict}>{busy?"Procesando…":receipt?"Confirmar reversión":"Enviar código de reversión"}</button><button type="button" className="admin-button secondary" disabled={busy} onClick={()=>void leave("home")}>Salir conservando configuración</button></div>}</form><p className="admin-note">Se revalidan permisos, configuración vigente, programación y condiciones. Un código de activación normal no autoriza esta reversión.</p></section></>}
 {error&&<p className="admin-warning" role="alert">{error}</p>}{uncertain&&<div className="admin-warning"><p>No pudimos confirmar la respuesta. Conservamos la misma operación para recuperar el resultado sin duplicarla.</p><button className="admin-button" disabled={busy} onClick={()=>void send()}>Reintentar la misma operación</button></div>}{conflict&&step==="security"&&!result&&<p className="admin-note">Consultá las condiciones actuales antes de solicitar una nueva autorización.</p>}
 </div></div>;
}
