"use client";
import {useEffect,useRef,useState,type FormEvent} from "react";
import {MutationError,secureMutation} from "@/lib/secure-mutation";
import {isConfigurationDraft,isConfigurationState,type ConfigurationDraft,type ConfiguredPrinter} from "@/lib/configuration-types";
import {isCatalogState,type CatalogState} from "@/lib/catalog-types";
import {isBranch,type Branch} from "@/lib/organization-types";

type PrinterForm={sucursal:string;nombre:string;formatos:string[];color:string;duplex:string;capacity:string;state:string};
type Command={path:string;method:"POST"|"PUT";body:string};
const emptyPrinter:PrinterForm={sucursal:"",nombre:"",formatos:[],color:"",duplex:"",capacity:"",state:""};
const printerLabels={OPERATIVA:"Operativa",DESHABILITADA:"Deshabilitada",RETIRADA:"Retirada"};
function serviceMap(draft:ConfigurationDraft){return Object.fromEntries(draft.recursos.serviciosPorSucursal.map(row=>[row.sucursal,row.servicios]));}

export function ConfigurationResources({draft,onSaved,onBack,onLockChange,onNext}:{draft:ConfigurationDraft;onSaved:(value:ConfigurationDraft)=>void;onBack:()=>void;onNext:()=>void;onLockChange:(locked:boolean)=>void}){
  const [current,setCurrent]=useState(draft),[branches,setBranches]=useState<Branch[]>([]),[catalog,setCatalog]=useState<CatalogState|null>(null),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState("");
  const [method,setMethod]=useState(draft.recursos.metodoAsignacion??""),[services,setServices]=useState<Record<string,string[]>>(()=>serviceMap(draft));
  const [editor,setEditor]=useState<"NEW"|ConfiguredPrinter|null>(null),[form,setForm]=useState<PrinterForm>(emptyPrinter),[action,setAction]=useState<{printer:ConfiguredPrinter;kind:"STATE"|"RETIRE"}|null>(null),[reason,setReason]=useState("");
  const [busy,setBusy]=useState(false),[uncertain,setUncertain]=useState(false),[error,setError]=useState(""),[conflict,setConflict]=useState(false),[latest,setLatest]=useState<ConfigurationDraft|null>(null),[showRetired,setShowRetired]=useState(false);
  const command=useRef<Command|null>(null),locked=busy||uncertain;const base=`/api/admin/configuracion/borradores/${draft.codigoPublico}`;
  useEffect(()=>{onLockChange(locked);return()=>onLockChange(false);},[locked,onLockChange]);
  async function loadOptions(){setLoading(true);setLoadError("");try{
    const responses=await Promise.all([fetch("/api/admin/sucursales",{cache:"no-store"}),fetch("/api/admin/catalogo",{cache:"no-store"})]);
    const [b,c]:unknown[]=await Promise.all(responses.map(r=>r.json()));
    if(!responses.every(r=>r.ok)||!Array.isArray(b)||!b.every(isBranch)||!isCatalogState(c))throw new Error("No pudimos consultar las sucursales y el catálogo.");
    setBranches(b);setCatalog(c);
  }catch(cause){setLoadError(cause instanceof Error?cause.message:"No pudimos cargar las opciones.");}finally{setLoading(false);}}
  useEffect(()=>{void loadOptions();},[]);
  const resourcesDirty=method!==(current.recursos.metodoAsignacion??"")||JSON.stringify(services)!==JSON.stringify(serviceMap(current));
  function branchName(id:string){return branches.find(b=>b.codigoPublico===id)?.nombre??id;}
  function change<K extends keyof PrinterForm>(key:K,value:PrinterForm[K]){setForm(f=>({...f,[key]:value}));}
  function openEditor(printer?:ConfiguredPrinter){setError("");setAction(null);setReason("");setEditor(printer??"NEW");setForm(printer?{sucursal:printer.sucursal,nombre:printer.nombre,formatos:printer.formatos,color:printer.admiteColor?"COLOR":"BN",duplex:printer.admiteDobleFaz?"SI":"NO",capacity:String(printer.capacidadHojas),state:printer.estado}:{...emptyPrinter});}
  async function send(next?:Command){if(busy)return;setBusy(true);setError("");if(next)command.current=next;
    try{if(!command.current)throw new Error("No hay una solicitud pendiente.");const c=command.current;const response=await secureMutation(c.path,c.body,"application/json",c.method);const data:unknown=await response.json();if(!isConfigurationDraft(data))throw new Error("No pudimos confirmar los recursos recibidos.");command.current=null;setUncertain(false);onSaved(data);}
    catch(cause){setError(cause instanceof Error?cause.message:"No pudimos guardar los recursos.");if(cause instanceof MutationError&&!cause.uncertain){command.current=null;setUncertain(false);setConflict(cause.status===409);}else if(command.current)setUncertain(true);}finally{setBusy(false);}}
  function mutate(path:string,method:"POST"|"PUT",fields:Record<string,unknown>){if(locked||conflict)return;void send({path:base+path,method,body:JSON.stringify({operacion:crypto.randomUUID(),version:current.version,...fields})});}
  function saveResources(event:FormEvent){event.preventDefault();mutate("/recursos","PUT",{metodoAsignacion:method,serviciosPorSucursal:Object.entries(services).filter(([,ids])=>ids.length>0).map(([sucursal,servicios])=>({sucursal,servicios}))});}
  function savePrinter(event:FormEvent){event.preventDefault();if(!form.formatos.length){setError("Seleccioná al menos un formato compatible.");return;}const fields={nombre:form.nombre.trim(),formatos:form.formatos,admiteColor:form.color==="COLOR",admiteDobleFaz:form.duplex==="SI",capacidadHojas:Number(form.capacity)};
    if(editor==="NEW")mutate("/impresoras","POST",{...fields,sucursal:form.sucursal,estado:form.state});else if(editor)mutate(`/impresoras/${editor.codigoPublico}`,"PUT",fields);}
  function saveAction(event:FormEvent){event.preventDefault();if(!action)return;mutate(`/impresoras/${action.printer.codigoPublico}/${action.kind==="RETIRE"?"retirar":"estado"}`,"POST",{motivo:reason.trim(),...(action.kind==="STATE"?{estado:action.printer.estado==="OPERATIVA"?"DESHABILITADA":"OPERATIVA"}:{})});}
  async function consult(){setBusy(true);setError("");try{const r=await fetch("/api/admin/configuracion",{cache:"no-store"});const data:unknown=await r.json();if(!r.ok||!isConfigurationState(data))throw new Error("No pudimos consultar el borrador.");if(!data.borrador)throw new Error("El borrador ya no está en preparación. Recargá la página para consultar su historial.");setLatest(data.borrador);}catch(cause){setError(cause instanceof Error?cause.message:"No pudimos consultar el borrador.");}finally{setBusy(false);}}
  function adopt(){if(!latest)return;if(latest.codigoPublico!==draft.codigoPublico){onSaved(latest);return;}
    if(editor&&editor!=="NEW"){const found=latest.recursos.impresoras.find(p=>p.codigoPublico===editor.codigoPublico);if(!found||found.estado!=="DESHABILITADA"){setError("Esta impresora ya no se puede editar. Cargá el estado guardado para continuar.");return;}setEditor(found);}
    if(action){const found=latest.recursos.impresoras.find(p=>p.codigoPublico===action.printer.codigoPublico);if(!found||found.estado!==action.printer.estado){setError("Cambió el estado de esta impresora. Cargá el estado guardado para continuar.");return;}setAction({...action,printer:found});}
    setCurrent(latest);setConflict(false);setLatest(null);setError("");}
  const printerList=current.recursos.impresoras.filter(p=>showRetired||p.estado!=="RETIRADA");
  return <>
    <h2>Fase 4 · Recursos y asignación</h2><p className="admin-note">Borrador {draft.numero} · Editando versión {current.version}. Los estados son previstos para esta configuración; todavía no están activos.</p>
    <div className="resource-toolbar"><p>Declaraciones manuales de equipos y servicios por sucursal.</p><button type="button" className="admin-button secondary" disabled={locked||loading} onClick={loadOptions}>Actualizar sucursales y catálogo</button></div>
    {loading&&<p role="status">Cargando opciones…</p>}{loadError&&<p className="admin-warning" role="alert">{loadError}</p>}
    <p className="admin-note">Creá formatos y servicios en <a href={locked?undefined:"/administracion/catalogo"} target="_blank" rel="noopener noreferrer">Servicios y precios (otra pestaña)</a> y volvé a actualizar las opciones. Las <a href={locked?undefined:"/administracion/sucursales"} target="_blank" rel="noopener noreferrer">sucursales (otra pestaña)</a> se administran por separado.</p>
    {!editor?<>
      <section className="admin-card"><div className="resource-toolbar"><h3>Impresoras y capacidades</h3><button type="button" className="admin-button" disabled={locked||loading||!!loadError||resourcesDirty||conflict||!!action||!catalog?.formatos.length||!branches.some(b=>b.estado==="ACTIVA")} onClick={()=>openEditor()}>Agregar impresora</button></div>
        {(!catalog?.formatos.length||!branches.some(b=>b.estado==="ACTIVA"))&&<p className="admin-info">Para dar de alta una impresora, creá al menos una sucursal activa y un formato en el catálogo.</p>}
        {resourcesDirty&&<p className="admin-info">Guardá el método y los servicios seleccionados antes de modificar impresoras.</p>}
        {printerList.length===0?<p className="admin-empty">No hay impresoras declaradas en este borrador.</p>:<div className="admin-table-wrap" tabIndex={0} aria-label="Impresoras configuradas"><table className="admin-table resource-table"><thead><tr><th>Impresora / Sucursal</th><th>Estado previsto</th><th>Formatos</th><th>Color</th><th>Doble faz</th><th>Capacidad</th><th>Papel / histórico</th><th>Acciones</th></tr></thead><tbody>{printerList.map(p=><tr key={p.codigoPublico}><td><strong>{p.nombre}</strong><small>{branchName(p.sucursal)}</small></td><td><span className={`resource-state ${p.estado.toLowerCase()}`}>{printerLabels[p.estado]}</span></td><td>{p.formatos.map(id=>catalog?.formatos.find(f=>f.codigoPublico===id)?.nombre??id).join(", ")}</td><td>{p.admiteColor?"B/N y color":"B/N"}</td><td>{p.admiteDobleFaz?"Sí":"No"}</td><td>{p.capacidadHojas} hojas</td><td>Sin lectura<small>Telemetría CUPS en construcción</small></td><td><div className="resource-row-actions">{p.estado==="DESHABILITADA"&&<button type="button" className="admin-button secondary" disabled={locked||resourcesDirty||conflict||!!action} onClick={()=>openEditor(p)}>Editar {p.nombre}</button>}{p.estado!=="RETIRADA"&&<button type="button" className="admin-button secondary" disabled={locked||resourcesDirty||conflict||!!action} onClick={()=>{setAction({printer:p,kind:"STATE"});setReason("");setError("");}}>{p.estado==="OPERATIVA"?"Deshabilitar":"Habilitar"} {p.nombre}</button>}{p.estado==="RETIRADA"&&<small>{p.motivoRetiro}</small>}</div></td></tr>)}</tbody></table></div>}
        {current.recursos.impresoras.some(p=>p.estado==="RETIRADA")&&<label className="admin-check"><input type="checkbox" checked={showRetired} disabled={locked} onChange={e=>setShowRetired(e.target.checked)}/>Mostrar impresoras retiradas</label>}
      </section>
      <form className="admin-form admin-card resource-services" onSubmit={saveResources}><fieldset className="admin-fieldset" disabled={locked||loading||!!loadError||!!action}>
        <h3>Método de asignación</h3><label className="admin-check"><input type="radio" name="assignment" required checked={method==="MANUAL"} onChange={()=>setMethod("MANUAL")}/>Asignación manual</label><p className="admin-note">El personal elegirá la impresora compatible al organizar el trabajo.</p><label className="admin-check"><input type="radio" disabled/>Asignación automática · En construcción</label>
        <h3>Servicios habilitados por sucursal</h3><p className="admin-note">Elegí los servicios que podrá ofrecer cada sucursal. Sus precios y compatibilidades pertenecen al catálogo comercial.</p>
        {branches.length===0?<p className="admin-empty">Todavía no hay sucursales.</p>:branches.map(b=><section className="resource-branch" key={b.codigoPublico}><h4>{b.nombre}{b.estado!=="ACTIVA"&&" · Desactivada"}</h4>{!catalog?.servicios.length?<p>No hay servicios en el catálogo.</p>:catalog.servicios.map(s=><label className="admin-check" key={s.codigoPublico}><input type="checkbox" checked={(services[b.codigoPublico]??[]).includes(s.codigoPublico)} disabled={b.estado!=="ACTIVA"&&!(current.recursos.serviciosPorSucursal.find(row=>row.sucursal===b.codigoPublico)?.servicios??[]).includes(s.codigoPublico)} onChange={e=>setServices(v=>({...v,[b.codigoPublico]:e.target.checked?[...(v[b.codigoPublico]??[]),s.codigoPublico]:(v[b.codigoPublico]??[]).filter(id=>id!==s.codigoPublico)}))}/>{s.nombre} · {s.tipo==="IMPRESION"?"Impresión":"Terminación"}</label>)}</section>)}
      </fieldset><button className="admin-button" disabled={locked||loading||!!loadError||!!action||conflict}>Guardar asignación y servicios</button></form>
    </>:<section className="admin-card resource-editor"><h3>{editor==="NEW"?"Agregar impresora":`Editar impresora · ${editor.nombre}`}</h3>
      {editor!=="NEW"&&<><p className="admin-info">Deshabilitada en este borrador. La sucursal y la identidad técnica se conservan.</p></>}
      <div className="resource-edit-grid"><form className="admin-form" onSubmit={savePrinter}><fieldset className="admin-fieldset" disabled={locked||!!action||conflict}><div className="admin-form-grid">
        <label>Nombre de la impresora<input required maxLength={120} value={form.nombre} onChange={e=>change("nombre",e.target.value)}/></label>
        {editor==="NEW"&&<div className="catalog-field"><label htmlFor="resource-branch">Sucursal de la impresora</label><select id="resource-branch" required value={form.sucursal} onChange={e=>change("sucursal",e.target.value)}><option value="">Elegir sucursal</option>{branches.filter(b=>b.estado==="ACTIVA").map(b=><option key={b.codigoPublico} value={b.codigoPublico}>{b.nombre}</option>)}</select></div>}
        <div className="catalog-field"><label htmlFor="resource-color">Modo de color</label><select id="resource-color" required value={form.color} onChange={e=>change("color",e.target.value)}><option value="">Elegir capacidad</option><option value="BN">Blanco y negro</option><option value="COLOR">Blanco y negro y color</option></select></div>
        <div className="catalog-field"><label htmlFor="resource-duplex">Admite doble faz</label><select id="resource-duplex" required value={form.duplex} onChange={e=>change("duplex",e.target.value)}><option value="">Elegir capacidad</option><option value="SI">Sí</option><option value="NO">No</option></select></div>
        <label>Capacidad máxima de hojas<input type="number" min="1" max="2147483647" step="1" required value={form.capacity} onChange={e=>change("capacity",e.target.value)}/></label>
        {editor==="NEW"&&<div className="catalog-field"><label htmlFor="resource-state">Estado previsto inicial</label><select id="resource-state" required value={form.state} onChange={e=>change("state",e.target.value)}><option value="">Elegir estado</option><option value="DESHABILITADA">Deshabilitada</option><option value="OPERATIVA">Operativa</option></select></div>}
      </div><fieldset className="resource-formats"><legend>Formatos compatibles</legend>{catalog?.formatos.map(f=><label className="admin-check" key={f.codigoPublico}><input type="checkbox" checked={form.formatos.includes(f.codigoPublico)} onChange={e=>change("formatos",e.target.checked?[...form.formatos,f.codigoPublico]:form.formatos.filter(id=>id!==f.codigoPublico))}/>{f.nombre}</label>)}</fieldset></fieldset>
        <div className="configuration-actions"><button type="button" className="admin-button secondary" disabled={locked||!!action} onClick={()=>{setEditor(null);setError("");}}>Volver a la lista</button><button className="admin-button" disabled={locked||!!action||conflict}>Guardar impresora</button></div>
      </form><aside className="resource-details"><h4>Información de la impresora</h4><dl><dt>Identidad técnica</dt><dd className="resource-identity">{editor==="NEW"?"Se asignará al guardar":editor.codigoPublico}</dd><dt>Sucursal</dt><dd>{form.sucursal?branchName(form.sucursal):"Sin seleccionar"}</dd><dt>Histórico de impresión</dt><dd>Sin registro</dd><dt>Disponibilidad estimada de papel</dt><dd>Sin registro</dd></dl><p className="admin-info">La capacidad se declara manualmente. Las recargas y las lecturas de sensores están En construcción. Los trabajos manuales y sus controles de calidad se registran desde cada pedido.</p></aside></div>
      {editor!=="NEW"&&<div className="resource-danger"><h4>Retirar impresora del borrador</h4><p>La impresora deshabilitada dejará de estar disponible en esta configuración. Su identidad e historial se conservan.</p><button type="button" className="admin-button secondary" disabled={locked||!!action||conflict} onClick={()=>{setAction({printer:editor,kind:"RETIRE"});setReason("");}}>Retirar impresora</button></div>}
    </section>}
    {action&&<form className="admin-form admin-card resource-action" onSubmit={saveAction}><h3>{action.kind==="RETIRE"?"Confirmar retiro":action.printer.estado==="OPERATIVA"?"Deshabilitar impresora":"Habilitar impresora"} · {action.printer.nombre}</h3><p>Este cambio afecta el estado previsto del borrador.</p><fieldset className="admin-fieldset" disabled={locked||conflict}><label>Motivo del cambio<input required maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></label></fieldset><div className="configuration-actions"><button type="button" className="admin-button secondary" disabled={locked} onClick={()=>setAction(null)}>Volver sin cambiar estado</button><button className="admin-button" disabled={locked||conflict}>Confirmar cambio de estado</button></div></form>}
    {error&&<p className="admin-warning" role="alert">{error}</p>}
    {uncertain&&<div className="admin-warning"><p>No pudimos confirmar la respuesta. Conservamos el comando y sus datos para evitar duplicados.</p><button type="button" className="admin-button" disabled={busy} onClick={()=>send()}>Reintentar la misma operación</button></div>}
    {conflict&&<div className="admin-warning"><p>El borrador cambió. Los datos de tu formulario se conservan.</p><button type="button" className="admin-button secondary" disabled={locked} onClick={consult}>Consultar recursos guardados</button></div>}
    {latest&&<section className="admin-card"><h3>Edición guardada {latest.version}</h3><p>{latest.recursos.impresoras.filter(p=>p.estado!=="RETIRADA").length} impresoras declaradas. Revisá los datos antes de volver a guardar.</p><div className="configuration-actions"><button type="button" className="admin-button secondary" disabled={locked} onClick={adopt}>Usar edición actual conservando mis datos</button><button type="button" className="admin-button secondary" disabled={locked} onClick={()=>onSaved(latest)}>Cargar el estado guardado</button></div></section>}
    <aside className="admin-card resource-notes"><h3>Consideraciones</h3><ul><li>Deshabilitá una impresora antes de editarla o retirarla. Retirar conserva el registro.</li><li>La capacidad máxima declarada no indica cuántas hojas quedan. Consultá los trabajos e inspecciones en el pedido correspondiente.</li><li>Recargas y existencias de papel: <strong>En construcción</strong>.</li><li>Conexión CUPS y lecturas de dispositivos: <strong>En construcción</strong>.</li></ul></aside>
    <div className="configuration-actions"><button type="button" className="admin-button secondary" disabled={locked} onClick={onBack}>Volver a pagos y reglas</button><button type="button" className="admin-button secondary" disabled={locked||resourcesDirty||!current.recursos.metodoAsignacion||!!editor||!!action||conflict} onClick={onNext}>Continuar a horarios y entrega</button></div>
  </>;
}
