"use client";
import {useEffect,useRef,useState,type FormEvent} from "react";
import {MutationError,secureMutation} from "@/lib/secure-mutation";
import {isConfigurationDraft,isConfigurationState,type ConfigurationDraft,type DeliveryMode,type OperatingDay,type BranchSchedule} from "@/lib/configuration-types";
import {isBranch,type Branch} from "@/lib/organization-types";
const days=["Lunes","Martes","Miércoles","Jueves","Viernes","Sábado","Domingo"];
const modes:Record<DeliveryMode,string>={RETIRO_SUCURSAL:"Retiro en local",RETIRO_PUNTO_ENTREGA:"Puntos de entrega",ENVIO_DOMICILIO:"Envío a domicilio"};
type PointOption={punto:string;sucursal:string;nombre:string;zonaHoraria:string;costo:string;versionDisponibilidad:number};
type Validation={version:number;valida:boolean;problemas:{codigo:string;sucursal:string|null;mensaje:string}[];avisos:string[];puntosDisponibles:PointOption[]};
type PointDestination={punto:string;nombre:string;zonaHoraria:string;costo:string;versionDisponibilidad:number;fecha:string;apertura:string;cierre:string;franjaDesde:string;franjaHasta:string;cupoConfigurado:number};
type ZoneDestination=Omit<PointDestination,"punto"|"versionDisponibilidad">&{zona:string;territorio:{codigoPostal:string;localidad:string;provincia:string}};
type Estimate={version:number;zonaHoraria:string;recibidoEn:string;inicioPreparacion:string;finPreparacion:string;llegadaEstimada:string|null;disponibleDesde:string|null;enCola:boolean;advertencias:string[];destinoPunto:PointDestination|null;destinoZona:ZoneDestination|null};
function record(v:unknown):v is Record<string,unknown>{return !!v&&typeof v==="object";}
function isValidation(v:unknown):v is Validation{return record(v)&&Number.isSafeInteger(v.version)&&typeof v.valida==="boolean"&&Array.isArray(v.avisos)&&v.avisos.every(a=>typeof a==="string")&&Array.isArray(v.puntosDisponibles)&&v.puntosDisponibles.every(p=>record(p)&&["punto","sucursal","nombre","zonaHoraria","costo"].every(k=>typeof p[k]==="string")&&Number.isSafeInteger(p.versionDisponibilidad))&&Array.isArray(v.problemas)&&v.problemas.every(p=>record(p)&&typeof p.codigo==="string"&&typeof p.mensaje==="string"&&(p.sucursal===null||typeof p.sucursal==="string"));}
function isDestination(v:unknown):v is PointDestination{return record(v)&&["punto","nombre","zonaHoraria","costo","fecha","apertura","cierre","franjaDesde","franjaHasta"].every(k=>typeof v[k]==="string")&&Number.isSafeInteger(v.versionDisponibilidad)&&Number.isSafeInteger(v.cupoConfigurado)&&Number(v.cupoConfigurado)>0;}
function isZoneDestination(v:unknown):v is ZoneDestination{return record(v)&&["zona","nombre","zonaHoraria","costo","fecha","apertura","cierre","franjaDesde","franjaHasta"].every(k=>typeof v[k]==="string")&&Number.isSafeInteger(v.cupoConfigurado)&&Number(v.cupoConfigurado)>0&&record(v.territorio)&&["codigoPostal","localidad","provincia"].every(k=>typeof (v.territorio as Record<string,unknown>)[k]==="string");}
function isEstimate(v:unknown):v is Estimate{return record(v)&&Number.isSafeInteger(v.version)&&["zonaHoraria","recibidoEn","inicioPreparacion","finPreparacion"].every(k=>typeof v[k]==="string")&&["llegadaEstimada","disponibleDesde"].every(k=>v[k]===null||typeof v[k]==="string")&&typeof v.enCola==="boolean"&&(v.destinoPunto===null||isDestination(v.destinoPunto))&&(v.destinoZona===null||isZoneDestination(v.destinoZona))&&Array.isArray(v.advertencias)&&v.advertencias.every(a=>typeof a==="string");}
function fullWeek(values:OperatingDay[]):OperatingDay[]{return days.map((_,i)=>values.find(d=>d.dia===i+1)??{dia:i+1,habilitado:null,apertura:null,cierre:null});}
function initialSchedules(draft:ConfigurationDraft){return draft.entrega.horariosPorSucursal.map(s=>({...s,dias:fullWeek(s.dias)}));}

export function ConfigurationDelivery({draft,onSaved,onBack,onLockChange,onPoints,onZones}:{draft:ConfigurationDraft;onSaved:(value:ConfigurationDraft)=>void;onBack:()=>void;onPoints:()=>void;onZones:()=>void;onLockChange:(value:boolean)=>void}){
  const [current,setCurrent]=useState(draft),[preparation,setPreparation]=useState(draft.entrega.preparacionHoras??""),[transfer,setTransfer]=useState(draft.entrega.trasladoHoras??""),[selectedModes,setModes]=useState<DeliveryMode[]>(draft.entrega.modalidades),[schedules,setSchedules]=useState<BranchSchedule[]>(()=>initialSchedules(draft));
  const [branches,setBranches]=useState<Branch[]>([]),[branchToAdd,setBranchToAdd]=useState(""),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState(""),[validation,setValidation]=useState<Validation|null>(null);
  const [busy,setBusy]=useState(false),[uncertain,setUncertain]=useState(false),[error,setError]=useState(""),[conflict,setConflict]=useState(false),[latest,setLatest]=useState<ConfigurationDraft|null>(null);
  const [territory,setTerritory]=useState({codigoPostal:"",localidad:"",provincia:""});
  const [simulationPoint,setSimulationPoint]=useState(""),[receipt,setReceipt]=useState(""),[simulationBranch,setSimulationBranch]=useState(""),[simulationMode,setSimulationMode]=useState(""),[estimate,setEstimate]=useState<Estimate|null>(null),[simulating,setSimulating]=useState(false),[simulationError,setSimulationError]=useState("");
  const command=useRef<string|null>(null),locked=busy||uncertain||simulating,base=`/api/admin/configuracion/borradores/${draft.codigoPublico}/entrega`;
  useEffect(()=>{onLockChange(locked);return()=>onLockChange(false);},[locked,onLockChange]);
  async function load(){setLoading(true);setLoadError("");clearEstimate();try{const [rb,rv]=await Promise.all([fetch("/api/admin/sucursales",{cache:"no-store"}),fetch(base+"/validacion",{cache:"no-store"})]);const [b,v]:unknown[]=await Promise.all([rb.json(),rv.json()]);if(!rb.ok||!rv.ok||!Array.isArray(b)||!b.every(isBranch)||!isValidation(v))throw new Error("No pudimos consultar las sucursales y la validación guardada.");setBranches(b);setValidation(v);setSimulationPoint(point=>v.puntosDisponibles.some(p=>p.punto===point&&p.sucursal===simulationBranch)?point:"");if(v.version!==current.version)setConflict(true);}catch(cause){setLoadError(cause instanceof Error?cause.message:"No pudimos consultar los horarios.");}finally{setLoading(false);}}
  useEffect(()=>{void load();},[]); // Initial state belongs to this draft edition; later refresh is explicit.
  const dirty=preparation!==(current.entrega.preparacionHoras??"")||transfer!==(current.entrega.trasladoHoras??"")||JSON.stringify(selectedModes)!==JSON.stringify(current.entrega.modalidades)||JSON.stringify(schedules)!==JSON.stringify(initialSchedules(current));
  const destination=estimate?.destinoPunto??estimate?.destinoZona;
  const pointOptions=validation?.puntosDisponibles.filter(p=>p.sucursal===simulationBranch)??[];
  function name(id:string){return branches.find(b=>b.codigoPublico===id)?.nombre??id;}
  function clearEstimate(){setEstimate(null);setSimulationError("");}
  function dayChange(branch:string,day:number,field:"habilitado"|"apertura"|"cierre",value:boolean|string|null){clearEstimate();setSchedules(rows=>rows.map(row=>row.sucursal!==branch?row:{...row,dias:row.dias.map(d=>d.dia!==day?d:field==="habilitado"?{...d,habilitado:value as boolean|null,...(value===true?{}:{apertura:null,cierre:null})}:{...d,[field]:value})}));}
  function addSchedule(){const branch=branches.find(b=>b.codigoPublico===branchToAdd);if(!branch||schedules.some(s=>s.sucursal===branch.codigoPublico))return;setSchedules(rows=>[...rows,{sucursal:branch.codigoPublico,zonaHoraria:current.entrega.horariosPorSucursal.find(s=>s.sucursal===branch.codigoPublico)?.zonaHoraria??branch.zonaHoraria,dias:fullWeek([])}]);setBranchToAdd("");clearEstimate();}
  async function save(event?:FormEvent){event?.preventDefault();if(busy)return;setBusy(true);setError("");try{if(!command.current)command.current=JSON.stringify({operacion:crypto.randomUUID(),version:current.version,preparacionHoras:preparation||null,trasladoHoras:transfer||null,modalidades:selectedModes,horariosPorSucursal:schedules.map(s=>({sucursal:s.sucursal,dias:s.dias}))});const r=await secureMutation(base,command.current,"application/json","PUT");const data:unknown=await r.json();if(!isConfigurationDraft(data))throw new Error("No pudimos confirmar los horarios recibidos.");command.current=null;setUncertain(false);onSaved(data);}catch(cause){setError(cause instanceof Error?cause.message:"No pudimos guardar los horarios.");if(cause instanceof MutationError&&!cause.uncertain){command.current=null;setUncertain(false);setConflict(cause.status===409);}else if(command.current)setUncertain(true);}finally{setBusy(false);}}
  async function consult(){setBusy(true);setError("");try{const [r,br]=await Promise.all([fetch("/api/admin/configuracion",{cache:"no-store"}),fetch("/api/admin/sucursales",{cache:"no-store"})]);const [data,b]:unknown[]=await Promise.all([r.json(),br.json()]);if(!r.ok||!br.ok||!Array.isArray(b)||!b.every(isBranch)||!isConfigurationState(data))throw new Error("No pudimos consultar el borrador.");if(!data.borrador)throw new Error("El borrador ya no está en preparación. Recargá la página para consultar su historial.");setBranches(b);setLatest(data.borrador);}catch(cause){setError(cause instanceof Error?cause.message:"No pudimos consultar el borrador.");}finally{setBusy(false);}}
  function adopt(){if(!latest)return;if(latest.codigoPublico!==draft.codigoPublico){onSaved(latest);return;}setSchedules(rows=>rows.map(row=>({...row,zonaHoraria:latest.entrega.horariosPorSucursal.find(s=>s.sucursal===row.sucursal)?.zonaHoraria??branches.find(b=>b.codigoPublico===row.sucursal)?.zonaHoraria??row.zonaHoraria})));setCurrent(latest);setConflict(false);setLatest(null);setValidation(null);setError("");clearEstimate();}
  async function simulate(event:FormEvent){event.preventDefault();if(locked||dirty||conflict)return;setSimulating(true);setEstimate(null);setSimulationError("");try{const r=await secureMutation(base+"/simular",JSON.stringify({version:current.version,sucursal:simulationBranch,modalidad:simulationMode,punto:simulationMode==="RETIRO_PUNTO_ENTREGA"?simulationPoint:null,territorio:simulationMode==="ENVIO_DOMICILIO"?territory:null,recibidoEn:new Date(receipt+":00Z").toISOString()}),"application/json","POST");const data:unknown=await r.json();if(!isEstimate(data)||data.version!==current.version)throw new Error("No pudimos confirmar la estimación recibida.");setEstimate(data);}catch(cause){setSimulationError(cause instanceof Error?cause.message:"No pudimos calcular la estimación.");if(cause instanceof MutationError&&cause.status===409){try{const r=await fetch(base+"/validacion",{cache:"no-store"});const v:unknown=await r.json();if(r.ok&&isValidation(v)){setValidation(v);setSimulationPoint(point=>v.puntosDisponibles.some(p=>p.punto===point&&p.sucursal===simulationBranch)?point:"");if(v.version!==current.version||v.problemas.some(p=>p.codigo==="BORRADOR_NO_EDITABLE"))setConflict(true);}}catch{/* Keep the original actionable simulation error. */}}}finally{setSimulating(false);}}
  function date(value:string|null,zone?:string){if(!value||!estimate)return "Sin disponibilidad confirmada";return new Intl.DateTimeFormat("es-AR",{dateStyle:"medium",timeStyle:zone?"long":"medium",hourCycle:"h23",timeZone:zone??estimate.zonaHoraria}).format(new Date(value));}
  return <>
    <h2>Fase 5 · Horarios, puntos de entrega y envíos</h2><p className="admin-note">Borrador {draft.numero} · Editando versión {current.version}. Los horarios habituales requieren una configuración activada para aplicarse.</p>
    <form className="admin-form" onSubmit={save}><fieldset className="admin-fieldset" disabled={locked||loading}>
      <div className="delivery-columns"><section className="admin-card delivery-calendar"><h3>Días y horario operativo</h3><p className="admin-note">Cada sucursal define sus siete días. Sin configurar y Cerrado son decisiones diferentes.</p>
        <div className="catalog-field"><label htmlFor="schedule-branch">Sucursal para configurar horarios</label><select id="schedule-branch" value={branchToAdd} onChange={e=>setBranchToAdd(e.target.value)}><option value="">Elegir sucursal</option>{branches.filter(b=>b.estado==="ACTIVA"&&!schedules.some(s=>s.sucursal===b.codigoPublico)).map(b=><option key={b.codigoPublico} value={b.codigoPublico}>{b.nombre}</option>)}</select></div><button type="button" className="admin-button secondary" disabled={!branchToAdd} onClick={addSchedule}>Agregar calendario</button>
        {schedules.length===0&&<p className="admin-empty">Todavía no se configuraron horarios.</p>}
        {schedules.map(s=><section className="delivery-branch" key={s.sucursal}><div className="resource-toolbar"><h4>{name(s.sucursal)}</h4><button type="button" className="admin-button secondary" onClick={()=>{setSchedules(rows=>rows.filter(r=>r.sucursal!==s.sucursal));clearEstimate();}}>Quitar calendario de {name(s.sucursal)}</button></div><p className="admin-note">Zona del calendario: <strong>{s.zonaHoraria}</strong>{branches.find(b=>b.codigoPublico===s.sucursal)?.estado==="DESACTIVADA"&&" · Sucursal desactivada"}</p>
          <div className="admin-table-wrap" tabIndex={0} aria-label={`Calendario de ${name(s.sucursal)}`}><table className="admin-table delivery-week"><thead><tr><th>Día</th><th>Estado</th><th>Apertura</th><th>Cierre</th></tr></thead><tbody>{s.dias.map(d=><tr key={d.dia}><th scope="row">{days[d.dia-1]}</th><td><select aria-label={`Estado ${days[d.dia-1]} de ${name(s.sucursal)}`} value={d.habilitado===null?"":d.habilitado?"ABIERTO":"CERRADO"} onChange={e=>dayChange(s.sucursal,d.dia,"habilitado",e.target.value===""?null:e.target.value==="ABIERTO")}><option value="">Sin configurar</option><option value="ABIERTO">Abierto</option><option value="CERRADO">Cerrado</option></select></td><td><input aria-label={`Apertura ${days[d.dia-1]} de ${name(s.sucursal)}`} type="time" step="60" disabled={d.habilitado!==true} value={d.apertura??""} onChange={e=>dayChange(s.sucursal,d.dia,"apertura",e.target.value||null)}/></td><td><input aria-label={`Cierre ${days[d.dia-1]} de ${name(s.sucursal)}`} type="time" step="60" disabled={d.habilitado!==true} value={d.cierre??""} onChange={e=>dayChange(s.sucursal,d.dia,"cierre",e.target.value||null)}/></td></tr>)}</tbody></table></div>
        </section>)}
      </section><section className="admin-card delivery-times"><h3>Tiempos estimados</h3><div className="catalog-field"><label htmlFor="preparation-hours">Tiempo estimado de preparación (horas)</label><input id="preparation-hours" type="number" min="0.01" max="10000" step="0.01" value={preparation} onChange={e=>{setPreparation(e.target.value);clearEstimate();}}/><small>Horas operativas necesarias para terminar el trabajo.</small></div><div className="catalog-field"><label htmlFor="transfer-hours">Tiempo adicional de traslado o envío (horas)</label><input id="transfer-hours" type="number" min="0" max="10000" step="0.01" value={transfer} onChange={e=>{setTransfer(e.target.value);clearEstimate();}}/><small>Se suma a preparación cuando el pedido sale hacia un punto o domicilio. Cero debe ingresarse expresamente.</small></div><p className="admin-info">Ambos tiempos se consumen dentro del horario operativo de la sucursal de origen. Fuera de horario, el cálculo continúa desde la próxima apertura.</p><p className="admin-note">Son estimaciones: no obligan a esperar si el pedido está listo antes. No garantizan el tiempo de un transportista externo.</p></section></div>
      <section className="admin-card delivery-modes"><h3>Modalidades de entrega</h3>{Object.entries(modes).map(([value,label])=><label className="admin-check" key={value}><input type="checkbox" checked={selectedModes.includes(value as DeliveryMode)} onChange={e=>{setModes(m=>e.target.checked?[...m,value as DeliveryMode]:m.filter(v=>v!==value));clearEstimate();}}/>{label}</label>)}<div className="configuration-actions"><button type="button" className="admin-button secondary" disabled={locked||dirty||conflict} onClick={onPoints}>Administrar puntos</button><button type="button" className="admin-button secondary" disabled={locked||dirty||conflict} onClick={onZones}>Administrar zonas y cupos</button></div><p className="admin-note">Seleccionar una modalidad prepara el borrador. Las definiciones de puntos se administran desde este borrador. Su disponibilidad diaria se gestiona desde el dashboard. Las zonas domiciliarias definen cobertura y cupos globales. La oferta al cliente y las reservas todavía están En construcción.</p></section>
    </fieldset>
    {loadError&&<p className="admin-warning" role="alert">{loadError}</p>}{loading&&<p role="status">Consultando calendarios…</p>}
    {error&&<p className="admin-warning" role="alert">{error}</p>}
    {uncertain?<div className="admin-warning"><p>La respuesta no se pudo confirmar. Conservamos la misma operación y los datos enviados.</p><button type="button" className="admin-button" disabled={busy} onClick={()=>save()}>Reintentar el mismo guardado</button></div>:<div className="configuration-actions"><button type="button" className="admin-button secondary" disabled={locked} onClick={onBack}>Volver a recursos</button><button className="admin-button" disabled={locked||loading||conflict||!!loadError}>Guardar horarios y modalidades</button></div>}
    </form>
    {conflict&&<div className="admin-warning"><p>El borrador cambió. Tus datos permanecen en el formulario.</p><button type="button" className="admin-button secondary" disabled={locked} onClick={consult}>Consultar horarios guardados</button></div>}
    {latest&&<section className="admin-card"><h3>Edición actual {latest.version}</h3><p>{latest.entrega.horariosPorSucursal.length} calendarios guardados.</p><div className="configuration-actions"><button type="button" className="admin-button secondary" disabled={locked} onClick={adopt}>Usar edición actual conservando mis datos</button><button type="button" className="admin-button secondary" disabled={locked} onClick={()=>onSaved(latest)}>Cargar el estado guardado</button></div></section>}
    <section className="admin-card delivery-validation"><div className="resource-toolbar"><h3>Validación de la fase</h3><button type="button" className="admin-button secondary" disabled={locked||loading} onClick={load}>Actualizar validación y sucursales</button></div><p className="admin-note">El borrador admite datos incompletos. Esta comprobación usa la edición guardada; avanzar exige completar los mínimos.</p>{dirty&&<p className="admin-info">Hay cambios sin guardar. Los resultados siguientes corresponden a los datos guardados.</p>}{validation&&<>{validation.valida?<p className="admin-success">Calendarios, tiempos y modalidades cumplen los mínimos de esta fase.</p>:<ul className="delivery-issues">{validation.problemas.map((p,i)=><li key={`${p.codigo}:${p.sucursal}:${i}`}>{p.sucursal&&<strong>{name(p.sucursal)}: </strong>}{p.mensaje}</li>)}</ul>}{validation.avisos.map((aviso,i)=><p className="admin-info" key={i}>{aviso}</p>)}</>}<p className="admin-note">La reserva de capacidad y la revisión integral antes de activar siguen En construcción.</p></section>
    <section className="admin-card delivery-simulation"><h3>Simulación del recorrido temporal</h3><p className="admin-note">Calcula sobre los horarios guardados. No crea pedidos, reservas ni entregas.</p><form className="admin-form" onSubmit={simulate}><fieldset className="admin-fieldset" disabled={locked||dirty||conflict||loading||!!loadError}><div className="admin-form-grid"><div className="catalog-field"><label htmlFor="estimate-branch">Sucursal del ejemplo</label><select id="estimate-branch" required value={simulationBranch} onChange={e=>{setSimulationBranch(e.target.value);setSimulationPoint("");clearEstimate();}}><option value="">Elegir sucursal</option>{schedules.map(s=><option key={s.sucursal} value={s.sucursal}>{name(s.sucursal)}</option>)}</select></div><div className="catalog-field"><label htmlFor="estimate-mode">Modalidad del ejemplo</label><select id="estimate-mode" required value={simulationMode} onChange={e=>{setSimulationMode(e.target.value);setSimulationPoint("");clearEstimate();}}><option value="">Elegir modalidad</option>{selectedModes.map(m=><option key={m} value={m}>{modes[m]}</option>)}</select></div><div className="catalog-field"><label htmlFor="estimate-date">Fecha y hora de recepción (UTC)</label><input id="estimate-date" type="datetime-local" step="60" required value={receipt} onChange={e=>{setReceipt(e.target.value);clearEstimate();}}/><small>La preparación usa la zona del origen; la llegada y franja usan la zona del destino.</small></div>{simulationMode==="RETIRO_PUNTO_ENTREGA"&&<div className="catalog-field"><label htmlFor="estimate-point">Punto de entrega del ejemplo</label><select id="estimate-point" required value={simulationPoint} onChange={e=>{setSimulationPoint(e.target.value);clearEstimate();}}><option value="">Elegir punto</option>{pointOptions.map(p=><option key={p.punto} value={p.punto}>{p.nombre} · {p.zonaHoraria}</option>)}</select><small>{pointOptions.length?"Opciones habilitadas para esta sucursal según la última consulta. El servidor vuelve a comprobarlas al calcular.":"No hay puntos utilizables para este origen. Revisá relación, disponibilidad temporal y franjas con cupo positivo."}</small></div>}{simulationMode==="ENVIO_DOMICILIO"&&([['codigoPostal','Código postal del ejemplo'],['localidad','Localidad del ejemplo'],['provincia','Provincia del ejemplo']] as const).map(([key,label])=><label key={key}>{label}<input required maxLength={key==='codigoPostal'?24:120} value={territory[key]} onChange={e=>{setTerritory(t=>({...t,[key]:e.target.value}));clearEstimate();}}/></label>)}</div><button className="admin-button">Calcular recorrido temporal</button></fieldset></form>{dirty&&<p className="admin-note">Guardá tus cambios para calcular el recorrido.</p>}{simulationError&&<p className="admin-warning" role="alert">{simulationError}</p>}
      {estimate&&<div className="delivery-result"><p>Zona del origen: <strong>{estimate.zonaHoraria}</strong></p>{estimate.destinoPunto&&<p>Punto: <strong>{estimate.destinoPunto.nombre}</strong> · Zona del destino: <strong>{estimate.destinoPunto.zonaHoraria}</strong></p>}{estimate.destinoZona&&<p>Zona de envío: <strong>{estimate.destinoZona.nombre}</strong> · {estimate.destinoZona.territorio.codigoPostal}, {estimate.destinoZona.territorio.localidad}, {estimate.destinoZona.territorio.provincia} · Zona horaria: <strong>{estimate.destinoZona.zonaHoraria}</strong></p>}<ol className="delivery-timeline"><li><strong>Pedido recibido</strong><span>{date(estimate.recibidoEn)}</span></li><li><strong>{estimate.enCola?"En cola hasta la apertura":"Inicio de preparación"}</strong><span>{date(estimate.inicioPreparacion)}</span></li><li><strong>Preparación terminada</strong><span>{date(estimate.finPreparacion)}</span></li>{estimate.llegadaEstimada&&<li><strong>Llegada estimada</strong><span>{date(estimate.llegadaEstimada,destination?.zonaHoraria)}</span></li>}<li><strong>Disponibilidad de entrega</strong><span>{date(estimate.disponibleDesde,destination?.zonaHoraria)}</span></li></ol>{destination&&<section className="delivery-point-window"><h4>{estimate.destinoZona?"Ventana estimada de envío":"Ventana estimada en el punto"}</h4><p>Desde {date(destination.franjaDesde,destination.zonaHoraria)} hasta {date(destination.franjaHasta,destination.zonaHoraria)}.</p><p>Franja habitual: {destination.apertura}–{destination.cierre}. Costo configurado: ARS {destination.costo}. Cupo configurado: {destination.cupoConfigurado} pedidos{estimate.destinoZona?" compartidos entre todas las sucursales":""}.</p>{estimate.destinoPunto&&<p>Estado temporal consultado: edición {estimate.destinoPunto.versionDisponibilidad}.</p>}<p>No se reservaron plazas.</p></section>}<ul>{estimate.advertencias.map((a,i)=><li key={i}>{a}</li>)}</ul></div>}
    </section><div className="configuration-actions"><button type="button" className="admin-button secondary" disabled>Fase 6 · En construcción</button></div>
  </>;
}
