"use client";
import {useEffect,useRef,useState,type FormEvent} from "react";
import {catalogDate} from "@/lib/catalog-types";
import {modelLabels,criterionLabels} from "@/lib/configuration-types";
import {HistoryValues,historySummary} from "@/components/configuration-history-values";
import {isHistoryList,isHistoryDetail,isHistoryEvents,isHistoryComparison,type Actor,type HistoryRow,type HistoryList,type HistoryDetail,type HistoryEvent,type HistoryPage,type HistoryComparison} from "@/lib/configuration-history-types";
const root="/api/admin/configuracion/historial";
const states:Record<string,string>={ACTIVA:"Activa",PROGRAMADA:"Programada",HISTORICA:"Histórica",CANCELADA:"Cancelada"};
const events:Record<string,string>={BORRADOR_CREADO:"Borrador creado",MODELO_SELECCIONADO:"Modelo seleccionado",CANCELACION_SOLICITADA:"Cancelación solicitada",BORRADOR_CANCELADO:"Borrador cancelado",PAGOS_CONFIGURADOS:"Pagos configurados",RECURSOS_CONFIGURADOS:"Recursos configurados",IMPRESORA_CREADA:"Impresora declarada",IMPRESORA_EDITADA:"Impresora editada",IMPRESORA_ESTADO_CAMBIADO:"Estado de impresora cambiado",IMPRESORA_RETIRADA:"Impresora retirada",ENTREGA_CONFIGURADA:"Entrega configurada",PUNTO_CREADO:"Punto creado",PUNTO_EDITADO:"Punto editado",ZONA_CREADA:"Zona creada",ZONA_EDITADA:"Zona editada",ACTIVACION_SOLICITADA:"Activación solicitada",CONFIGURACION_ACTIVADA:"Configuración activada",CONFIGURACION_HISTORICA:"Reemplazada por otra configuración",AUTORIZACION_RECHAZADA:"Autorización rechazada",PROGRAMACION_SOLICITADA:"Programación solicitada",CONFIGURACION_PROGRAMADA:"Activación programada",PROGRAMACION_CANCELADA:"Programación cancelada",INTENTO_MANUAL_INICIADO:"Inicio manual registrado",INTENTO_EXITOSO:"Intento exitoso",INTENTO_FALLIDO:"Intento fallido",INTENTO_INTERRUMPIDO:"Intento interrumpido",INTENTO_INICIADO:"Intento en curso"};
const date=(x:string|null)=>x?catalogDate(x):"Sin registro";
function ActorName({value}:{value:Actor|null}){return value?<span>{value.nombre} · {value.rol??"Rol no capturado"}{!value.capturado&&<small className="admin-note">Identidad actual; registro anterior a la captura histórica.</small>}</span>:<span>Sin registro</span>;}
function Validity({v}:{v:HistoryRow}){return <>{v.activadaEn?<>Desde {date(v.activadaEn)}{v.finVigencia&&<small>Hasta {date(v.finVigencia)}</small>}</>:v.previstaEn?<>Prevista: {new Intl.DateTimeFormat("es-AR",{dateStyle:"short",timeStyle:"short",timeZone:v.zonaHoraria??"UTC"}).format(new Date(v.previstaEn))}<small>{v.zonaHoraria} · {v.canceladaEn?"Cancelada sin activación":"Aún sin vigencia"}</small></>:<>Sin vigencia{v.canceladaEn&&<small>Cancelada: {date(v.canceladaEn)}</small>}</>}</>;}
async function read<T>(path:string,guard:(v:unknown)=>v is T):Promise<T>{const r=await fetch(path,{cache:"no-store"});const data:unknown=await r.json();if(!r.ok)throw new Error(r.status===403?"No tenés permiso para consultar el historial.":"No pudimos consultar el historial. Volvé a intentarlo.");if(!guard(data))throw new Error("El historial recibido tiene un formato inesperado.");return data;}
export function ConfigurationHistory({onCurrent}:{onCurrent:()=>void}){
 const[list,setList]=useState<HistoryList|null>(null),[detail,setDetail]=useState<HistoryDetail|null>(null),[audit,setAudit]=useState<HistoryPage<HistoryEvent>|null>(null),[comparison,setComparison]=useState<HistoryComparison|null>(null),[view,setView]=useState<"list"|"detail"|"compare">("list");
 const[search,setSearch]=useState(""),[state,setState]=useState("TODOS"),[order,setOrder]=useState("RECIENTES"),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const[origin,setOrigin]=useState(""),[destination,setDestination]=useState(""),[options,setOptions]=useState<HistoryRow[]>([]),[optionPage,setOptionPage]=useState(0),[moreOptions,setMoreOptions]=useState(false);
 const ticket=useRef(0),filter=useRef({buscar:"",estado:"TODOS",orden:"RECIENTES"});
 async function run(work:()=>Promise<void>){if(busy)return;setBusy(true);setError("");try{await work();}catch(e){setError(e instanceof Error?e.message:"No pudimos consultar.");}finally{setBusy(false);}}
 async function listing(page=0){const q=new URLSearchParams({...filter.current,pagina:String(page)});const data=await read(root+"?"+q,isHistoryList);setList(data);setView("list");}
 useEffect(()=>{const n=++ticket.current;setBusy(true);read(root,isHistoryList).then(d=>{if(ticket.current===n)setList(d);}).catch(()=>{if(ticket.current===n)setError("No pudimos consultar el historial. Volvé a intentarlo.");}).finally(()=>{if(ticket.current===n)setBusy(false);});return()=>{ticket.current++;};},[]);
 async function open(id:string){const[d,a]=await Promise.all([read(root+"/"+id,isHistoryDetail),read(root+"/"+id+"/auditoria",isHistoryEvents)]);setDetail(d);setAudit(a);setView("detail");setComparison(null);}
 async function optionBatch(page:number){const d=await read(root+"?pagina="+page,isHistoryList);setOptions(current=>page===0?d.versiones.elementos:[...current,...d.versiones.elementos.filter(x=>!current.some(o=>o.codigo===x.codigo))]);setOptionPage(page);setMoreOptions((page+1)*d.versiones.tamano<d.versiones.total);return d;}
 async function compareFrom(){if(!detail)return;const d=await optionBatch(0);const target=d.activa?.codigo??"";setOrigin(detail.version.codigo);setDestination(target);setComparison(null);setView("compare");if(target)setComparison(await read(`${root}/${detail.version.codigo}/comparacion/${target}`,isHistoryComparison));}
 function submit(e:FormEvent){e.preventDefault();filter.current={buscar:search.trim(),estado:state,orden:order};void run(()=>listing());}
 const comparisonOptions=[...new Map([...(detail?[detail.version]:[]),...(comparison?[comparison.origen,comparison.destino]:[]),...options].map(v=>[v.codigo,v])).values()];
 return <div className="configuration-history-panel" aria-busy={busy}>
 {view==="list"?<><h2>Fase 8 · Historial de versiones</h2><p className="admin-note">Consultar configuraciones activas, programadas, históricas y canceladas.</p>{list&&<div className="configuration-summary history-summary"><section className="admin-card"><span className="history-symbol active" aria-hidden="true">✓</span><h3>Activa: {list.activa?`V${list.activa.numero}`:"Ninguna"}</h3><p>Configuración actualmente vigente.</p></section><section className="admin-card"><span className="history-symbol scheduled" aria-hidden="true">▣</span><h3>Programadas: {list.cantidades.PROGRAMADA??0}</h3><p>Cambios pendientes de publicación.</p></section><section className="admin-card"><span className="history-symbol" aria-hidden="true">▤</span><h3>Históricas: {list.cantidades.HISTORICA??0}</h3><p>Canceladas: {list.cantidades.CANCELADA??0}. Todas conservan su registro.</p></section></div>}
 <section className="admin-card"><h3>Versiones de configuración</h3><form className="history-filters admin-form" onSubmit={submit}><label>Buscar versión<input placeholder="Por ejemplo, V2" maxLength={19} pattern="[vV]?[0-9]{0,18}" value={search} onChange={e=>setSearch(e.target.value)}/></label><label>Estado<select aria-label="Estado" value={state} onChange={e=>setState(e.target.value)}><option value="TODOS">Todos</option>{Object.entries(states).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Orden<select aria-label="Orden" value={order} onChange={e=>setOrder(e.target.value)}><option value="RECIENTES">Más recientes</option><option value="ANTIGUAS">Más antiguas</option></select></label><button className="admin-button secondary" disabled={busy}>Consultar versiones</button></form>
 {list?.versiones.elementos.length?<div className="admin-table-wrap" tabIndex={0} aria-label="Versiones de configuración"><table className="admin-table history-table"><thead><tr>{["Versión","Estado","Vigencia","Autor","Modelo","Resumen","Acciones"].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{list.versiones.elementos.map(v=><tr key={v.codigo}><td><strong>V{v.numero}</strong></td><td><span className={`history-badge ${v.estado.toLowerCase()}`}>{states[v.estado]}</span></td><td><Validity v={v}/></td><td><ActorName value={v.autor}/></td><td>{v.modelo?modelLabels[v.modelo as keyof typeof modelLabels]:"Sin seleccionar"}{v.criterio&&<small>{criterionLabels[v.criterio as keyof typeof criterionLabels]}</small>}</td><td>{v.motivo}</td><td><button className="admin-button secondary" disabled={busy} aria-label={`Ver detalle de V${v.numero}`} onClick={()=>void run(()=>open(v.codigo))}>Ver detalle</button></td></tr>)}</tbody></table></div>:!busy&&<p className="admin-empty">No hay versiones cerradas que coincidan. Los borradores se consultan desde la configuración actual.</p>}
 {list&&<div className="configuration-actions"><button className="admin-button secondary" disabled={busy||list.versiones.pagina===0} onClick={()=>void run(()=>listing(list.versiones.pagina-1))}>Página anterior</button><span>{list.versiones.total} versiones · Página {list.versiones.pagina+1}</span><button className="admin-button secondary" disabled={busy||(list.versiones.pagina+1)*list.versiones.tamano>=list.versiones.total} onClick={()=>void run(()=>listing(list.versiones.pagina+1))}>Página siguiente</button></div>}<p className="admin-info">La consulta no modifica las versiones. Para reutilizar una configuración se creará un nuevo borrador.</p></section><div className="configuration-actions"><a className="admin-button secondary" href="/administracion">Volver al inicio</a><button className="admin-button" onClick={onCurrent}>Ver configuración actual</button></div></>:view==="detail"&&detail?<>
 <h2>Fase 8 · Detalle de versión V{detail.version.numero}</h2><p className="admin-note">Configuración {states[detail.version.estado].toLowerCase()} · Solo lectura</p><section className="admin-card history-version"><h3>V{detail.version.numero} · {states[detail.version.estado]}</h3><Validity v={detail.version}/><div className="activation-facts"><p><small>Autor de la versión</small><ActorName value={detail.version.autor}/></p><p><small>Creada</small>{date(detail.version.creadaEn)}</p><p><small>Publicada por</small><ActorName value={detail.activador}/></p><p><small>Motivo</small>{detail.version.motivo}</p></div>{detail.programador&&<p>Programada el {date(detail.version.confirmadaEn)} por <ActorName value={detail.programador}/>. Motivo: {detail.motivoProgramacion}. Fecha prevista: {date(detail.version.previstaEn)}.</p>}<div className="configuration-actions">{detail.predecesora&&<button className="admin-button secondary" disabled={busy} onClick={()=>void run(()=>open(detail.predecesora!.codigo))}>Predecesora V{detail.predecesora.numero}</button>}{detail.reemplazadaPor&&<button className="admin-button secondary" disabled={busy} onClick={()=>void run(()=>open(detail.reemplazadaPor!.codigo))}>Reemplazada por V{detail.reemplazadaPor.numero}</button>}</div></section>
 <h3>Resumen de la configuración</h3><p className="admin-note">Parámetros guardados en esta versión. Las referencias a sucursales, formatos y servicios muestran sus nombres actuales; no certifican disponibilidad actual ni cupos libres.</p><div className="history-modules">{detail.modulos.map((m,i)=><details className="admin-card" key={m.codigo}><summary><span className={`history-module-icon icon-${i}`} aria-hidden="true">{["⚙","▣","▤","◷","⌖"][i]}</span><span className="history-module-description"><strong>{i+1}. {m.titulo}</strong><small>{historySummary(m.codigo,m.valores)}</small></span><span aria-hidden="true">›</span></summary><HistoryValues value={m.valores} refs={detail.referencias}/></details>)}<section className="admin-card"><h4>6. Referencia comercial informativa</h4><p>{detail.revisionComercial?`RC-${detail.revisionComercial.numero}`:"No capturada"}</p><p className="admin-note">Servicios y precios mantienen su historial independiente. No se restauran al consultar esta versión.</p><a href="/administracion/catalogo">Consultar catálogo e historial comercial</a></section></div>
 <section className="admin-card"><h3>Auditoría</h3><ol className="history-timeline">{audit?.elementos.map(e=><li key={e.clave}><div><strong>{events[e.tipo]??e.tipo}</strong><time>{date(e.fecha)}</time></div><p>{e.descripcion}</p><p className="admin-note">Por <ActorName value={e.actor}/>{e.edicion!==null&&` · Edición ${e.edicion}`}</p>{e.estadoNuevo&&<p>{e.estadoAnterior??"Sin estado anterior"} → {e.estadoNuevo}</p>}{e.recurso&&<p className="admin-note">Recurso o intento: {detail.referencias[e.recurso]??e.recurso}</p>}{e.origen&&<p>Origen: {e.origen}. Inicio: {date(e.inicio)}. Fin: {date(e.fin)}{e.atraso&&`. Atraso detectado: ${date(e.atraso)}`}.</p>}</li>)}</ol>{audit&&<div className="configuration-actions"><button className="admin-button secondary" disabled={busy||audit.pagina===0} onClick={()=>void run(async()=>setAudit(await read(`${root}/${detail.version.codigo}/auditoria?pagina=${audit.pagina-1}`,isHistoryEvents)))}>Eventos anteriores</button><span>{audit.total} registros · Página {audit.pagina+1}</span><button className="admin-button secondary" disabled={busy||(audit.pagina+1)*audit.tamano>=audit.total} onClick={()=>void run(async()=>setAudit(await read(`${root}/${detail.version.codigo}/auditoria?pagina=${audit.pagina+1}`,isHistoryEvents)))}>Eventos siguientes</button></div>}</section>
 <div className="configuration-actions"><button className="admin-button secondary" disabled={busy} onClick={()=>setView("list")}>Volver al historial</button><button className="admin-button secondary" disabled={busy} onClick={()=>void run(compareFrom)}>Comparar versiones</button><button className="admin-button" disabled>Usar como base · En construcción</button></div></>:view==="compare"?<>
 <h2>Fase 8 · Comparar versiones</h2><p className="admin-note">Diferencias entre configuraciones guardadas, sin modificar ninguna versión.</p><form className="admin-card history-filters admin-form" onSubmit={e=>{e.preventDefault();if(origin&&destination)void run(async()=>setComparison(await read(`${root}/${origin}/comparacion/${destination}`,isHistoryComparison)));}}><label>Origen<select aria-label="Origen" required value={origin} onChange={e=>setOrigin(e.target.value)}><option value="">Elegí versión</option>{comparisonOptions.map(v=><option key={v.codigo} value={v.codigo}>V{v.numero} · {states[v.estado]}</option>)}</select></label><label>Destino<select aria-label="Destino" required value={destination} onChange={e=>setDestination(e.target.value)}><option value="">Elegí versión</option>{comparisonOptions.map(v=><option key={v.codigo} value={v.codigo}>V{v.numero} · {states[v.estado]}</option>)}</select></label><button className="admin-button secondary" disabled={busy}>Cambiar comparación</button>{moreOptions&&<button type="button" className="admin-button secondary" disabled={busy} onClick={()=>void run(async()=>{await optionBatch(optionPage+1);})}>Cargar más versiones</button>}</form>
 {comparison&&<><h3>Cambios detectados: V{comparison.origen.numero} → V{comparison.destino.numero}</h3>{(origin!==comparison.origen.codigo||destination!==comparison.destino.codigo)&&<p className="admin-warning">Cambiaste la selección. Pulsá Cambiar comparación para actualizar el resultado.</p>}<div className="admin-card"><div className="admin-table-wrap" tabIndex={0} aria-label="Comparación por módulos"><table className="admin-table history-comparison"><thead><tr><th>Sección</th><th>V{comparison.origen.numero}</th><th>V{comparison.destino.numero}</th><th>Resultado</th></tr></thead><tbody>{comparison.secciones.map(s=><tr key={s.codigo}><td>{s.titulo}</td><td><p>{historySummary(s.codigo,s.origen)}</p><details><summary>Ver valores de origen</summary><HistoryValues value={s.origen} refs={comparison.referencias}/></details></td><td><p>{historySummary(s.codigo,s.destino)}</p><details><summary>Ver valores de destino</summary><HistoryValues value={s.destino} refs={comparison.referencias}/></details></td><td><span className={`history-badge ${s.modificada?"modified":"activa"}`}>{s.modificada?"Modificado":"Sin cambios"}</span></td></tr>)}</tbody></table></div><p>{comparison.modificadas} secciones modificadas · {comparison.secciones.length-comparison.modificadas} sin cambios</p></div><p className="admin-info">Servicios y precios se comparan desde su historial comercial independiente. Referencias informativas: {comparison.comercialOrigen?`RC-${comparison.comercialOrigen.numero}`:"No capturada"} → {comparison.comercialDestino?`RC-${comparison.comercialDestino.numero}`:"No capturada"}.</p></>}
 <div className="configuration-actions"><button className="admin-button secondary" disabled={busy} onClick={()=>void run(()=>open(comparison?.origen.codigo??detail!.version.codigo))}>Volver al detalle</button><button className="admin-button" disabled>Usar como base · En construcción</button></div></>:null}
 {busy&&<p role="status" className="admin-note">Consultando registros…</p>}{error&&<div className="admin-warning" role="alert"><p>{error}</p><button className="admin-button secondary" disabled={busy} onClick={()=>void run(()=>listing(list?.versiones.pagina??0))}>Volver a consultar historial</button></div>}
 </div>;
}
