"use client";
import {useEffect,useRef,useState} from "react";
import {quoteRead,money,date} from "@/lib/quote-types";
import {isOrder,type Order,type OrderPdf,type OrderReview} from "@/lib/order-types";
import {secureMutation,MutationError} from "@/lib/secure-mutation";
import {PrivateFiles} from "./private-files";
import {PaymentPanel} from "./payment-panel";
type Kind="ARCHIVO"|"DATOS"|"ENTREGA"|"CANTIDAD"|"OTRO";
type Request={codigoPublico:string;tipo:Kind;estado:string;mensajeCliente:string;motivoInterno:string|null;solicitante:string;fecha:string;cotizacionBase:string;items:string[];cotizaciones:{codigoPublico:string;total:string;estado:string;aceptadaEn:string|null;vigenteHasta:string}[];respuesta:{mensaje:string;fecha:string;cotizacion:string;total:string;archivos:OrderPdf[]}|null};
type View={version:number;puedeSolicitar:boolean;solicitudes:Request[]};
type Preview={solicitud:string;version:number;cotizacion:string;nuevaCotizacion:boolean;totalAnterior:string;totalNuevo:string;diferencia:string;huella:string;habilitada:boolean;bloqueos:string[];finales:OrderReview|null;archivos:OrderPdf[]};
const kinds:Record<Kind,string>={ARCHIVO:"Archivo PDF",DATOS:"Datos de contacto",ENTREGA:"Entrega",CANTIDAD:"Cantidades u opciones",OTRO:"Otro motivo"};
function isView(v:unknown):v is View {if(!v||typeof v!=="object")return false;const x=v as View;return Number.isSafeInteger(x.version)&&typeof x.puedeSolicitar==="boolean"&&Array.isArray(x.solicitudes)&&x.solicitudes.every(s=>typeof s.codigoPublico==="string"&&typeof s.mensajeCliente==="string"&&Array.isArray(s.items)&&Array.isArray(s.cotizaciones));}
function isPreview(v:unknown):v is Preview {if(!v||typeof v!=="object")return false;const x=v as Preview;return typeof x.huella==="string"&&typeof x.habilitada==="boolean"&&Number.isSafeInteger(x.version)&&Array.isArray(x.archivos)&&Array.isArray(x.bloqueos)&&typeof x.totalNuevo==="string";}
export function OrderCorrections({order,internal,financial,onSaved}:{order:Order;internal:boolean;financial:boolean;onSaved:()=>void}){
 const[data,setData]=useState<View|null>(null),[pre,setPre]=useState<Preview|null>(null),[error,setError]=useState(""),[notice,setNotice]=useState(""),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[uncertain,setUncertain]=useState(false),[requesting,setRequesting]=useState(false),[kind,setKind]=useState<Kind|"">(""),[ack,setAck]=useState(false),[revision,setRevision]=useState(0);
 const form=useRef<HTMLFormElement>(null),running=useRef(false),command=useRef<{path:string;body:string}|null>(null);
 const base=`/api/${internal?"operacion":"cliente"}/pedidos/${order.codigoPublico}/correcciones`,locked=busy||loading||uncertain;
 async function load(){if(running.current)return;setLoading(true);setError("");setAck(false);try{const v=await quoteRead(base,isView);setData(v);if(!internal&&order.estado==="CORRECCION_SOLICITADA"&&v.solicitudes.some(s=>s.estado==="PENDIENTE"))setPre(await quoteRead(`${base}/respuesta`,isPreview));else setPre(null);}catch(e){setError(e instanceof Error?e.message:"No se pudieron consultar las correcciones.");setPre(null);}finally{setLoading(false);}}
 useEffect(()=>{void load();},[order.codigoPublico,order.version,internal]);
 const pending=data?.solicitudes.find(s=>s.estado==="PENDIENTE"),candidate=pending?.cotizaciones[0],quote=candidate?.codigoPublico??order.cotizacion;
 const home=(pre?.finales?.franja?.modalidad??order.oferta.modalidad)==="ENVIO_DOMICILIO";
 const canEditContact=!!pre?.nuevaCotizacion||pending?.tipo==="DATOS"||pending?.tipo==="OTRO";
 async function save(recover=false){
  if(running.current||!recover&&locked)return;
  if(!recover){if(!form.current?.reportValidity())return;const f=new FormData(form.current);if(internal){const items=f.getAll("items");if(kind==="ARCHIVO"&&!items.length){setError("Seleccioná al menos un PDF que el cliente deba corregir.");return;}command.current={path:base,body:JSON.stringify({operacion:crypto.randomUUID(),version:order.version,tipo:kind,motivo:f.get("motivo"),mensajeCliente:f.get("mensaje"),items})};}
   else{if(!pre?.habilitada||!ack)return;command.current={path:`${base}/respuesta`,body:JSON.stringify({operacion:crypto.randomUUID(),version:pre.version,solicitud:pre.solicitud,huella:pre.huella,condicionesAceptadas:true,mensaje:f.get("mensaje"),contacto:home?canEditContact?{receptor:f.get("receptor"),telefono:f.get("telefono")}:order.contacto:null})};}}
  if(!command.current)return;running.current=true;setBusy(true);setError("");try{const r=await secureMutation(command.current.path,command.current.body,"application/json"),v:unknown=await r.json();if(!isOrder(v)||v.codigoPublico!==order.codigoPublico)throw new Error("No se pudo verificar la corrección guardada.");command.current=null;setUncertain(false);setRequesting(false);setAck(false);setNotice(internal?"Solicitud enviada. El pedido espera la respuesta del cliente.":"Respuesta guardada. La nueva versión espera revisión de la imprenta.");onSaved();}
  catch(e){setError(e instanceof Error?e.message:"No se pudo guardar la corrección.");if(e instanceof MutationError&&!e.uncertain){command.current=null;setUncertain(false);setPre(null);}else setUncertain(true);}finally{running.current=false;setBusy(false);}
 }
 function changed(){setRevision(n=>n+1);void load();}
 function requote(s:Request){return `/cliente/cotizaciones/nueva?pedido=${order.codigoPublico}&solicitud=${s.codigoPublico}&reemplaza=${s.cotizaciones[0]?.codigoPublico??s.cotizacionBase}`;}
 return <section id="pedido-correcciones" className="client-card order-corrections" aria-label="Correcciones del pedido"><header className="order-management-heading"><h2>Correcciones del trabajo</h2><span>{pending?"Esperando al cliente":"Solicitud y respuesta"}</span></header><p>El pedido conserva sus versiones anteriores. Enviar un archivo no responde la solicitud: el cliente debe revisar y enviar su respuesta explícitamente.</p>
 {loading&&<p role="status">Consultando correcciones…</p>}{data?.solicitudes.length===0&&!requesting&&<p className="client-empty">No hay correcciones solicitadas.</p>}
 {internal&&data?.puedeSolicitar&&!requesting&&<button className="client-button" disabled={locked} onClick={()=>{setRequesting(true);setKind("");setNotice("");}}>Solicitar corrección</button>}
 {internal&&requesting&&<form ref={form} className="client-form order-decision-form" onSubmit={e=>{e.preventDefault();void save();}}><h3>Solicitar corrección al cliente · PED-{order.numero}</h3><p className="client-muted">Confirmado el {date(order.confirmadaEn)} · {order.oferta.sucursal.nombre}</p><fieldset disabled={locked}><div className="client-grid correction-form-grid"><div className="correction-work-card"><h4>Detalles del trabajo</h4>{order.oferta.items.map(i=><p key={i.codigoPublico}>{i.documento.nombre}<br/>{i.formato} · {i.papel} · {i.trabajo.color==="COLOR"?"Color":"Blanco y negro"}<br/>{i.trabajo.paginas} páginas × {i.trabajo.copias} copias</p>)}<label>Tipo de corrección<select aria-label="Tipo de corrección" required value={kind} onChange={e=>setKind(e.target.value as Kind)}><option value="">Seleccioná el motivo</option>{Object.entries(kinds).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><h4>PDF que debe reemplazar</h4>{order.archivos.map((f,i)=><label className="client-check" key={f.archivo}><input type="checkbox" name="items" value={f.item}/>{i+1}. {f.nombre} · {f.paginas} páginas</label>)}<p className="client-muted">Marcá sólo los PDF que necesiten correcciones. Cambiar páginas, opciones o entrega requiere una nueva cotización aceptada.</p></div><div><label>Mensaje visible al cliente<textarea name="mensaje" required maxLength={2000}/></label><label>Motivo interno (no se muestra al cliente)<textarea name="motivo" required maxLength={500}/></label><p className="client-muted">Adjuntar archivos de referencia <span className="client-construction">En construcción</span></p></div></div><div className="client-actions"><button type="button" className="client-button order-danger" onClick={()=>setRequesting(false)}>Volver sin enviar</button><button className="client-button order-approve">Enviar solicitud de corrección</button></div></fieldset></form>}
 {data?.solicitudes.map(s=><article className="order-correction-entry" key={s.codigoPublico}><h3>{kinds[s.tipo]} · {s.estado}</h3><p>{date(s.fecha)} · {s.solicitante}</p><p className="order-text">{s.mensajeCliente}</p>{internal&&s.motivoInterno&&<p className="order-private-note order-text">Motivo interno: {s.motivoInterno}</p>}{s.items.length>0&&<p>PDF solicitados: {s.items.map(i=>order.archivos.find(f=>f.item===i)?.nombre??"Ítem de una versión anterior").join(", ")}.</p>}
 {s.cotizaciones.length>0&&<div className="client-table-wrap"><table className="client-table"><thead><tr><th>Oferta</th><th>Total</th><th>Aceptación</th></tr></thead><tbody>{s.cotizaciones.map((q,i)=><tr key={q.codigoPublico}><td>{!internal?<a href={`/cliente/cotizaciones/${q.codigoPublico}`}>{i===0?"Última cotización":"Cotización anterior"}</a>:i===0?"Última cotización":"Cotización anterior"}<br/>{q.estado}</td><td>{money(q.total)}</td><td>{q.aceptadaEn?date(q.aceptadaEn):"Pendiente"}</td></tr>)}</tbody></table></div>}
 {s.respuesta&&<details><summary>Respuesta del cliente · {date(s.respuesta.fecha)}</summary><p className="order-text">{s.respuesta.mensaje}</p><p>Total de esa versión: {money(s.respuesta.total)}</p><ul>{s.respuesta.archivos.map(f=><li key={f.archivo}><a href={`/api/${internal?"operacion":"cliente"}/cotizaciones/${s.respuesta!.cotizacion}/archivos/${f.archivo}/original`}>{f.nombre} · {f.paginas} páginas</a> · Vista previa aceptada {date(f.aceptadaEn)}</li>)}</ul></details>}
 {!internal&&s.estado==="PENDIENTE"&&<div className="client-actions"><a className="client-button secondary" href={locked?undefined:requote(s)}>Cotizar cambios de páginas, opciones o entrega</a>{candidate&&<a className="client-button" href={`/cliente/cotizaciones/${candidate.codigoPublico}`}>Revisar y aceptar la nueva cotización</a>}</div>}</article>)}
 {pending&&internal&&candidate&&<><p className="client-note">El cliente propone una cotización nueva. La aplicación de dinero requiere su aceptación y permiso financiero; responder la corrección no realiza el movimiento.</p><PrivateFiles quote={quote} version={order.version} internal refresh={revision}/>{financial&&<PaymentPanel quote={quote} internal onChange={changed}/>}</>}
 {pending&&!internal&&<><PrivateFiles quote={quote} version={order.version} refresh={revision} correction={{pedido:order.codigoPublico,solicitud:pending.codigoPublico}} onChange={changed}/>{candidate&&<PaymentPanel quote={quote} onChange={changed}/>}<section className="order-correction-response"><h3>Revisar y responder</h3>{pre&&<><div className="payment-totals"><div><span>Importe anterior</span><strong>{money(pre.totalAnterior)}</strong></div><div><span>Importe propuesto</span><strong>{money(pre.totalNuevo)}</strong></div><div><span>Diferencia del trabajo</span><strong>{money(pre.diferencia)}</strong></div></div><p className="client-note">Esta diferencia compara precios. El dinero acreditado, aplicado y pendiente figura en los pagos. Responder no cobra ni mueve dinero automáticamente.</p>{pre.finales?.franja&&<p>Nueva reserva: {pre.finales.franja.nombre} · {pre.finales.franja.fecha} · {pre.finales.franja.apertura}–{pre.finales.franja.cierre} ({pre.finales.franja.zonaHoraria}).</p>}{pre.finales?.condiciones&&<p>Condiciones al responder: pago previo {money(pre.finales.condiciones.actuales.pagoPrevioRequerido)}, seña {money(pre.finales.condiciones.actuales.senaRequerida)} y saldo {money(pre.finales.condiciones.actuales.saldo)}. Se conservan también las condiciones cotizadas. El trabajo vuelve a revisión humana.</p>}{pre.bloqueos.length>0&&<ul className="client-warning">{pre.bloqueos.map(b=><li key={b}>{b}</li>)}</ul>}<form ref={form} className="client-form" onSubmit={e=>{e.preventDefault();void save();}}><fieldset disabled={locked||!pre.habilitada}><label>Respuesta a la imprenta<textarea name="mensaje" required maxLength={2000}/></label>{home&&canEditContact&&<><label>Nombre de quien recibe<input name="receptor" defaultValue={order.contacto?.receptor??""} required maxLength={140}/></label><label>Teléfono de contacto<input name="telefono" type="tel" defaultValue={order.contacto?.telefono??""} required minLength={6} maxLength={40}/></label></>}<label className="client-check"><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/>Revisé y acepto los PDF propuestos, el importe, la entrega y las condiciones de esta respuesta.</label><button className="client-button order-approve" disabled={!ack}>Enviar respuesta de corrección</button></fieldset></form></>}<button className="client-button secondary" disabled={locked} onClick={()=>void load()}>Actualizar revisión de la respuesta</button></section></>}
 {error&&<p className="client-warning" role="alert">{error}</p>}{notice&&<p className="client-success" role="status">{notice}</p>}{uncertain&&<div className="client-warning"><p>No se pudo confirmar la respuesta del sistema. Recuperá la misma operación antes de enviar otra.</p><button className="client-button" disabled={busy} onClick={()=>void save(true)}>Recuperar corrección</button></div>}
 </section>;
}
