"use client";
import {useEffect,useState} from "react";
import {quoteRead,money,date,modeLabels} from "@/lib/quote-types";
import {isOrderList,orderState,type OrderList} from "@/lib/order-types";
import "@/app/client.css";
export function OrderListView({branch}:{branch?:string}){
 const[state,setState]=useState("");
 const[data,setData]=useState<OrderList|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 async function load(page=0){setBusy(true);setError("");try{setData(await quoteRead(`${branch?`/api/operacion/sucursales/${branch}/pedidos`:"/api/cliente/pedidos"}?pagina=${page}${state?`&estado=${state}`:""}`,isOrderList));}catch(e){setError(e instanceof Error?e.message:"No pudimos consultar los pedidos.");}finally{setBusy(false);}}
 useEffect(()=>{void load();},[branch,state]);
 return <section className="client-card"><h2>{branch?"Pedidos de esta sucursal":"Mis pedidos"}</h2><p>Pedidos confirmados con sus archivos y reserva. La aprobación, la producción y la entrega son pasos separados.</p>{busy&&<p role="status">Consultando pedidos…</p>}{error&&<p role="alert" className="client-warning">{error}</p>}<div className="client-actions"><label>Filtrar por estado <select aria-label="Filtrar por estado" value={state} disabled={busy} onChange={e=>setState(e.target.value)}><option value="">Todos los pedidos</option>{["PENDIENTE_REVISION","CORRECCION_SOLICITADA","APROBADO","RECHAZADO","CANCELADO"].map(s=><option key={s} value={s}>{orderState(s)}</option>)}</select></label><button className="client-button secondary" disabled={busy} onClick={()=>void load(data?.pagina??0)}>Actualizar pedidos</button></div>{data?.total===0&&<p className="client-empty">No hay pedidos con este filtro.</p>}{!!data?.total&&<><div className="client-table-wrap"><table className="client-table"><thead><tr><th>Pedido</th><th>Estado</th><th>Sucursal</th><th>Entrega</th><th>Confirmado</th><th>Total</th><th>Acción</th></tr></thead><tbody>{data.elementos.map(p=><tr key={p.codigoPublico}><td>PED-{p.numero}</td><td><span className="client-state">{orderState(p.estado)}</span></td><td>{p.sucursal}</td><td>{modeLabels[p.modalidad]}</td><td>{date(p.confirmadaEn)}</td><td>{money(p.total)}</td><td><a className="client-button secondary" href={`/${branch?"operacion":"cliente"}/pedidos/${p.codigoPublico}`}>Ver PED-{p.numero}</a></td></tr>)}</tbody></table></div><div className="client-actions"><button className="client-button secondary" disabled={busy||data.pagina===0} onClick={()=>void load(data.pagina-1)}>Anteriores</button><span>Página {data.pagina+1} · {data.total} pedidos</span><button className="client-button secondary" disabled={busy||(data.pagina+1)*25>=data.total} onClick={()=>void load(data.pagina+1)}>Siguientes</button></div></>}</section>;
}
