"use client";
import {useEffect,useRef,useState,type FormEvent} from "react";
import {quoteRead,date,money} from "@/lib/quote-types";
import {isPaymentView,type PaymentView,type Payment} from "@/lib/payment-types";
import {secureMutation,MutationError} from "@/lib/secure-mutation";
import {PaymentEvidence} from "./payment-evidence";
import "@/app/client.css";
import "@/app/payments.css";
type Action={type:"informar"|"descartar"|"recibir"|"aplicar"|"devolver";payment?:Payment;intento?:string;medio?:string};
const names:Record<Action["type"],string>={informar:"Informar transferencia",descartar:"Descartar transferencia informada",recibir:"Registrar dinero recibido",aplicar:"Aplicar dinero a esta cotización",devolver:"Registrar devolución realizada"};
export function PaymentPanel({quote,internal=false,onChange}:{quote:string;internal?:boolean;onChange?:()=>void}){
 const base=`/api/${internal?"operacion":"cliente"}/cotizaciones/${quote}/pagos`;
 const[data,setData]=useState<PaymentView|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[uncertain,setUncertain]=useState(false),[error,setError]=useState(""),[success,setSuccess]=useState(""),[action,setAction]=useState<Action|null>(null);
 const [evidence,setEvidence]=useState<{quote:string;parent:string;kind:"intento"|"pago"}|null>(null);
 const sending=useRef(false),command=useRef<{path:string;body:string}|null>(null),formRef=useRef<HTMLFormElement>(null);const locked=loading||busy||uncertain;
 async function load(){setLoading(true);setError("");try{const v=await quoteRead(base,isPaymentView);setData(v);onChange?.();}catch(e){setError(e instanceof Error?e.message:"No pudimos consultar los pagos.");}finally{setLoading(false);}}
 useEffect(()=>{void load();},[quote,internal]);
 function choose(a:Action){if(locked)return;setAction(a);setError("");setSuccess("");setTimeout(()=>{formRef.current?.scrollIntoView({behavior:"smooth",block:"center"});formRef.current?.querySelector<HTMLInputElement>("input:not([type=hidden])")?.focus();},0);}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(locked||!action)return;const f=new FormData(e.currentTarget);const body:Record<string,unknown>={operacion:crypto.randomUUID(),motivo:f.get("motivo")};
  if(action.type!=="descartar")body.importe=f.get("importe");
  if(["informar","recibir","devolver"].includes(action.type))body.referencia=f.get("referencia");
  if(action.intento)body.intento=action.intento;
  if(action.payment){body.pago=action.payment.codigoPublico;body.version=action.payment.version;}
  if(action.type==="recibir"||action.type==="devolver"){
   const raw=f.get("fecha");const when=new Date(typeof raw==="string"?raw:"");if(!Number.isFinite(when.getTime())||when.getTime()>Date.now()){setError("Indicá una fecha y hora válida, correspondiente a un movimiento ya realizado.");return;}
   body[action.type==="recibir"?"recibidoEn":"devueltoEn"]=when.toISOString();body.medio=action.medio??f.get("medio");body.verificado=f.get("verificado")==="on";
  }
  command.current={path:`${base}/${action.type}`,body:JSON.stringify(body)};await execute();
 }
 async function execute(){if(sending.current||!command.current)return;sending.current=true;setBusy(true);setError("");const c=command.current;
  try{const response=await secureMutation(c.path,c.body,"application/json"),v:unknown=await response.json();if(!isPaymentView(v)||v.cotizacion!==quote)throw new Error("No pudimos verificar el resultado guardado.");setData(v);setUncertain(false);command.current=null;setAction(null);setSuccess("La operación quedó registrada. Los importes de abajo reflejan su resultado.");onChange?.();}
  catch(e){setError(e instanceof Error?e.message:"No pudimos completar la operación.");if(e instanceof MutationError&&!e.uncertain){command.current=null;setUncertain(false);}else setUncertain(true);}finally{sending.current=false;setBusy(false);}
 }
 const permission=(p:string)=>internal&&data?.permisos.includes(p),hasAction=!!action;
 return <section className="payment-panel" aria-label="Pagos de la cotización"><header className="payment-heading"><div><span>LA MONTAÑA · FINANZAS</span><h2>{data?.estado==="CONFIRMADA"?"Pagos del pedido":internal?"Dinero y aplicación a la cotización":"Pagos de tu cotización"}</h2></div><button className="client-button secondary" disabled={locked} onClick={()=>void load()}>Actualizar pagos</button></header>
 {loading&&<p role="status">Consultando dinero e historial…</p>}{error&&<p role="alert" className="client-warning">{error}</p>}{success&&<p role="status" className="client-success">{success}</p>}
 {data&&<><p>COT-{data.numero} · {data.cliente} · {data.sucursal} · {data.estado}</p><div className="payment-totals"><div><span>Total cotizado</span><strong>{money(data.total)}</strong></div><div><span>Dinero aplicado</span><strong>{money(data.aplicado)}</strong></div><div className="payment-pending"><span>Importe pendiente</span><strong>{money(data.pendiente)}</strong></div></div>
 <p className="client-note">Una transferencia informada o su comprobante no acreditan dinero. El personal autorizado verifica la recepción y aplica el pago a la oferta aceptada. Esto no crea un pedido ni aprueba producción o entrega.</p>
 {!data.pedidoFinalizado&&!data.cotizacionSustituida&&<><dl className="client-key-values"><div><dt>Anticipo de la oferta / cobertura admitida</dt><dd>{money(data.anticipoOfertado)} / {money(data.coberturaAnticipoOfertado)}</dd></div><div><dt>{data.estado==="CONFIRMADA"?"Anticipo al confirmar / cobertura admitida":"Anticipo según reglas actuales / cobertura admitida"}</dt><dd>{data.anticipoActual===null?"Configuración no disponible":`${money(data.anticipoActual)} / ${money(data.coberturaAnticipoActual??"0")}`}</dd></div></dl><p className="client-muted">La cobertura del anticipo cuenta sólo los medios admitidos por cada regla. El dinero recibido se conserva aunque la cotización venza. Las reglas de carga y producción se verifican por separado.</p></>}{data.pedidoFinalizado&&<p className="client-warning">El pedido fue cancelado o rechazado y no exige nuevos pagos. El dinero registrado se conserva y no se devuelve automáticamente. El personal autorizado puede registrar su devolución o un cobro que se haya recibido tarde.</p>}
 {data.pedidoCerrado&&<p className="client-note">El pedido está cerrado. Un cobro tardío puede registrarse y devolverse como excedente. Las aplicaciones conciliadas se conservan; la corrección administrativa del cierre está <span className="client-construction">En construcción</span>.</p>}{data.cotizacionSustituida&&!data.pedidoFinalizado&&<p className="client-warning">Esta cotización tiene una versión posterior del trabajo. Consultá sus importes antes de pagar. El dinero recibido se conserva; su aplicación a la nueva oferta aceptada debe registrarla un interno autorizado.</p>}
 <div className="client-actions">{data.puedeInformar&&<button className="client-button" disabled={locked} onClick={()=>choose({type:"informar"})}>Informar transferencia</button>}{data.aceptada&&data.mediosRecepcion.includes("EFECTIVO")&&permission("REGISTRAR_COBRO")&&<button className="client-button payment-confirm" disabled={locked} onClick={()=>choose({type:"recibir",medio:"EFECTIVO"})}>Registrar efectivo</button>}{data.aceptada&&data.mediosRecepcion.includes("TRANSFERENCIA")&&permission("ACREDITAR_PAGO")&&<button className="client-button payment-confirm" disabled={locked} onClick={()=>choose({type:"recibir",medio:"TRANSFERENCIA"})}>Registrar transferencia recibida</button>}</div>
 {hasAction&&action&&<form ref={formRef} className="client-form payment-form" onSubmit={e=>void submit(e)} key={`${action.type}-${action.payment?.codigoPublico??""}-${action.intento??""}-${action.medio??""}`}><h3>{names[action.type]}</h3><fieldset disabled={locked}>
 {action.payment&&<p>Pago {action.payment.referencia} · recibido {money(action.payment.importe)} · aplicado {money(action.payment.aplicado)} · devuelto {money(action.payment.devuelto)} · disponible {money(action.payment.disponible)}.</p>}
 {action.type==="aplicar"&&<p className="client-warning">Se aplicará a COT-{data.numero}, por {money(data.total)}; pendiente {money(data.pendiente)}. Si cubría una oferta anterior vencida o sustituida, la operación liberará esa aplicación y conservará su historia. El excedente queda disponible para devolución. Máximo aplicable ahora: {money(action.payment?.maximoAplicable??"0")}.</p>}
 {action.type==="devolver"&&<p className="client-warning">{data.pedidoCerrado?"Registrá sólo dinero ya devuelto que estuviera disponible como excedente; el importe aplicado al pedido cerrado se conserva.":"Registrá sólo dinero que ya devolviste. Primero se descuenta del disponible y luego de las aplicaciones; esto puede volver a bloquear la carga o los requisitos de producción y entrega."}</p>}
 {action.type==="recibir"&&<p>Medio: {action.medio==="EFECTIVO"?"Efectivo":"Transferencia"}. {action.intento?"Verificá el importe y la referencia reales; pueden diferir de lo informado por el cliente.":"Registrá el movimiento real con su referencia única."}</p>}
 {action.type!=="descartar"&&<label>Importe en pesos<input name="importe" required inputMode="decimal" pattern="[0-9]+([.][0-9]{1,2})?" maxLength={20} placeholder="Ingresá el importe; decimales con punto"/></label>}
 {action.type==="devolver"&&<label>Medio de devolución<select name="medio" required defaultValue=""><option value="" disabled>Seleccioná el medio</option><option value="EFECTIVO">Efectivo</option><option value="TRANSFERENCIA">Transferencia</option></select></label>}
 {["informar","recibir","devolver"].includes(action.type)&&<label>{action.type==="informar"?"Referencia informada":action.medio==="EFECTIVO"?"Número de recibo único en la sucursal":"Referencia única: banco, cuenta y movimiento"}<input name="referencia" required maxLength={160}/></label>}
 {(action.type==="recibir"||action.type==="devolver")&&<label>Fecha y hora del movimiento (hora de tu dispositivo)<input name="fecha" type="datetime-local" required/></label>}
 <label>Motivo / detalle<textarea name="motivo" required maxLength={300}/></label>
 {(action.type==="recibir"||action.type==="devolver")&&<label className="client-check"><input name="verificado" type="checkbox" required/>{action.type==="recibir"?"Verifiqué personalmente el dinero recibido; no estoy acreditando sólo un comprobante.":"Verifiqué que esta devolución ya fue realizada al cliente."}</label>}
 <div className="client-actions"><button className="client-button payment-confirm">{busy?"Registrando…":names[action.type]}</button><button type="button" className="client-button secondary" onClick={()=>setAction(null)}>Volver sin registrar</button></div></fieldset></form>}
 <section className="client-card"><h3>Transferencias informadas</h3>{!data.intentos.length?<p>No hay transferencias informadas para esta cotización.</p>:<div className="client-table-wrap"><table className="client-table"><thead><tr><th>Referencia informada</th><th>Importe declarado</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{data.intentos.map(i=><tr key={i.codigoPublico}><td>{i.referencia}<small>{date(i.fecha)}</small></td><td>{money(i.importe)}</td><td>{i.estado==="PENDIENTE"?"Pendiente de verificar":i.estado==="ACREDITADO"?"Dinero verificado":"Descartada"}</td><td><button className="client-button secondary" disabled={locked} onClick={()=>setEvidence({quote:i.cotizacion,parent:i.codigoPublico,kind:"intento"})}>Comprobantes</button>{i.estado==="PENDIENTE"&&<div className="client-actions">{permission("ACREDITAR_PAGO")&&<button className="client-button payment-confirm" disabled={locked} onClick={()=>choose({type:"recibir",intento:i.codigoPublico,medio:"TRANSFERENCIA"})}>Verificar recepción</button>}{(!internal||permission("ACREDITAR_PAGO"))&&<button className="client-button secondary" disabled={locked} onClick={()=>choose({type:"descartar",intento:i.codigoPublico})}>Descartar informe</button>}</div>}</td></tr>)}</tbody></table></div>}<p className="client-muted">Los comprobantes conservan su vínculo al informe después de registrar el pago.</p></section>
 <section><h3>Dinero recibido y conservado</h3>{!data.pagos.length?<p>No hay pagos recibidos en esta cotización o sus predecesoras dentro de tu acceso.</p>:data.pagos.map(p=><article className="client-card" key={p.codigoPublico}><h4>{p.medio==="EFECTIVO"?"Efectivo":"Transferencia"} · {money(p.importe)}</h4><p>{p.referencia} · {date(p.recibidoEn)}</p><p>Origen COT-{p.numeroOrigen} · {p.sucursal}</p><dl className="client-key-values"><div><dt>Aplicado actualmente</dt><dd>{money(p.aplicado)}</dd></div><div><dt>Devuelto</dt><dd>{money(p.devuelto)}</dd></div><div><dt>Disponible sin aplicar</dt><dd>{money(p.disponible)}</dd></div></dl><div className="client-actions"><button className="client-button secondary" disabled={locked} onClick={()=>setEvidence({quote:p.cotizacionOrigen,parent:p.codigoPublico,kind:"pago"})}>Comprobantes de este pago</button>{p.puedeAplicar&&<button className="client-button" disabled={locked} onClick={()=>choose({type:"aplicar",payment:p})}>Aplicar este pago</button>}{p.puedeDevolver&&<button className="client-button secondary" disabled={locked} onClick={()=>choose({type:"devolver",payment:p})}>Registrar devolución</button>}</div><details><summary>Historial de aplicaciones y devoluciones</summary>{!p.aplicaciones.length&&!p.devoluciones.length&&<p>Todavía no tiene aplicaciones ni devoluciones.</p>}{p.aplicaciones.map((v,i)=><p key={`a${i}`}>COT-{v.numero}: se aplicaron {money(v.importe)}; conserva {money(v.vigente)}. {date(v.fecha)} · {v.motivo}</p>)}{p.devoluciones.map(v=><p key={v.codigoPublico}>Devuelto {money(v.importe)} · {v.medio} · {v.referencia}. {date(v.fecha)} · {v.motivo}</p>)}</details></article>)}</section>
 {!!data.relacionadas.length&&<section className="client-card"><h3>Cotizaciones del mismo trabajo</h3><p>Para recuperar un pago después del vencimiento o una corrección, el cliente debe aceptar la nueva oferta. Abrí su detalle para aplicar el dinero allí.</p>{data.relacionadas.map(q=><p key={q.codigoPublico}><a href={`/${internal?"operacion":"cliente"}/cotizaciones/${q.codigoPublico}${internal?"/pagos":""}`}>COT-{q.numero}</a> · {money(q.total)} · {q.estado} · {q.aceptada?"Aceptada":"Sin aceptar"} · {q.sucursal}</p>)}</section>}
 {evidence&&<PaymentEvidence key={`${evidence.quote}-${evidence.kind}-${evidence.parent}`} {...evidence} internal={internal} onClose={()=>setEvidence(null)}/>}
 <details><summary>Últimos movimientos financieros de esta cotización</summary>{data.historial.length?data.historial.map((e,i)=><p key={i}>{date(e.fecha)} · {e.tipo} · {e.actor}: {e.motivo}</p>):<p>No hay movimientos.</p>}</details><p className="client-muted">Plataformas de pago automáticas · En construcción.</p></>}
 {uncertain&&<div role="alert" className="client-warning"><p>No pudimos confirmar la respuesta. Conservamos la misma operación para recuperarla sin duplicar el dinero.</p><button className="client-button" disabled={busy} onClick={()=>void execute()}>Recuperar operación financiera</button></div>}
 </section>;
}
