"use client";
import {useEffect,useRef,useState,type FormEvent} from "react";
import {secureMutation,MutationError} from "@/lib/secure-mutation";
import {readLocalPdf} from "@/lib/local-pdf";
import {isOptions,isQuote,quoteRead,modeLabels,type QuoteOptions,type QuoteInput,type DocumentInfo,type Mode,type Address} from "@/lib/quote-types";
type Row={key:string;documento:DocumentInfo;paginas:number;choice:string;copies:string;double:boolean;ends:string[];local:boolean};
type Combination=QuoteOptions["combinaciones"][number];
const choiceKey=(o:Combination)=>[o.servicio,o.formato,o.papel,o.color].join(":");
const emptyAddress:Address={calle:"",numero:"",referencias:"",territorio:{codigoPostal:"",localidad:"",provincia:""}};
export function QuoteForm({replaces}:{replaces?:string}){
 const[options,setOptions]=useState<QuoteOptions|null>(null),[rows,setRows]=useState<Row[]>([]),[branch,setBranch]=useState(""),[mode,setMode]=useState<Mode|"">(""),[point,setPoint]=useState(""),[payment,setPayment]=useState(""),[address,setAddress]=useState<Address>(emptyAddress);
 const[loading,setLoading]=useState(true),[reading,setReading]=useState(false),[busy,setBusy]=useState(false),[uncertain,setUncertain]=useState(false),[error,setError]=useState(""),[conflict,setConflict]=useState(false);
 const command=useRef<string|null>(null),reader=useRef<AbortController|null>(null),sending=useRef(false);const locked=loading||reading||busy||uncertain;
 async function load(initial=false){setLoading(true);setError("");try{const data=await quoteRead("/api/cliente/cotizaciones/opciones",isOptions);setOptions(data);setConflict(false);if(initial&&replaces){const old=await quoteRead(`/api/cliente/cotizaciones/${replaces}`,isQuote);const o=old.oferta;setBranch(o.sucursal.codigoPublico);setMode(o.modalidad);setPoint(o.punto??"");setPayment(o.medioPago);setAddress(o.direccion??emptyAddress);setRows(o.items.map(i=>({key:crypto.randomUUID(),documento:i.documento,paginas:i.trabajo.paginas,choice:[i.trabajo.servicio,i.trabajo.formato,i.trabajo.papel,i.trabajo.color].join(":"),copies:String(i.trabajo.copias),double:i.trabajo.dobleFaz,ends:i.trabajo.terminaciones,local:false})));}}catch(e){setError(e instanceof Error?e.message:"No pudimos consultar las opciones.");}finally{setLoading(false);}}
 useEffect(()=>{void load(true);return()=>reader.current?.abort();},[replaces]);
 function update(key:string,change:Partial<Row>){setRows(old=>old.map(r=>r.key===key?{...r,...change}:r));}
 async function files(list:FileList|null){if(!list||locked)return;setError("");if(rows.length+list.length>20){setError("Una cotización admite hasta 20 PDF.");return;}reader.current?.abort();const abort=new AbortController();reader.current=abort;setReading(true);
  try{const added:Row[]=[];const known=new Set(rows.map(r=>r.documento.sha256));for(const file of Array.from(list)){const d=await readLocalPdf(file,abort.signal);if(known.has(d.documento.sha256))throw new Error("Ese PDF ya está incluido. Cada archivo lleva una sola configuración homogénea.");known.add(d.documento.sha256);added.push({key:crypto.randomUUID(),...d,choice:"",copies:"",double:false,ends:[],local:true});}setRows(old=>[...old,...added]);}
  catch(e){if(!abort.signal.aborted)setError(e instanceof Error?e.message:"No pudimos leer el archivo.");}finally{if(!abort.signal.aborted)setReading(false);}
 }
 async function submit(event?:FormEvent){event?.preventDefault();if(busy||reading||loading||sending.current)return;setError("");
  if(!uncertain){if(!options?.configuracion||!options.revisionComercial||!branch||!mode||!payment||rows.length===0){setError("Seleccioná archivos y completá todas las opciones del trabajo.");return;}
   const items:QuoteInput["items"]=[];
   for(const row of rows){const o=options.combinaciones.find(x=>x.sucursal===branch&&choiceKey(x)===row.choice);if(!o||!Number.isInteger(Number(row.copies))||Number(row.copies)<1||Number(row.copies)>10000||row.double&&!o.dobleFaz||row.ends.some(e=>!o.terminaciones.includes(e))){setError("Revisá la configuración de cada archivo con las opciones vigentes de la sucursal.");return;}items.push({documento:row.documento,trabajo:{servicio:o.servicio,formato:o.formato,papel:o.papel,color:o.color,paginas:row.paginas,copias:Number(row.copies),dobleFaz:row.double,terminaciones:row.ends}});}
   const input:QuoteInput={operacion:crypto.randomUUID(),configuracion:options.configuracion,revisionComercial:options.revisionComercial,sucursal:branch,items,modalidad:mode,punto:mode==="RETIRO_PUNTO_ENTREGA"?point:null,direccion:mode==="ENVIO_DOMICILIO"?address:null,medioPago:payment,reemplaza:replaces??null};command.current=JSON.stringify(input);
  }
  if(!command.current)return;sending.current=true;setBusy(true);
  try{const r=await secureMutation("/api/cliente/cotizaciones",command.current,"application/json"),data:unknown=await r.json();if(!isQuote(data))throw new Error("No pudimos verificar la cotización guardada.");location.assign(`/cliente/cotizaciones/${data.codigoPublico}`);}
  catch(e){setError(e instanceof Error?e.message:"No pudimos cotizar.");if(e instanceof MutationError&&!e.uncertain){command.current=null;setUncertain(false);if(e.status===409)setConflict(true);}else setUncertain(true);sending.current=false;setBusy(false);}
 }
 const names=new Map([...(options?.formatos??[]),...(options?.papeles??[]),...(options?.servicios??[])].map(n=>[n.codigoPublico,n.nombre]));const choices=options?.combinaciones.filter(o=>o.sucursal===branch)??[];
 return <><p className="client-note">Los PDF se leen en tu dispositivo y todavía no se envían a la imprenta. Para cargarlos después deberás seleccionarlos otra vez; al salir no se guardan sus bytes. La carga privada, la vista previa validada y la confirmación del pedido están <strong>En construcción</strong>. Podés guardar una cotización real con estos datos provisionales.</p>
 {loading&&<p role="status">Consultando opciones actuales…</p>}{!loading&&!options?.disponible&&<section className="client-card client-empty"><h2>La imprenta está en preparación</h2><p>{options?.mensaje??"No pudimos consultar las opciones."}</p><button className="client-button secondary" onClick={()=>void load()}>Volver a consultar</button></section>}
 {options?.disponible&&<form className="client-form" onSubmit={submit}><fieldset disabled={locked||conflict}>
 <section className="client-card"><h2><span className="client-step">1</span>Archivos y sucursal</h2><label>Sucursal que realizará el trabajo<select aria-label="Sucursal que realizará el trabajo" required value={branch} onChange={e=>{setBranch(e.target.value);setPoint("");setRows(old=>old.map(r=>({...r,choice:"",ends:[],double:false})));}}><option value="">Seleccioná una sucursal</option>{options.sucursales.map(s=><option key={s.codigoPublico} value={s.codigoPublico}>{s.nombre} · {s.direccion}</option>)}</select></label><div className="client-file" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();void files(e.dataTransfer.files);}}><p><strong>Arrastrá tus PDF aquí o seleccionalos desde tu dispositivo.</strong></p><label>Seleccionar PDF<input type="file" accept="application/pdf,.pdf" multiple onChange={e=>{void files(e.target.files);e.target.value="";}}/></label><p className="client-muted">Máximo 10 MB por PDF y 20 archivos. El conteo se obtiene del documento. Un archivo tiene una única configuración de impresión.</p></div>{reading&&<p role="status">Leyendo PDF en este dispositivo…</p>}{replaces&&<p className="client-note">Esta oferta reemplazará la anterior sólo cuando se guarde correctamente. Los datos heredados se pueden revisar; la oferta nueva requerirá otra aceptación.</p>}</section>
 {rows.map((r,index)=>{const selected=choices.find(o=>choiceKey(o)===r.choice);return <section className="client-card" key={r.key}><div className="client-item-title"><h2>Archivo {index+1}</h2><button className="client-button secondary" type="button" onClick={()=>setRows(old=>old.filter(x=>x.key!==r.key))}>Quitar archivo {index+1}</button></div><div className="client-file"><strong>{r.documento.nombre}</strong><p>{r.paginas} páginas · {(r.documento.bytes/1024).toLocaleString("es-AR",{maximumFractionDigits:1})} KB</p><span className="client-muted">{r.local?"Leído localmente. Falta la inspección del servidor.":"Datos de la cotización anterior; el archivo no está cargado en el servidor."}</span></div><div className="client-grid"><div><label>Configuración de impresión · archivo {index+1}<select aria-label={`Configuración de impresión · archivo ${index+1}`} required value={r.choice} onChange={e=>update(r.key,{choice:e.target.value,double:false,ends:[]})}><option value="">Seleccioná servicio, formato, papel y color</option>{choices.map(o=><option key={choiceKey(o)} value={choiceKey(o)}>{names.get(o.servicio)} · {names.get(o.formato)} · {names.get(o.papel)} · {o.color==="COLOR"?"Color":"Blanco y negro"}</option>)}</select></label><label>Cantidad de copias · archivo {index+1}<input type="number" min={1} max={10000} step={1} required value={r.copies} onChange={e=>update(r.key,{copies:e.target.value})}/></label></div><div><h3>Opcionales</h3><label className="client-check"><input type="checkbox" checked={r.double} disabled={!selected?.dobleFaz} onChange={e=>update(r.key,{double:e.target.checked})}/>Doble faz</label>{selected?.terminaciones.map(id=><label className="client-check" key={id}><input type="checkbox" checked={r.ends.includes(id)} onChange={e=>update(r.key,{ends:e.target.checked?[...r.ends,id]:r.ends.filter(x=>x!==id)})}/>{names.get(id)}</label>)}{!selected&&<p className="client-muted">Elegí la configuración para consultar las terminaciones compatibles.</p>}</div></div></section>})}
 <section className="client-card"><h2><span className="client-step">2</span>Entrega y pago</h2><div className="client-grid"><label>Modalidad de entrega<select aria-label="Modalidad de entrega" required value={mode} onChange={e=>{setMode(e.target.value as Mode);setPoint("");}}><option value="">Seleccioná una modalidad</option>{options.modalidades.filter(m=>m!=="RETIRO_PUNTO_ENTREGA"||options.puntos.some(p=>p.sucursal===branch)).map(m=><option key={m} value={m}>{modeLabels[m]}</option>)}</select></label><label>Medio de pago preferido<select aria-label="Medio de pago preferido" required value={payment} onChange={e=>setPayment(e.target.value)}><option value="">Seleccioná un medio</option>{options.medios.map(m=><option key={m} value={m}>{m==="EFECTIVO"?"Efectivo":"Transferencia"}</option>)}</select></label></div>{mode==="RETIRO_PUNTO_ENTREGA"&&<label>Punto de entrega<select aria-label="Punto de entrega" required value={point} onChange={e=>setPoint(e.target.value)}><option value="">Seleccioná un punto</option>{options.puntos.filter(p=>p.sucursal===branch).map(p=><option key={p.codigoPublico} value={p.codigoPublico}>{p.nombre} · {p.direccion}</option>)}</select></label>}{mode==="ENVIO_DOMICILIO"&&<div className="client-grid">{([['calle','Calle'],['numero','Número'],['referencias','Referencias de entrega (opcional)']] as const).map(([key,label])=><label key={key}>{label}<input required={key!=="referencias"} maxLength={key==="numero"?30:key==="calle"?140:300} value={address[key]} onChange={e=>setAddress({...address,[key]:e.target.value})}/></label>)}{([['codigoPostal','Código postal'],['localidad','Localidad'],['provincia','Provincia']] as const).map(([key,label])=><label key={key}>{label}<input required maxLength={key==="codigoPostal"?24:120} value={address.territorio[key]} onChange={e=>setAddress({...address,territorio:{...address.territorio,[key]:e.target.value}})}/></label>)}</div>}<p className="client-muted">La cotización indicará el costo y una fecha estimada. Todavía no reserva un cupo. La seña o el pago previo, si corresponden, pueden exigir transferencia aunque el saldo se pague en efectivo.</p><p className="client-muted">Pasarelas de pago <span className="client-construction">En construcción</span></p></section>
 <div className="client-actions center"><button className="client-button" disabled={rows.length===0}>Cotizar trabajo</button></div></fieldset></form>}
 {error&&<p className="client-warning" role="alert">{error}</p>}{uncertain&&<div className="client-warning"><p>La respuesta no se pudo confirmar. Recuperá la misma operación antes de cambiar datos.</p><button className="client-button" disabled={busy} onClick={()=>void submit()}>Recuperar cotización</button></div>}{conflict&&<button className="client-button secondary" disabled={locked} onClick={()=>void load()}>Actualizar opciones y revisar</button>}
 </>;
}
