"use client";
import {useEffect,useState} from "react";
import {quoteRead,isQuoteList,money,date,type QuoteList} from "@/lib/quote-types";
export function QuoteListView(){
 const[data,setData]=useState<QuoteList|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 async function load(page=0){setBusy(true);setError("");try{setData(await quoteRead(`/api/cliente/cotizaciones?pagina=${page}`,isQuoteList));}catch(e){setError(e instanceof Error?e.message:"No pudimos consultar.");}finally{setBusy(false);}}
 useEffect(()=>{void load();},[]);
 return <><div className="client-actions"><a className="client-button" href="/cliente/cotizaciones/nueva">Preparar un pedido</a></div><section className="client-card"><h2>Mis cotizaciones</h2><p className="client-muted">Ofertas guardadas con sus precios y condiciones. Aceptar una cotización todavía no crea un pedido ni registra un pago.</p>{busy&&<p role="status">Consultando cotizaciones…</p>}{error&&<p className="client-warning" role="alert">{error}</p>}{error&&<button className="client-button secondary" onClick={()=>void load(data?.pagina??0)}>Volver a consultar</button>}{data?.total===0&&<div className="client-empty"><h3>Todavía no tenés cotizaciones</h3><p>Seleccioná tus PDF y elegí entre las opciones configuradas por la imprenta.</p></div>}{data&&data.total>0&&<><div className="client-table-wrap"><table className="client-table"><thead><tr><th>Cotización</th><th>Estado</th><th>Sucursal</th><th>Archivos</th><th>Vencimiento</th><th>Total</th><th>Acción</th></tr></thead><tbody>{data.elementos.map(q=><tr key={q.codigoPublico}><td>COT-{q.numero}</td><td><span className="client-state">{q.estado}</span>{q.aceptadaEn&&<p className="client-muted">Oferta aceptada</p>}</td><td>{q.sucursal}</td><td>{q.items}</td><td>{date(q.vigenteHasta)}</td><td>{money(q.total)}</td><td><a className="client-button secondary" href={`/cliente/cotizaciones/${q.codigoPublico}`}>Ver COT-{q.numero}</a></td></tr>)}</tbody></table></div><div className="client-actions"><button className="client-button secondary" disabled={busy||data.pagina===0} onClick={()=>void load(data.pagina-1)}>Anteriores</button><span>Página {data.pagina+1} · {data.total} cotizaciones</span><button className="client-button secondary" disabled={busy||(data.pagina+1)*data.tamano>=data.total} onClick={()=>void load(data.pagina+1)}>Siguientes</button></div></>}</section><section className="client-card"><h2>Mis pedidos</h2><p>Consultá los pedidos que ya confirmaste y sus reservas.</p><a className="client-button secondary" href="/cliente/pedidos">Ver mis pedidos</a></section></>;
}
