"use client";
import {useEffect,useState} from "react";
import "@/app/client.css";
type Page={elementos:{cotizacion:string;numero:number;cliente:string;estado:string;archivos:number;validos:number;aceptados:number}[];total:number;pagina:number};
export function ReceivedFiles({branch}:{branch:string}){
 const[data,setData]=useState<Page|null>(null),[page,setPage]=useState(0),[busy,setBusy]=useState(true),[error,setError]=useState("");
 async function load(){setBusy(true);setError("");try{const r=await fetch(`/api/operacion/sucursales/${branch}/archivos?pagina=${page}`,{cache:"no-store"}),v=await r.json();if(!r.ok||!Array.isArray(v.elementos))throw new Error(typeof v.mensaje==="string"?v.mensaje:"No pudimos consultar los archivos recibidos.");setData(v);}catch(e){setError(e instanceof Error?e.message:"No pudimos consultar.");}finally{setBusy(false);}}
 useEffect(()=>{void load();},[branch,page]);
 return <section className="client-card"><h2>Archivos recibidos</h2><p>PDF y vistas previas de las cotizaciones de esta sucursal. Aprobar trabajos, cobrar y producir sigue En construcción.</p>{busy&&<p role="status">Consultando…</p>}{error&&<p role="alert" className="client-warning">{error}</p>}{data&&!busy&&(data.elementos.length?<div className="client-table-wrap"><table className="client-table"><thead><tr><th>Cotización</th><th>Cliente</th><th>Estado</th><th>PDF vigentes</th><th>Preview aceptadas</th><th>Consulta</th></tr></thead><tbody>{data.elementos.map(q=><tr key={q.cotizacion}><td>COT-{q.numero}</td><td>{q.cliente}</td><td>{q.estado}</td><td>{q.validos}</td><td>{q.aceptados}</td><td><a href={`/operacion/cotizaciones/${q.cotizacion}/archivos`}>Revisar archivos</a></td></tr>)}</tbody></table></div>:<p>No hay cotizaciones con archivos recibidos en esta sucursal.</p>)}<div className="client-actions"><button className="client-button secondary" disabled={busy} onClick={()=>void load()}>Actualizar recibidos</button><button className="client-button secondary" disabled={busy||page===0} onClick={()=>setPage(p=>p-1)}>Anterior</button><button className="client-button secondary" disabled={busy||!data||(page+1)*25>=data.total} onClick={()=>setPage(p=>p+1)}>Siguiente</button></div></section>;
}
