import {MountainMark} from "@/components/mountain-brand";
import type {SiteContent,SiteSection} from "@/lib/website-types";
function Placeholder({label="Imagen de portada"}:{label?:string}){return <div className="website-image-placeholder"><span aria-hidden="true">▧</span><p>{label}</p><small>Sin configurar</small></div>;}
export function WebsiteView({content,requiresOwner=false,unavailable=false,preview=false}:{content:SiteContent|null;requiresOwner?:boolean;unavailable?:boolean;preview?:boolean}){
 const c=content,image=(id:string)=>`/api/${preview?"admin":"publico"}/pagina-web/imagenes/${id}`;
 const cards=c?.fichas.filter(f=>f.visible).sort((a,b)=>a.orden-b.orden||a.codigo.localeCompare(b.codigo))??[];
 function section(key:SiteSection){
  if(key==="PORTADA")return <section key={key} className="website-hero"><div>{!c&&<span className="website-eyebrow">PORTADA PENDIENTE</span>}<h1>{c?.titulo||(preview?"Título de portada pendiente":"El lugar para presentar tu imprenta.")}</h1><p className={c?"website-description":"website-placeholder-text"}>{c?.descripcion||(!c?"Título y descripción de la portada sin configurar.":"")}</p>{!c&&<><div className="website-placeholder-line"/><div className="website-placeholder-line short"/></>}{c&&(preview?<button disabled className="website-button">Preparar un trabajo</button>:<a className="website-button" href="/cliente/cotizaciones/nueva">Preparar un trabajo</a>)}</div>{c?.portada?<img className="website-hero-image" src={image(c.portada)} alt={c.portadaAlt}/>:!c?<Placeholder/>:<div className="website-wordmark" aria-hidden="true">{c.nombre.slice(0,1).toUpperCase()}</div>}</section>;
  if(key==="CATALOGO")return c&&!cards.length?null:<section key={key} className="website-section"><span className="website-eyebrow">CATÁLOGO PÚBLICO</span><h2>Productos y servicios</h2>{!c&&<p>Las fichas que publique el propietario aparecerán aquí.</p>}<div className="website-cards">{c?cards.map(f=><article className="website-product-card" key={f.codigo}>{f.imagenes.length>0&&<div className="website-card-images">{f.imagenes.map(i=><img key={i.codigo} src={image(i.codigo)} alt={i.alternativo} loading="lazy"/>)}</div>}<span className="website-eyebrow">{f.tipo==="PRODUCTO"?"Producto":"Servicio"}</span><h3>{f.nombre||"Nombre pendiente"}</h3><p>{f.descripcion}</p></article>):[1,2,3].map(n=><article className="website-placeholder-card" key={n}><Placeholder label="Imagen de ficha"/><h3>Ficha sin configurar</h3><div className="website-placeholder-line"/><div className="website-placeholder-line short"/></article>)}</div></section>;
  return c&&!c.correo&&!c.telefono&&!c.direccion?null:<section key={key} className="website-section website-contact"><div><span className="website-eyebrow">CONTACTO</span><h2>Datos de la imprenta</h2>{!c&&<p>Sin datos de contacto publicados.</p>}{c?.direccion&&<p>{c.direccion}</p>}</div><div>{c?<>{c.correo&&<p><a href={`mailto:${c.correo}`}>{c.correo}</a></p>}{c.telefono&&<p>{c.telefono}</p>}</>:<><div className="website-placeholder-line"/><div className="website-placeholder-line short"/></>}</div></section>;
 }
 return <div className="website">{preview&&<div className="website-preview-notice" role="status">Vista previa privada del borrador · Guardar no publica esta página</div>}<header className="website-header"><a href={preview?undefined:"/web"} className="website-brand">{c?.logo?<img className="website-logo" src={image(c.logo)} alt={c.logoAlt}/>:<span className="website-logo-placeholder" aria-hidden="true">◇</span>}<span>{c?.nombre||"Nombre de la imprenta"}{!c&&<small>Identidad sin configurar</small>}</span></a><nav aria-label="Página de la imprenta">{preview?<><button disabled>Iniciar sesión</button><button disabled className="website-button">Crear cuenta</button></>:<><a href="/acceso">Iniciar sesión</a><a className="website-button" href={requiresOwner?"/acceso":"/registro"}>Crear cuenta</a></>}</nav></header>
 <main>{unavailable?<div className="website-error" role="alert"><h1>Página temporalmente no disponible</h1><p>No pudimos consultar la publicación guardada. <a href="/web">Volver a intentar</a></p></div>:<>{!c&&<div className="website-notice"><strong>Sitio sin configurar</strong><p>Este es el espacio público de la imprenta. Su propietario todavía no publicó contenido; los recuadros indican dónde aparecerá.</p></div>}{(c?.secciones??["PORTADA","CATALOGO","CONTACTO"]).map(key=>section(key as SiteSection))}</>}</main>
 <footer className="website-footer"><span><MountainMark/> Software La Montaña · Demo local</span>{!preview&&<a href="/">Panel de inicio de la demo</a>}</footer></div>;
}
