"use client";
import {useEffect,useRef,useState} from "react";
import {secureMutation,MutationError} from "@/lib/secure-mutation";
import {useNavigationGuard} from "./navigation-boundary";
import {isImageSource,isWebImage,type ImageSource,type SourceFile,type WebImage} from "@/lib/website-media-types";
import type {SiteCard} from "@/lib/website-types";
function CandidateThumbnail({file}:{file:SourceFile}){const[failed,setFailed]=useState(false);return failed?<p className="web-image-placeholder">Miniatura no disponible. La importación informará si el archivo está dañado.</p>:<img loading="lazy" src={`/api/admin/pagina-web/origen/miniatura?${new URLSearchParams({ruta:file.ruta,sha256:file.sha256!})}`} alt={`Vista previa de ${file.nombre}`} onError={()=>setFailed(true)}/>;}
export function WebsiteMedia({folder,onFolderChange,images,cards=[],onImported,onUse,onLockChange,compact=false,fixedTarget,disabled=false}:{folder:string;onFolderChange:(folder:string)=>void;images:WebImage[];cards?:SiteCard[];onImported:(image:WebImage)=>void;onUse:(id:string,target:string)=>void;onLockChange:(locked:boolean)=>void;compact?:boolean;fixedTarget?:string;disabled?:boolean}){
 const[source,setSource]=useState<ImageSource|null>(null),[loading,setLoading]=useState(false),[sourceError,setSourceError]=useState(""),[epoch,setEpoch]=useState(0);
 const[target,setTarget]=useState(fixedTarget??"biblioteca"),[busy,setBusy]=useState(false),[uncertain,setUncertain]=useState(false),[results,setResults]=useState<Record<string,{ok:boolean;text:string}>>({});
 const command=useRef<{ruta:string;body:string;target:string}|null>(null),operationLocked=busy||uncertain,locked=operationLocked||disabled;
 useNavigationGuard({blocked:operationLocked});useEffect(()=>{onLockChange(operationLocked);return()=>onLockChange(false);},[operationLocked,onLockChange]);
 useEffect(()=>{const abort=new AbortController();setLoading(true);setSourceError("");setSource(null);const timer=setTimeout(()=>{void(async()=>{try{const r=await fetch(`/api/admin/pagina-web/origen?${new URLSearchParams({carpeta:folder})}`,{cache:"no-store",signal:abort.signal}),v:unknown=await r.json();if(!r.ok||!isImageSource(v))throw new Error("No pudimos comprobar la carpeta. Revisá la subcarpeta y volvé a intentar.");if(!abort.signal.aborted)setSource(v);}catch(e){if(!abort.signal.aborted)setSourceError(e instanceof Error?e.message:"No pudimos consultar la carpeta.");}finally{if(!abort.signal.aborted)setLoading(false);}})();},250);return()=>{clearTimeout(timer);abort.abort();};},[folder,epoch]);
 async function importFile(file?:SourceFile){if(busy)return;if(file){if(uncertain||!file.sha256)return;command.current={ruta:file.ruta,target:fixedTarget??target,body:JSON.stringify({operacion:crypto.randomUUID(),ruta:file.ruta,sha256:file.sha256})};}const c=command.current;if(!c)return;setBusy(true);try{
  const response=await secureMutation("/api/admin/pagina-web/imagenes/importar",c.body,"application/json"),v:unknown=await response.json();
  if(!v||typeof v!=="object"||!("imagen"in v)||!isWebImage(v.imagen)||!("existente"in v)||typeof v.existente!=="boolean")throw new Error("No pudimos verificar la importación.");
  onImported(v.imagen);if(c.target!=="biblioteca")onUse(v.imagen.codigo,c.target);
  setResults(s=>({...s,[c.ruta]:{ok:true,text:(v.existente?"La imagen ya estaba importada; se reutilizó la misma copia.":"Imagen importada a la biblioteca.")+(c.target!=="biblioteca"?" Asociación preparada: guardá el borrador para conservarla.":"")}}));command.current=null;setUncertain(false);
 }catch(e){setResults(s=>({...s,[c.ruta]:{ok:false,text:e instanceof Error?e.message:"No pudimos importar esta imagen."}}));if(e instanceof MutationError&&!e.uncertain){command.current=null;setUncertain(false);}else setUncertain(true);}finally{setBusy(false);}}
 return <section className="admin-card web-media"><div className="resource-toolbar"><h3>{compact?"Carpeta autorizada de imágenes":"Carpeta y biblioteca de imágenes"}</h3><button type="button" className="admin-button secondary" disabled={locked||loading} onClick={()=>setEpoch(v=>v+1)}>Actualizar carpeta</button></div>
 <p>Copiá los archivos usando el explorador de esta computadora. El programa sólo lee la entrada; las copias importadas se guardan por separado y no dependen del original.</p>
 {loading?<p role="status">Comprobando la carpeta…</p>:sourceError?<p className="admin-warning" role="alert">{sourceError}</p>:source&&<><p><strong>Ruta en esta computadora:</strong> <code className="web-host-path">{source.rutaHost}</code></p><p className={source.legible?"admin-info":"admin-warning"} role={source.legible?"status":"alert"}>{source.mensaje}</p><p>Subcarpeta consultada: <strong>{source.carpeta||"Raíz de la entrada"}</strong></p><div className="configuration-actions">{folder&&<button className="admin-button secondary" disabled={locked} onClick={()=>onFolderChange(folder.split('/').slice(0,-1).join('/'))}>Subir a carpeta anterior</button>}{source.subcarpetas.map(s=><button className="admin-button secondary" disabled={locked} key={s} onClick={()=>onFolderChange(s)}>Abrir {s.split('/').pop()}</button>)}</div>{source.limitada&&<p className="admin-warning">Se muestran hasta 100 entradas por carpeta. Organizá los archivos en subcarpetas más pequeñas para consultar el resto.</p>}</>}
 {!compact&&<><p className="admin-note">JPEG, PNG y WebP · hasta 10 MiB y 25 millones de píxeles. Se generan copias PNG sin metadatos del original y miniaturas. Guardar o importar no modifica la página pública.</p>
 {!fixedTarget&&<label className="web-image-target">Usar imagen como<select aria-label="Usar imagen como" disabled={locked} value={target} onChange={e=>setTarget(e.target.value)}><option value="biblioteca">Sólo importar a la biblioteca</option><option value="logo">Logotipo de la imprenta</option><option value="portada">Imagen de portada</option>{cards.map((c,i)=><option key={c.codigo} value={c.codigo}>Ficha {i+1} · {c.nombre||"sin nombre"}</option>)}</select></label>}
 <h4>Archivos de la carpeta</h4>{source?.legible&&!source.archivos.length&&<p className="admin-empty">No hay archivos en esta subcarpeta. Copiá imágenes y usá Actualizar carpeta.</p>}<div className="web-image-grid">{source?.archivos.map(file=><article key={`${file.ruta}:${file.sha256}`} className="web-image-tile">{file.estado==="CANDIDATA"&&file.sha256?<CandidateThumbnail file={file}/>:<div className="web-image-placeholder" aria-hidden="true">Archivo no admitido</div>}<h5>{file.nombre}</h5><p>{file.mensaje}</p>{file.bytes>0&&<small>{(file.bytes/1024/1024).toFixed(2)} MiB</small>}<button type="button" className="admin-button secondary" disabled={locked||file.estado!=="CANDIDATA"||!file.sha256} onClick={()=>void importFile(file)}>{fixedTarget||target!=="biblioteca"?"Importar y usar":"Importar a biblioteca"} · {file.nombre}</button>{results[file.ruta]&&<p className={results[file.ruta].ok?"admin-info":"admin-warning"} role={results[file.ruta].ok?"status":"alert"}>{results[file.ruta].text}</p>}</article>)}</div>
 {uncertain&&<div className="admin-warning" role="alert"><p>No pudimos confirmar la importación. Conservamos la misma operación; reintentá para conocer el resultado sin duplicar imágenes.</p><button className="admin-button" disabled={busy} onClick={()=>void importFile()}>Reintentar importación</button></div>}
 {!fixedTarget&&<><h4>Biblioteca persistente</h4><p className="admin-note">Estas copias siguen disponibles aunque retires los archivos de la carpeta original. Para asignarlas, elegí un destino arriba y usá su botón.</p>{!images.length?<p className="admin-empty">Todavía no hay imágenes importadas.</p>:<div className="web-image-grid">{images.map(i=><article className="web-image-tile" key={i.codigo}><img src={`/api/admin/pagina-web/imagenes/${i.codigo}/miniatura`} alt={i.nombre} loading="lazy"/><h5>{i.nombre}</h5><small>{i.ancho} × {i.alto} píxeles</small><button className="admin-button secondary" disabled={locked||target==="biblioteca"} onClick={()=>onUse(i.codigo,target)}>Usar {i.nombre}</button></article>)}</div>}</>}
 </>}
 </section>;
}
