DatabaseDirectory /var/lib/clamav
LocalSocket /tmp/clamd.sock
LocalSocketMode 660
TCPSocket 3310
TCPAddr 0.0.0.0
User clamav
LogTime yes
StreamMaxLength 10M
MaxFileSize 10M
MaxScanSize 128M
MaxScanTime 15000
MaxThreads 2
AlertExceedsMax yes
AlertEncrypted yes
ConcurrentDatabaseReload no
