import {mkdir,copyFile} from 'node:fs/promises';
import {createRequire} from 'node:module';
import {dirname,resolve} from 'node:path';
const require=createRequire(import.meta.url);
const root=dirname(require.resolve('pdfjs-dist/package.json'));
const {version}=require('pdfjs-dist/package.json');
const target=resolve(import.meta.dirname,'../public/pdfjs',version);
await mkdir(target,{recursive:true});
await copyFile(resolve(root,'build/pdf.worker.min.mjs'),resolve(target,'pdf.worker.min.mjs'));
await copyFile(resolve(root,'LICENSE'),resolve(target,'LICENSE'));
