import {isConfigurationDraft,type ConfigurationDraft} from "@/lib/configuration-types";
import {isCatalogState,type CatalogState,type ColorMode} from "@/lib/catalog-types";
export type Finding={nivel:"BLOQUEO"|"ADVERTENCIA"|"INFORMACION";codigo:string;area:string;fase:number;mensaje:string;sucursal:string|null};
export type ReviewOption={sucursal:string;servicio:string;formato:string;papel:string;color:ColorMode;dobleFaz:boolean;terminaciones:string[]};
export type Review={huella:string;borrador:ConfigurationDraft;catalogo:CatalogState;sucursales:{codigoPublico:string;nombre:string;activa:boolean}[];fase5Valida:boolean;hallazgos:Finding[];bloqueos:number;advertencias:number;opciones:ReviewOption[];puntosDisponibles:{punto:string;sucursal:string;nombre:string;zonaHoraria:string;costo:string;versionDisponibilidad:number}[]};
export type ReviewSimulation={version:number;revisionComercial:string;precio:{paginas:number;copias:number;carillas:number;hojas:number;subtotal:string;minimoPreparacionMinutos:number;lineas:{servicio:string;nombre:string;base:string;unidades:number;precioUnitario:string;importe:string}[]};costoEntrega:string;total:string;finanzas:{pagoPrevioRequerido:string;senaRequerida:string;saldo:string;revisionHumana:boolean;cargaRequiereAcreditacion:boolean};entrega:{zonaHoraria:string;inicioPreparacion:string;finPreparacion:string;llegadaEstimada:string|null;disponibleDesde:string|null};impresoras:{codigoPublico:string;nombre:string}[];recorrido:string[];observaciones:string[]};
function rec(v:unknown):v is Record<string,unknown>{return !!v&&typeof v==="object";}
const strings=(v:Record<string,unknown>,keys:string[])=>keys.every(k=>typeof v[k]==="string");
export function isReview(v:unknown):v is Review{return rec(v)&&typeof v.huella==="string"&&/^[a-f0-9]{64}$/.test(v.huella)&&isConfigurationDraft(v.borrador)&&isCatalogState(v.catalogo)&&typeof v.fase5Valida==="boolean"&&Number.isSafeInteger(v.bloqueos)&&Number.isSafeInteger(v.advertencias)&&Array.isArray(v.sucursales)&&v.sucursales.every(s=>rec(s)&&strings(s,["codigoPublico","nombre"])&&typeof s.activa==="boolean")&&Array.isArray(v.hallazgos)&&v.hallazgos.every(h=>rec(h)&&["BLOQUEO","ADVERTENCIA","INFORMACION"].includes(String(h.nivel))&&strings(h,["codigo","area","mensaje"])&&Number.isInteger(h.fase)&&(h.sucursal===null||typeof h.sucursal==="string"))&&Array.isArray(v.puntosDisponibles)&&v.puntosDisponibles.every(p=>rec(p)&&strings(p,["punto","sucursal","nombre","zonaHoraria","costo"])&&Number.isSafeInteger(p.versionDisponibilidad))&&Array.isArray(v.opciones)&&v.opciones.every(o=>rec(o)&&strings(o,["sucursal","servicio","formato","papel"])&&["BLANCO_NEGRO","COLOR"].includes(String(o.color))&&typeof o.dobleFaz==="boolean"&&Array.isArray(o.terminaciones)&&o.terminaciones.every(t=>typeof t==="string"));}
export function isReviewSimulation(v:unknown):v is ReviewSimulation{return rec(v)&&Number.isSafeInteger(v.version)&&strings(v,["revisionComercial","costoEntrega","total"])&&rec(v.precio)&&strings(v.precio,["subtotal"])&&["paginas","copias","carillas","hojas","minimoPreparacionMinutos"].every(k=>Number.isSafeInteger((v.precio as Record<string,unknown>)[k]))&&Array.isArray(v.precio.lineas)&&v.precio.lineas.every(l=>rec(l)&&strings(l,["servicio","nombre","base","precioUnitario","importe"])&&Number.isSafeInteger(l.unidades))&&rec(v.finanzas)&&strings(v.finanzas,["pagoPrevioRequerido","senaRequerida","saldo"])&&typeof v.finanzas.revisionHumana==="boolean"&&typeof v.finanzas.cargaRequiereAcreditacion==="boolean"&&rec(v.entrega)&&strings(v.entrega,["zonaHoraria","inicioPreparacion","finPreparacion"])&&["llegadaEstimada","disponibleDesde"].every(k=>(v.entrega as Record<string,unknown>)[k]===null||typeof (v.entrega as Record<string,unknown>)[k]==="string")&&Array.isArray(v.impresoras)&&v.impresoras.every(p=>rec(p)&&strings(p,["codigoPublico","nombre"]))&&Array.isArray(v.recorrido)&&v.recorrido.every(t=>typeof t==="string")&&Array.isArray(v.observaciones)&&v.observaciones.every(t=>typeof t==="string");}
export function optionKey(o:ReviewOption){return [o.sucursal,o.servicio,o.formato,o.papel,o.color].join(":");}
