import {type Quote,type Mode} from "./quote-types";
export type OrderPdf={item:string;archivo:string;nombre:string;sha256:string;bytes:number;paginas:number;aceptadaEn:string};
export type OrderSlot={modalidad:Mode;destino:string;origen:string;nombre:string;zonaHoraria:string;fecha:string;apertura:string;cierre:string;desde:string;hasta:string;cupoConfigurado:number;plazasLibres:number;costo:string};
export type OrderConditions={cotizadas:Quote["oferta"]["condiciones"];actuales:Quote["oferta"]["condiciones"];revisionHumana:boolean};
export type OrderReview={pedido:string|null;version:number;configuracion:string|null;numeroConfiguracion:number;huella:string|null;habilitada:boolean;bloqueos:string[];condiciones:OrderConditions|null;franja:OrderSlot|null;archivos:OrderPdf[]};
export type Order={version:number;estadoReserva:string;finalizadaEn:string|null;codigoPublico:string;numero:number;cotizacion:string;estado:string;confirmadaEn:string;aprobadaEn:string|null;configuracion:string;numeroConfiguracion:number;oferta:Quote["oferta"];condiciones:OrderConditions;reserva:OrderSlot;contacto:{receptor:string;telefono:string}|null;archivos:OrderPdf[];historial:{estado:string;motivo:string;fecha:string}[]};
export type OrderList={elementos:{codigoPublico:string;numero:number;estado:string;confirmadaEn:string;sucursal:string;total:string;modalidad:Mode}[];total:number;pagina:number};
const record=(v:unknown):v is Record<string,unknown>=>typeof v==="object"&&v!==null&&!Array.isArray(v);
const strings=(v:unknown):v is string[]=>Array.isArray(v)&&v.every(x=>typeof x==="string");
const conditions=(v:unknown)=>record(v)&&record(v.actuales)&&strings(v.actuales.instrucciones)&&typeof v.actuales.senaRequerida==="string"&&typeof v.actuales.pagoPrevioRequerido==="string"&&record(v.cotizadas)&&typeof v.revisionHumana==="boolean";
const slot=(v:unknown)=>record(v)&&["nombre","zonaHoraria","fecha","apertura","cierre","desde","hasta","modalidad","costo"].every(k=>typeof v[k]==="string")&&Number.isSafeInteger(v.cupoConfigurado)&&Number.isSafeInteger(v.plazasLibres);
const files=(v:unknown)=>Array.isArray(v)&&v.every(x=>record(x)&&typeof x.archivo==="string"&&typeof x.item==="string"&&typeof x.nombre==="string"&&typeof x.sha256==="string"&&Number.isSafeInteger(x.paginas));
export function isOrderReview(v:unknown):v is OrderReview{return record(v)&&Number.isSafeInteger(v.version)&&typeof v.habilitada==="boolean"&&strings(v.bloqueos)&&files(v.archivos)&&(typeof v.pedido==="string"||v.pedido===null&&typeof v.huella==="string"&&conditions(v.condiciones)&&slot(v.franja));}
export function isOrder(v:unknown):v is Order{return record(v)&&Number.isSafeInteger(v.version)&&typeof v.estadoReserva==="string"&&typeof v.codigoPublico==="string"&&Number.isSafeInteger(v.numero)&&typeof v.estado==="string"&&typeof v.cotizacion==="string"&&record(v.oferta)&&typeof v.oferta.total==="string"&&record(v.oferta.sucursal)&&Array.isArray(v.oferta.items)&&conditions(v.condiciones)&&slot(v.reserva)&&files(v.archivos)&&Array.isArray(v.historial)&&v.historial.every(e=>record(e)&&typeof e.estado==="string"&&typeof e.motivo==="string"&&typeof e.fecha==="string");}
export function isOrderList(v:unknown):v is OrderList{return record(v)&&Number.isSafeInteger(v.total)&&Number.isSafeInteger(v.pagina)&&Array.isArray(v.elementos)&&v.elementos.every(e=>record(e)&&typeof e.codigoPublico==="string"&&Number.isSafeInteger(e.numero)&&typeof e.total==="string"&&typeof e.estado==="string");}
export const orderState=(s:string)=>({PENDIENTE_REVISION:"Pendiente de revisión",CORRECCION_SOLICITADA:"Corrección solicitada",APROBADO:"Aprobado",RECHAZADO:"Rechazado",CANCELADO:"Cancelado"}[s]??s);
